### ISSUE TITLE
Pricing and Unit of Measure

### ISSUE THREAD

**Issue by kieronmoran** [Sage/SData-2.0#10]
When retrieving a Price record and Including the unitsOfMeasure, the feed only displays the first Unit of Measure found, not the actual unit of measure associated with the Product.

This is the same for JSON, XML & ATOM feeds.

This is the sData Request URL against the Stationary & Mart data.
http://localhost:5493/sdata/accounts50/GCRM/-/prices?where=reference eq 'BOARD001'&include=unitOfMeasure

The unit of measure for BOARD001 is "Each".

**Comment by darroncockram** [comment]
To be honest I'm surprised that the unitOfMeasure property isn't flagged as sme:isUnsupported="true" as in Sage 50 Accounts a price has not direct relationship with a unit of measure. There's just an indirect relationship via the product that is associated with the price resource. I've raised the issue with the Accounts team but I'm not sure what approach they'll decide to take.
