### ISSUE TITLE
How to create a trading account with a specific reference

### ISSUE THREAD

**Issue by Myddleware** [Sage/SData-2.0#103]
Hi Guys,
I 'm trying to create a trading account wit a specific reference. Here is the xml I send to create a trading account. I have filled the field reference with 8BS-UK : 
```
<?xml version="1.0" encoding="utf-8"?>
<entry xmlns:sdata="http://schemas.sage.com/sdata/2008/1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://www.w3.org/2005/Atom">
<id/>
<title/>
  <content/>
  <sdata:payload>
    <tradingAccount xmlns="http://schemas.sage.com/crmErp/2008" xmlns:sc="http://schemas.sage.com/sc/2009"
      sdata:uuid="f3b4f5c5-c3f5-4e33-a76c-dc3b314d04c3">
      <type>Unknown</type>
      <status>Open</status>
      <customerSupplierFlag>Customer</customerSupplierFlag>
      <companyPersonFlag>Company</companyPersonFlag>
      <reference>8BS-UK</reference>
      <name>Company8</name>
    </tradingAccount>
  </sdata:payload>
</entry>
```

However in Sage, the reference filed is recalculated with the name of the company so I have COMPANY8 : 
![sgae_reference](https://user-images.githubusercontent.com/11330301/32676268-5e0c14e2-c630-11e7-9d20-c2ff0d8f97be.png)

I know it is possible to set a specific reference when we manually create a trading account in Sage50 but I don't know how to do it via the API. Could you help me ? Thanks.
Best regards,
Stéphane

**Comment by darroncockram** [comment]
You can't set the reference on a trading account via the Sdata feeds I'm afraid.

**Comment by Myddleware** [comment]
Thanks for your answer, I will stop to search ;)
We have a work around. We will create first the trading account by putting the referenece in the name, so the reference will be initialized with the name (which will be the reference). Then we will update the name of the trading account with its real name.
Have a nice day.
