### ISSUE TITLE
Creating a new sales order returns an error, but does save to sage. 

### ISSUE THREAD

**Issue by dcoulter45** [Sage/SData-2.0#104]
I'm currently posting the following XML to sdata 

> <?xml version="1.0" encoding="utf-8"?>
>         <entry xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3.org/2005/Atom">
>           <id/>
>           <title/>
>           <content/>
>           <sdata:payload>
>             <salesOrder xmlns="http://schemas.sage.com/crmErp/2008" sdata:uuid="AE344617-63F8-47A0-81A1-A37B6628906D">
>               <date>2017-11-14</date>
>               <tradingAccount sdata:uuid="5ca19a94-076c-4d92-b3fa-89a09f0d44c4"/>
>               <subTotal>160.00</subTotal>
>               <salesOrderLines>
>                 <salesOrderLine>
>                   <commodity sdata:uuid="3f26e5ba-beea-424c-984b-2663d8098524"></commodity>
>                   <quantity>1</quantity>
>                   <actualPrice>200.00</actualPrice>
>                   <priceTax>0.00</priceTax>
>                   <netTotal>200.00</netTotal>
>                 </salesOrderLine>
>               </salesOrderLines>
>             </salesOrder>
>           </sdata:payload>
>         </entry>

The sales order does save to sage, however this error message gets returned which means there's isn't a reference number or sage uuid returned for newly created sales order. 

`error ApplicationDiagnosis POST operation failed - The changes you requested to the table were not successful because they would create duplicate values in the index, primary key, or relationship. Change the data in the field or fields that contain duplicate data, remove the index, or redefine the index to permit duplicate entries and try again. at Sage.Integration.Accounts50.SDOAdapter.IdentityMappingManager.CreateIdentityMapping(Dictionary 2 typeMappings, String& localID, String type, Guid ID) at Sage.Integration.Accounts50.SDOAdapter.IdentityMappingManager.AddIdentityMapping(Guid ID, String localID, String type) at Sage.Integration.Accounts50.SDOAdapter.Feeds.salesOrderFeedEntry.Add(IRequest request) at Sage.Integration.Accounts50.SDOAdapter.RequestHandler 2.OnPostRequest(IRequest request) at Sage.Integration.Accounts50.SDOAdapter.RequestHandler 2.PostRequest(IRequest request) at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.PostRequest(IRequest request) (-1)`

Any help with this would be much much appreciated.

**Comment by darroncockram** [comment]
Are you trying to use the same UUID on the salesOrder each time you post?

**Comment by dcoulter45** [comment]
Yes. I've just taken the first uuid out and it goes through fine now. Had assumed from the example in the documentation there had to be a UUID there.

Thankyou very much for the help.

**Comment by darroncockram** [comment]
You can provide a UUID if you want to but it must be unique for each new post request. If you omit the UUID one will be automatically generated for you and returned in the response.
