### ISSUE TITLE
Operation not allowed Error 

### ISSUE THREAD

**Issue by bagavan44** [Sage/SData-2.0#105]
"Operation is not allowed" error coming when I try to update the AR_Options table. I am trying to update NexeDepositNo field. Other tables its working fine. Is it the limitation of SData or Sage not allowing?

My Sage version is Sage 100 Advanced ERP 2015 (Ver 5.20.0.0)

**Comment by darroncockram** [comment]
Does the schema specify sme:canPut="true" for that resource kind?

**Comment by bagavan44** [comment]
<xs:element name="AR_Options" type="AR_Options--type" sme:canGet="true" sme:canPost="false" sme:canPut="false" sme:canDelete="false" sme:canSearch="false" sme:pluralName="AR_Options" sme:label="AR_Options" sme:canPagePrevious="true" sme:canPageNext="true" sme:canPageIndex="true" sme:supportsETag="false" sme:hasUuid="false" sme:hasTemplate="false" sme:batchingMode="None" sme:role="resourceKind" sme:isSyncSource="false" sme:isSyncTarget="false" /> 

Looks like it set to false only. Can we change this in Sage? If yes can anybody navigate me there?

**Comment by darroncockram** [comment]
There are no options to change the operations that are allowed in the Sdata feeds. If the sme:canPut flag is set to false in the schema then the adapter does not allow updates and there is no way to change this I'm afraid.
