### ISSUE TITLE
Decmial Places / fractionDigits

### ISSUE THREAD

**Issue by markayling** [Sage/SData-2.0#108]
Hi

By default all currency values returned via Sage 50 Accounts / SData feed appear to be formatted to 2 decimal places.  As I understand it there is a schema hint called fractionDigits which determines the number of decimal places to be returned - in the SData documentation it states:

_Maximum number of digits to the right of the decimal point for a decimal property value. This attribute is a hint for the user interface. A service consumer may ignore it and pass a  decimal value with more decimal digits. In this case the provider will round or truncate the value._

and

_The sdata/decimal type is a string representing a (possibly signed) rational number with a finite number of decimal places. The decimal point is a period. The string type is necessary since some languages, such as JavaScript, have difficulties in representing decimal numbers (for example, 0.1 + 0.2 === 0.3 is false in JavaScript)._

_The metadata elements $totalDigits and $fractionDigits allow a more precise description if it is required._

Does anyone know the method/syntax for overriding the fractionDigits hint when consuming an SData feed in C#?  And/or if this can be achieved by passing something in the URL if accessing the feed via a browser?

TIA

Mark

**Comment by darroncockram** [comment]
You would simply include extra digits in the decimal value of the payload wherever you wanted to. Note however that as per the quote from the specification the consumer may choose to ignore this and round or truncate the value you specify so the actual value persisted in the product may not be exactly the same as the value you submit to the feeds. This is essentially a convenience for consumers so they do not need to be aware of the number of decimal places each specific provider is capable of handling and 
 do not need to include and special cases on a per provider basis. If you submit more decimal places that the provider can handle it should seamlessly deal with it for you.
