### ISSUE TITLE
SData service stopping intermittently

### ISSUE THREAD

**Issue by dcoulter45** [Sage/SData-2.0#109]
Hi, we're currently running Sage 50c accounts (v24.1) on a windows server. However, on a couple of occasions the SData service has stopped working. Accessing any url's will simply timeout. 

On opening Sage, it says SData has stopped and restarting the service doesn't start it. It just continues to say it has stopped. The only way to restart it is by killing the process ID or restarting the server. 

Any help would be much appreciated.

Thanks,
Dean

**Comment by darroncockram** [comment]
Not a problem I've seen before. Is there anything in the Windows event log?

**Comment by dcoulter45** [comment]
There's nothing in the application log just before it stops working. Although there are a couple of errors like the following. I've checked this url with the servers IP in a browser and works fine. This is only an occasional error though, most of the time it works fine. 
![screen shot 2018-01-08 at 9 29 39 am](https://user-images.githubusercontent.com/2168465/34665108-ed4cad7a-f456-11e7-8bcc-3bf1352065b5.png)

The only thing I could see around the last time it stopped working in the system log was this, but I don't even know if it's related to Sage.
![screen shot 2018-01-08 at 9 28 24 am](https://user-images.githubusercontent.com/2168465/34665272-75b6e2e8-f457-11e7-8a09-8910ea73bce8.png)

**Comment by dcoulter45** [comment]
I should also mention that this wasn't really a problem during testing, but once we started using a sage account that's linked to sage drive, it's become a much more persistent problem.

**Comment by asterix187** [comment]
Hi, just to add we experience this on various sites as well. It seems worse on sites with multiple Sage 50 trading companies rather than just the one.

**Comment by dcoulter45** [comment]
Thanks, good to know it's not just me asterix187. 
Have you found any way to deal with the constant restarts? At the minute I'm having to manually restart the server every time it happens which is fairly frustrating to us and clients.

**Comment by darroncockram** [comment]
As indicated by the message the first error was caught so that will not be the cause as the error was handled in that case. The 2nd error is unrelated to Sdata so that's not it either. Difficult to say what the actual cause is as there is little detail to go on I'm afraid. Does it happen at random times or at regular intervals or durations?

**Comment by dcoulter45** [comment]
The intervals seem random unfortunately. One day it might do down every 10 minutes, and others it'll be fine all day. 

I was talking to another developer yesterday evening, who said that if connections made to sage aren't closed properly it can cause issues. But I assume the following php CURL should be fine?

> $curl = curl_init($url);
> curl_setopt($curl, CURLOPT_HTTPHEADER, array('Content-Type: application/atom+xml'));
> curl_setopt($curl, CURLOPT_USERPWD, $_ENV['SAGE_USER'] . ":" . $_ENV['SAGE_PASS']);
> curl_setopt($curl, CURLOPT_TIMEOUT, 5);
> curl_setopt($curl, CURLOPT_POST, 0);
> curl_setopt($curl, CURLOPT_RETURNTRANSFER, TRUE);
> $response = curl_exec($curl);
> curl_close($curl);

Also, would logging into Sage 50 using the same account that's used to make the SData requests cause any issues?

**Comment by darroncockram** [comment]
There have been no changes to the Sdata service itself in the v24 release. I'm just waiting to hear back on any changes to the Accounts adapter.

**Comment by copels** [comment]
> We have had to write a restart routine into our code that, when detecting a slow response, restarts the sData service.
> 
> There appears to have been a complete lack of thought of testing sData with v24 of Sage 50 as we have had lots of issues with customers.

Hi Asterix - I appreciate this is an old thread - but I'd be interested in the code you wrote. Our SAGE system grinds to a hold for no reason and we have to restart the services using taskkill.
