### ISSUE TITLE
PriceList Name

### ISSUE THREAD

**Issue by kieronmoran** [Sage/SData-2.0#11]
When retrieving a PriceList Payload from Sage50, the Name and Description fields both show the Description of the PriceList. The feed does not contain the PriceList Name.

URL:
$url: "http://localhost:5493/sdata/accounts50/GCRM/{C4C463BE-B098-4A7D-A23B-D1A92B8DCB59}/priceLists(34f90bbf-ca91-46b2-a701-67f34b86d66b"

Feed:
{
$url: "http://base2008r2server:5493/sdata/accounts50/GCRM/{C4C463BE-B098-4A7D-A23B-D1A92B8DCB59}/priceLists(34f90bbf-ca91-46b2-a701-67f34b86d66b)?format=atomentry"
$uuid: "34f90bbf-ca91-46b2-a701-67f34b86d66b"
$httpStatus: "OK"
$descriptor: ""
active: true
type: "Other"
name: "Public Price List"
reference: "P"
description: "Public Price List"
calculationMethod: null
calculationType: null
calculationAmount: null
calculationPercent: null
roundingMethod: null
taxCodes: null
pricesIncludesTax: false
currency: "GBP"
operatingCompanyCurrency: "GBP"
operatingCompanyCurrencyExchangeRate: 1
operatingCompanyCurrencyExchangeRateOperator: "*"
operatingCompanyCurrencyExchangeRateDate: null
startDate: null
endDate: null
primacyIndicator: false
commodities: null
tradingAccounts: null
notes: null
}

This is from the Stationary & Mart Data.

This is a problem as when we request a tradingAccountSummary feed, the PriceList field has the Name (i.e. PUBLIC or TRADEA) but there is no way to locate that actual PriceList feed using this value.

Any advice (or tricks) would be awesome.

**Comment by darroncockram** [comment]
Hmmm, the problem is that the tradingAccountSummaries feed is an extension feed specific to the Sage 50 Accounts implementation so there's actually no specification covering what fields it should expose or in what form. I've raised this with the Accounts team but it's possible they might not consider it a bug.

**Comment by kieronmoran** [comment]
Hi Darron, thanks for the reply.

Just to be clear, the actual problem here is that the PriceList feed does NOT contain the Price List name (as seen through the Sage 50 UI).

Regards,
Kieron

**Comment by darroncockram** [comment]
Ah, OK I think I misunderstood. I'll update the bug report accordingly.

In the meantime there is a potential workaround but it is specific to Sage 50 Accounts and other Sdata providers would not support it. There is a special undocumented extension property on the priceList  resource kind called applicationID that holds the value you are looking for. It's not serialised as part of the feed response but you could still query on it e.g. http://localhost:5493/sdata/accounts50/GCRM/-/PriceLists?where=applicationID%20eq%20%27TRADEA%27
