### ISSUE TITLE
Sage 50 Customer Additional Discount / Commodity Quantity Discount

### ISSUE THREAD

**Issue by Tedworthy** [Sage/SData-2.0#110]
We're in the middle of developing an integration solution for the new website of a client of ours, that connects to their Sage 50 Accounts system to retrieve product pricing and stock, amongst other things.

Our client uses the 'additional discount' feature for certain customers to select a discount structure, as per this screenshot (apologies for the quality):
![customer-record](https://user-images.githubusercontent.com/944950/34826638-48057592-f6cf-11e7-8df1-ed257a513848.jpg)

They then configure quantity discounts on the product record using those discount structures, as per this screenshot:
![product-record](https://user-images.githubusercontent.com/944950/34826639-4bf34e9a-f6cf-11e7-929a-03979bc30af4.jpg)

What we'd like to be able to do on the website side is to get all this information, via SData. At the moment we just query the price using the /commodities endpoint, but this only gives us a single price figure and no detailed discount structures, so we don't know if this price should be discounted for the particular customer and quantity they're buying on the site.

I've looked through the various endpoints available but none seem to provide this information, as far as I can tell. Ideally we could do with access to the above price matrix directly, and the 'additional discount' field value for each customer on the tradingAccount, but if this isn't possible then at least a method of requesting the calculated price for a certain commodity, trading account and quantity. I've seen the computePrice service operation which looks promising, but after trying to use this I get the same result as the person in issue #72 as the prices returned are not discounted, when I believe they should be.

So, is it possible to get the information from the screenshots above out of Sage 50 via SData, and if not, is the best way to work around this to use computePrice? Are there any other options available to us?

Your help would be much appreciated. :)

**Comment by asterix187** [comment]
There is a function of Sage 50 sData called ComputePrice, accessed like an endpoint, that is suppose to query the discount tables etc. We haven't managed to get it to return the correct data however.

**Comment by Tedworthy** [comment]
Yeah, that's the service operation mentioned in #72, I've also tried using it but can't get it to apply any discounts to the prices returned, even in cases where it should. It sounds like you've had a similar experience, as has the OP in #72. Strange, there doesn't seem a lot of point in implementing a method like ComputePrice (particularly with the parameters it has) unless the value returned depends on the trading account provided and the quantity required.

**Comment by asterix187** [comment]
Indeed! We have now given up trying to use it (The OP and I work together).
