### ISSUE TITLE
Which Sage Platforms use SDATA/JSON?

### ISSUE THREAD

**Issue by SeanGahan** [Sage/SData-2.0#112]
We currently have Sage 100 and it employs SDATA which looks like an ATOM feed + XML and would like to know which Sage products / platforms support JSON.

Thanks!

**Comment by darroncockram** [comment]
The Sdata 1.0 and 1.1 standards are effectively XML-based with some limited JSON support via the format parameter (see the generic parameters section on this page http://sage.github.io/SData-2.0/pages/core/0211/).

**Comment by SeanGahan** [comment]
Thank you.

**Comment by SeanGahan** [comment]
Darren, 
One quick question; I'd like to know your opinion of the eBusiness Web Service.  If you could, perhaps contrast it with sData.  Thank you!

**Comment by darroncockram** [comment]
I've not used the eBusiness Web Service personally so I can't offer any opinion on it I'm afraid. They key difference with Sdata is that it is an open standard implemented by multiple Sage products whereas the eBusiness Web Service is specific to Sage 100.
