### ISSUE TITLE
Setting the Delivery Address in an Invoice in Sage 50 using sdata

### ISSUE THREAD

**Issue by jwilliamson1098** [Sage/SData-2.0#113]
So I can successfully create an invoice using sdata interface, but when I set any sort of address it either throws an error or is ignored.

I've tried setting tradingAccountFeedEntry.postalAddresses.Entries but this is readonly it seems. Registered address can be written but is ignored.

Does anyone have example code for setting the billing and delivery address for an invoice or is it not possible, just taking the defaults from Sage 50?

**Comment by asterix187** [comment]
You will need to create an object of PostalAddressFeed and assign the object invoice.

Something like:

postalAddressFeed postalAddresses = new postalAddressFeed();
postalAddressFeedEntry postalAddress = new postalAddressFeedEntry();

postalAddress.address1 = "Test Road";
postalAddress.type = "Shipping";
postalAddress.name = "Delivery Address";
postalAddresses.Entries.Add(postalAddress);

sage50Invoice.postalAddresses = postalAddresses;

**Comment by asterix187** [comment]
Just to add, your code is trying to set the address against the trading account. You don't actually need to have/add any delivery addresses against the company. You can just add individual addresses against the invoice record.

You should be setting it as a salesInvoiceFeedEntry.

salesInvoiceFeedEntry sage50Invoice = new salesInvoiceFeedEntry();
