### ISSUE TITLE
reliable posting

### ISSUE THREAD

**Issue by bedsDev** [Sage/SData-2.0#116]
hello, refer to the document of Reliable posting?
is it still working?

I tried to http://localhost:5493/sdata/Accounts50/GCRM/-/salesOrders?trackingID=c1d2fa31-2708-4690-b9b4-e76c66aa84a6

but I cannot find the response LOCATION header.

**Comment by bedsDev** [comment]
Reliable Posting seems not working. When I use the same the same uuid, it cannot prevent the same salesOrder writing to SAGE. I am using Sage 50 Accounts Professional.

Anyone has any idea?

thanks in advance

**Comment by darroncockram** [comment]
Having said that it is not possible to generate a new salesOrder with the same UUID as an existing one. Any attempt to do so would return an error.

**Comment by asterix187** [comment]
Surely its about time Sage open sourced the Sage 50 sData files and let us, as a community, sort out the problems?

**Comment by bedsDev** [comment]
@asterix187 I wish too.

**Comment by bedsDev** [comment]
@darroncockram thanks for the comments.

**Comment by asterix187** [comment]
@darroncockram who do we need to ask to make this happen?

**Comment by darroncockram** [comment]
There are no plans to open source the adapter I'm afraid. There was some talk a while back about making the SIF open source but this did not go forwards and it was instead made freely distributable (in binary format only and restrictions on disassembly/decompilation).

It is certainly possible to write your own Sdata adapters if you wanted to. The SIF makes this relatively straight forward. I did create some videos on this that were posted to YouTube a good few years back but it looks like these are no longer available on the official Sage channel. I'll see if I still have a copy of them somewhere.

**Comment by darroncockram** [comment]
I found some pretty raw versions of the videos that I've uploaded to YouTube here:
https://www.youtube.com/watch?v=IqoK0OEklsE&list=PLYWbNNVt4fEztYOiuLCAI_EwCQ6dMBoKG

They are quite old videos and I was using Visual Studio 2005 at the time, but the concepts are still the same and should work fine on more up to date versions of Visual Studio. Apologies for the quality of the videos. There were some better quality, professionally edited versions but I can't find those anywhere.

**Comment by asterix187** [comment]
Thanks Darron. To be honest we have written our own sData type wrapper now that gives us full control over the data and works with things like ComputePrice, active/inactive flags and so forth. I will give the relevant people a nudge next time I am in Newcastle.

**Comment by bedsDev** [comment]
@darroncockram thanks
