### ISSUE TITLE
TradingAccountSummaries Updated Date

### ISSUE THREAD

**Issue by kieronmoran** [Sage/SData-2.0#12]
When requesting a feed of TradingAccountSummaries, the updated date always shows the current DateTime.

Is this by design?

URL:
http://localhost:5493/sdata/accounts50/GCRM/-/tradingAccountSummaries?count=5&select=updated&format=xml

**Comment by darroncockram** [comment]
No, that's incorrect as the updated property should be the date and time on which the resource was last changed. I've passed this on to the Accounts team.
