### ISSUE TITLE
Carrier Nominal Code & Delivery Address

### ISSUE THREAD

**Issue by tombfi** [Sage/SData-2.0#123]
I'm looking to set the Nominal Code under Carriage on the Footer Tab of a Sales Order (Sage Accounts 50):
![image](https://user-images.githubusercontent.com/15382135/46351030-3d1f2480-c64e-11e8-84a2-777b61123ada.png)
I've looked through the available fields but I can't match this up to anything in sData, would this require the carrierTradingAccount to be set?

Also has the issue with the first line of the delivery address been resolved? I've tried: name, reference & description under: postalAddresses. I had a look through the other comments but couldn't see a final resolution to this issue? Is there a way around this now?

**Comment by darroncockram** [comment]
I don't think that field is exposed to the Sdata feeds by the Sage 50 Accounts adapter I'm afraid.

> Also has the issue with the first line of the delivery address been resolved?

Do you mean #53 . If so I'm afraid that the delivery name is still not exposed to the Sage 50 Accounts adapter.

**Comment by tombfi** [comment]
Thanks for coming back to me. Yes, I'm looking at something similar to #53, is there any way around this at all? The project I'm working on is to send orders from a website (specifically WooCommerce) and create orders for these into Sage Automatically, is my best option to build my own API for Sage instead or do you know of something else that will do the same? Ideally I'd like to push / pull data from the website rather than run a scheduled task from the Sage machine?

**Comment by darroncockram** [comment]
If the Sdata feeds do not support the requirements then the only alternative would be to use SDO (the Sage 50 Accounts SDK). That would require joining the developer programme https://my.sage.co.uk/public/help/askarticle.aspx?articleid=33851. Beyond that there may be existing 3rd party add ons that do what you need (they will have used SDO to develop this) but I couldn't say for sure on that front.
