### ISSUE TITLE
Sage 50 Credit Note

### ISSUE THREAD

**Issue by davidhendrickmb** [Sage/SData-2.0#124]
Hi there,
I'm trying to create a new credit note using the C# SData connection. I am getting the error below, could you please let me know what I might be doing wrong? I'm pretty much creating an invoice in reverse, which I have working.

`POST operation failed - Invalid index specified for Item retrieval

   at System.RuntimeType.ForwardCallToInvokeMember(String memberName, BindingFlags flags, Object target, Int32[] aWrapperTypes, MessageData& msgData)
   at Sage.Integration.Accounts50.SDOAdapter.ISDOFields.Item(Object& Index)
   at RuntimeRequestHandler54bea531667348ed932106fd7e123c1f.CopyPropertiesToSDOObject(ISDOFields , FeedEntry , IdentityMappingManager )
   at Sage.Integration.Accounts50.SDOAdapter.SDORequestHandler.OnPostRecordRequest(SDOWorkspaceScope scope, ISDORecord record, FeedEntry feedEntry)
   at Sage.Integration.Accounts50.SDOAdapter.SDORequestHandler.OnPostRequest(IRequest request, FeedEntry feedEntry)
   at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.OnPostRequest(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.PostRequest(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.PostRequest(IRequest request) (-1)`

Thanks,
David

**Comment by darroncockram** [comment]
Do you have an example of the payload you are sending? Also can you confirm which endpoint you are POSTing to please?

**Comment by davidhendrickmb** [comment]
Hi @darroncockram,
I'm using this endpoint "http://servername:5493/sdata/accounts50/-/-".
I've attached what I'm doing below. I'm basically trying to create credit notes an existing invoice.
Thanks,
David



`var service = GetNewSdataService();
                    var originvoice = new SDataResourceCollectionRequest(service);
                    originvoice.ContractName = "GCRM";
                    originvoice.ResourceKind = "salesInvoices";
                    originvoice.QueryValues.Add("where", "reference eq'" + originalInvoiceNumber + "'");
                    originvoice.QueryValues.Add("include", "salesInvoiceLines");
                    AtomFeed originvFeed = service.ReadFeed(originvoice);
                    AtomEntry origInvEntry = originvFeed.Entries.First();
                    var OrigInvPayload = origInvEntry.GetSDataPayload();
                    int ReservationId = Convert.ToInt32(OrigInvPayload.Values["customerReference"]);
                    var Reservation = context.Reservations
                                            .Include("VenueMeta")
                                            .Include(r => r.Invoices)
                                            .First(r => r.ReservationId == ReservationId);
                    
                    AtomFeed feed;
                    AtomFeed taxfeed;
                    AtomFeed commodfeed;
                    AtomEntry entry;
                    AtomEntry lineEntry;
                    SDataPayload payload;
                    SDataPayload linePayload;

                    // Get Customer Details
                    var rcu = new SDataResourceCollectionRequest(service);
                    rcu.ContractName = "GCRM";
                    rcu.ResourceKind = "tradingaccounts";
                    rcu.QueryValues.Add("where", "reference eq'" + OrigInvPayload.Values["CustomerId"].ToString() + "'");
                    feed = service.ReadFeed(rcu);
                    SDataPayload CustPayload = feed.Entries.First().GetSDataPayload();

                    string CommodityReference = GetAutoCommodity(Reservation);


                    // Get Commodity (Product) Details
                    var commodReq = new SDataResourceCollectionRequest(service);
                    commodReq.ContractName = "GCRM";
                    commodReq.ResourceKind = "commodities";
                    commodReq.QueryValues.Add("where", "reference eq'" + CommodityReference + "'");
                    commodfeed = service.ReadFeed(commodReq);
                    SDataPayload CommodPayload = commodfeed.Entries.First().GetSDataPayload();


                    // read the template for accounts
                    var tru1 = new SDataTemplateResourceRequest(service);
                    tru1.ContractName = "GCRM";
                    tru1.ResourceKind = "salesCredits";

                    // read the entry from the server
                    entry = service.ReadEntry(tru1);

                    // TODO: Make changes to the entry payload
                    payload = entry.GetSDataPayload();
                    payload.Values["CustomerId"] = OrigInvPayload.Values["CustomerId"].ToString();
                    payload.Values["tradingAccount"] = CustPayload;
                    payload.Values["type"] = "Product Credit Note";
                    payload.Values["customerReference"] = Reservation.ReservationId;
                    payload.Values["reference2"] = OrigInvPayload.Values["reference"].ToString();
                    payload.Values["text1"] = "Credited duplicate for invoice " + OrigInvPayload.Values["reference"].ToString();
                    
                    // Create invoice line
                    var tsol = new SDataTemplateResourceRequest(service);
                    tsol.ContractName = "GCRM";
                    tsol.ResourceKind = "salesCreditLines";
                    lineEntry = service.ReadEntry(tsol);
                    linePayload = lineEntry.GetSDataPayload();
                    linePayload.Values["quantity"] = "1";
                    linePayload.Values["type"] = "2";
                    linePayload.Values["commodity"] = CommodPayload;

                    var invoiceLineQuery = new SDataResourceCollectionRequest(service);
                    invoiceLineQuery.ContractName = "GCRM";
                    invoiceLineQuery.ResourceKind = "salesInvoiceLines";
                    invoiceLineQuery.QueryValues.Add("where", "reference eq'" + OrigInvPayload.Values["reference"].ToString() + "'");
                    AtomFeed invoiceLineFeed = service.ReadFeed(invoiceLineQuery);
                    var invoiceLinePayload = invoiceLineFeed.Entries.FirstOrDefault().GetSDataPayload();

                    linePayload.Values["actualPrice"] = (Convert.ToDouble(invoiceLinePayload.Values["actualPrice"]));
                    linePayload.Values["netTotal"] = (Convert.ToDouble(invoiceLinePayload.Values["netTotal"]));
                    linePayload.Values["grossTotal"] = (Convert.ToDouble(invoiceLinePayload.Values["grossTotal"]));

                    linePayload.Values["text"] = "Credit for duplicate invoice reference " + OrigInvPayload.Values["reference"].ToString();


                    // Add invoice line to invoice
                    SDataPayloadCollection LinesCollection = new SDataPayloadCollection();
                    LinesCollection.Add(linePayload);
                    payload.Values["salesCreditLines"] = LinesCollection;


                    entry.SetSDataPayload(payload);

                    var sru1 = new SDataSingleResourceRequest(service);
                    sru1.ContractName = "GCRM";
                    sru1.ResourceKind = "salesCredits";

                    var newEntry = service.CreateEntry(sru1, entry);
                    SDataPayload newEntryPayload = newEntry.GetSDataPayload();`

**Comment by darroncockram** [comment]
Nothing leaps out as an obvious issue there but here's a working payload from a quick test that I've just run. All you should need to do is set the tradingAccount UUID to a valid value from your dataset.

```XML
<?xml version="1.0" encoding="utf-8"?>
<entry xmlns:atom="http://www.w3.org/2005/Atom" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cf="http://www.microsoft.com/schemas/rss/core/2005" xmlns="http://www.w3.org/2005/Atom" xmlns:http="http://schemas.sage.com/sdata/http/2008/1" xmlns:sdatasync="http://schemas.sage.com/sdata/sync/2008/1" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:sme="http://schemas.sage.com/sdata/sme/2007" xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <author />
  <sdata:payload>
    <salesCredit xmlns="http://schemas.sage.com/crmErp/2008">
      <active xsi:nil="true" />
      <reference xsi:nil="true" />
      <reference2 xsi:nil="true" />
      <status xsi:nil="true" />
      <statusFlag xsi:nil="true" />
      <statusFlagText xsi:nil="true" />
      <type>Service Credit</type>
      <tradingAccount sdata:uuid="36fae95e-0c9b-416f-81f7-33f9f5e91470" />
      <customerReference xsi:nil="true" />
      <opportunity xsi:nil="true" />
      <pricelist xsi:nil="true" />
      <copyFlag xsi:nil="true" />
      <date xsi:nil="true" />
      <time xsi:nil="true" />
      <taxDate xsi:nil="true" />
      <taxCodes xsi:nil="true" />
      <postalAddresses xsi:nil="true" />
      <deliveryMethod xsi:nil="true" />
      <deliveryTerms xsi:nil="true" />
      <deliveryRule xsi:nil="true" />
      <deliveryDate xsi:nil="true" />
      <carrierCompany xsi:nil="true" />
      <carrierTradingAccount xsi:nil="true" />
      <carrierNetPrice>80.00</carrierNetPrice>
      <carrierTaxPrice>20.00</carrierTaxPrice>
      <carrierTotalPrice>100.00</carrierTotalPrice>
      <carrierSalesInvoice xsi:nil="true" />
      <carrierTaxCodes xsi:nil="true" />
      <carrierReference xsi:nil="true" />
      <currency xsi:nil="true" />
      <operatingCompanyCurrency xsi:nil="true" />
      <operatingCompanyCurrencyExchangeRate xsi:nil="true" />
      <operatingCompanyCurrencyExchangeRateOperator xsi:nil="true" />
      <operatingCompanyCurrencyExchangeRateDate xsi:nil="true" />
      <customerTradingAccountCurrency xsi:nil="true" />
      <customerTradingAccountCurrencyExchangeRate xsi:nil="true" />
      <customerTradingAccountCurrencyExchangeRateOperator xsi:nil="true" />
      <customerTradingAccountCurrencyExchangeRateDate xsi:nil="true" />
      <buyerContact>
        <contactGroups xsi:nil="true" />
        <active xsi:nil="true" />
        <reference xsi:nil="true" />
        <reference2 xsi:nil="true" />
        <status xsi:nil="true" />
        <type xsi:nil="true" />
        <gender xsi:nil="true" />
        <fullName>Joe Bloggs</fullName>
        <salutation xsi:nil="true" />
        <firstName xsi:nil="true" />
        <preferredName xsi:nil="true" />
        <familyName xsi:nil="true" />
        <title xsi:nil="true" />
        <middleName xsi:nil="true" />
        <suffix xsi:nil="true" />
        <financialAccounts xsi:nil="true" />
        <age xsi:nil="true" />
        <dateOfBirth xsi:nil="true" />
        <nationality xsi:nil="true" />
        <language xsi:nil="true" />
        <maritalStatus xsi:nil="true" />
        <countryOfResidence xsi:nil="true" />
        <nationalInsuranceNumber xsi:nil="true" />
        <taxReference xsi:nil="true" />
        <postalAddresses xsi:nil="true" />
        <phones xsi:nil="true" />
        <emails xsi:nil="true" />
        <website xsi:nil="true" />
        <tradingAccount xsi:nil="true" />
        <bankAccounts xsi:nil="true" />
        <jobTitle xsi:nil="true" />
        <companyContext xsi:nil="true" />
        <user xsi:nil="true" />
        <primacyIndicator xsi:nil="true" />
        <opportunities xsi:nil="true" />
        <salesQuotations xsi:nil="true" />
        <salesOrders xsi:nil="true" />
        <salesOrderDeliveries xsi:nil="true" />
        <salesInvoices xsi:nil="true" />
        <salesCredits xsi:nil="true" />
        <purchaseOrders xsi:nil="true" />
        <purchaseOrderDeliveries xsi:nil="true" />
        <interactions xsi:nil="true" />
        <projects xsi:nil="true" />
        <notes xsi:nil="true" />
      </buyerContact>
      <salespersons xsi:nil="true" />
      <salesCreditLines>
        <salesCreditLine>
          <originatorDocumentLine xsi:nil="true" />
          <active xsi:nil="true" />
          <reference xsi:nil="true" />
          <reference2 xsi:nil="true" />
          <status xsi:nil="true" />
          <type>Free Text</type>
          <number xsi:nil="true" />
          <commodity xsi:nil="true" />
          <text>An example</text>
          <deliveryTerms xsi:nil="true" />
          <deliveryDate xsi:nil="true" />
          <carrierTradingAccount xsi:nil="true" />
          <carrierNetPrice xsi:nil="true" />
          <carrierTaxPrice xsi:nil="true" />
          <carrierTotalPrice xsi:nil="true" />
          <carrierSalesInvoiceLine xsi:nil="true" />
          <carrierTaxCodes xsi:nil="true" />
          <carrierReference xsi:nil="true" />
          <unitOfMeasure xsi:nil="true" />
          <quantity>5.00</quantity>
          <initialPrice xsi:nil="true" />
          <pricelist xsi:nil="true" />
          <settlementDiscountType xsi:nil="true" />
          <settlementDiscountAmount xsi:nil="true" />
          <settlementDiscountPercent xsi:nil="true" />
          <settlementDiscountTerms xsi:nil="true" />
          <invoiceLineDiscountType xsi:nil="true" />
          <invoiceLineDiscountAmount xsi:nil="true" />
          <invoiceLineDiscountPercent xsi:nil="true" />
          <invoiceLineSubtotalDiscountType xsi:nil="true" />
          <invoiceLineSubtotalDiscountAmount xsi:nil="true" />
          <invoiceLineSubtotalDiscountPercent xsi:nil="true" />
          <actualPrice xsi:nil="true" />
          <netTotal>100.00</netTotal>
          <chargesTotal xsi:nil="true" />
          <discountTotal xsi:nil="true" />
          <taxCodes />
          <priceTax xsi:nil="true" />
          <taxTotal>20.00</taxTotal>
          <grossTotal>120.00</grossTotal>
          <costTotal xsi:nil="true" />
          <project xsi:nil="true" />
          <financialAccounts xsi:nil="true" />
          <notes xsi:nil="true" />
        </salesCreditLine>
      </salesCreditLines>
      <lineCount xsi:nil="true" />
      <originatorDocument xsi:nil="true" />
      <contract xsi:nil="true" />
      <settlementDiscountType xsi:nil="true" />
      <settlementDiscountAmount xsi:nil="true" />
      <settlementDiscountPercent xsi:nil="true" />
      <settlementDiscountTerms xsi:nil="true" />
      <settlementDiscountIncludedInTotal xsi:nil="true" />
      <invoiceDiscountType xsi:nil="true" />
      <invoiceDiscountAmount xsi:nil="true" />
      <invoiceDiscountPercent xsi:nil="true" />
      <invoiceAdditionalDiscount1Type xsi:nil="true" />
      <invoiceAdditionalDiscount1Amount xsi:nil="true" />
      <invoiceAdditionalDiscount1Percent xsi:nil="true" />
      <invoiceAdditionalDiscount2 xsi:nil="true" />
      <invoiceAdditionalDiscount2Amount xsi:nil="true" />
      <invoiceAdditionalDiscount2Percent xsi:nil="true" />
      <netTotal xsi:nil="true" />
      <discountTotal xsi:nil="true" />
      <chargesTotal xsi:nil="true" />
      <taxTotal xsi:nil="true" />
      <grossTotal xsi:nil="true" />
      <costTotal xsi:nil="true" />
      <text1 xsi:nil="true" />
      <text2 xsi:nil="true" />
      <projects xsi:nil="true" />
      <financialAccounts xsi:nil="true" />
      <interactions xsi:nil="true" />
      <user xsi:nil="true" />
      <notes xsi:nil="true" />
    </salesCredit>
  </sdata:payload>
</entry>

**Comment by davidhendrickmb** [comment]
Hi Darron,
I am setting the tradingAccount from the CustPayload object, is this not sufficient? This works for an invoice.

**Comment by darroncockram** [comment]
What I mean is that the above payload works but you could not POST it to your dataset unless the UUID specified in the tradingAccount is changed to a valid identifier for a record in your dataset.

**Comment by darroncockram** [comment]
> Sorry, I'm still not fully following. The CustPayload object is a valid customer within Sage, so I assume this is ok? How would I go about adding the UUID via the .Net implementation?

In the example payload above I have this element:

`<tradingAccount sdata:uuid="36fae95e-0c9b-416f-81f7-33f9f5e91470" />`

The value of this is the UUID of a tradingAccount in the dataset I was testing with. This will not exist in your dataset but if you replace the value with a UUID of a creditor that does exist in your dataset then the payload should work if you POST it.

> Please see a packet I traced via Fiddler

Is that the exact content you are POSTing? If so it is not a valid SData payload. Please see my example above for a valid one.

**Comment by davidhendrickmb** [comment]
It looks like the tradingAccount is being set correctly as I have it at the moment. I am directly querying Sage for this and this is a valid customer.

That is what I got from Fiddler, tracing the packet being sent from the .Net plugin. Can you let me know what is wrong with it?

**Comment by darroncockram** [comment]
> That is what I got from Fiddler, tracing the packet being sent from the .Net plugin. Can you let me know what is wrong with it?

It is not valid XML and not a not a valid Sdata payload. A valid payload would look something along the lines of the example I POSTed

**Comment by davidhendrickmb** [comment]
It is what the SData DLL has produced and I ran it through an XML validator which passed. Do you know what would cause the underlying error that I'm seeing as that is the problem?

**Comment by darroncockram** [comment]
What you have posted above is not valid XML - not even close. Is that definitely a capture of the exact body of the request that is being submitted to the Sdata feeds?

**Comment by davidhendrickmb** [comment]
I have substituted some items with # in order to conceal sensitive information, is that what you are referring to? If you can suggest an alternative to Fiddler, I'm happy to capture it there.

**Comment by davidhendrickmb** [comment]
I edited the post almost immediately afterwards as it seemed to be too long to paste...

**Comment by darroncockram** [comment]
The snippet in PasteBin that you linked to is valid XML and works perfectly fin for me (when I replace the UUIDs of the tradingAccount and commodity with valid values in my dataset)

**Comment by davidhendrickmb** [comment]
Ok, well that's good. Why would I be getting the error so?

**Comment by darroncockram** [comment]
I can't see anything obvious. What version of Accounts are you using?

**Comment by davidhendrickmb** [comment]
Sage 50 Accounts Professional 2014

**Comment by darroncockram** [comment]
Ah, that will be the problem then. There was a bug fix to address an incorrect mapping for sales credits applied quite a while back but this was only included in the 2015 release and later. A patch was never released for 2014.

That means the only option would be to upgrade to a later version of Accounts if you need to create sales credits. Newer versions of the Sdata adpater are backwards compatible, so you could use the newer version to connect to a 2014 dataset but the only way to get the new version of the Sdata adapter would be to install a newer version of Accounts I'm afraid.

**Comment by davidhendrickmb** [comment]
OK, at least I know now. Thanks for all of your help, much appreciated!
