### ISSUE TITLE
sage sdata url with UUID not working #118

### ISSUE THREAD

**Issue by oknaru** [Sage/SData-2.0#126]
HI
In-reference to the below issue, Can we re-open 
sage sdata url with UUID not working #118

I have got sage 23 with all the updates and service pack for two companies. Initially had problem with URL which generated wron -1 at the end but now it different UUID,

So when i type the url in browser http://myPC:5493/sdata/accounts50/GCRM/-/tradingaccounts" it opens the first company data but if it type http://myPC:5493/sdata/accounts50/GCRM/{C4C463BE-B098-4A7D-A23B-D1A92B8DCB59}/tradingaccounts it just ask for username and password then it does not got any further.
No errors are thrown either.

Any suggestion or advise?

Best regards
Hemal

**Comment by asterix187** [comment]
Can you try restarting the sdata service and then just connecting to dataset 2. There had been a long running issue with sdata where it holds open the first dataset regardless of the query specifying another dataset.


________________________________

**Comment by darroncockram** [comment]
A -1 at the end of a dataset identifier is not necessarily incorrect. It happens if you expose the same dataset twice e.g. backup and restore to a different company on the same machine.

A few things to check:

Is {C4C463BE-B098-4A7D-A23B-D1A92B8DCB59} a valid identifier for dataset on that machine?
If you query the Sdata registry does it show in the results?
http://myPC:5493/sdata/$system/registry/*/endpoints?where=endPointType%20eq%20%27dataSet%27
Can you open the dataset using the main Sage 50 Accounts application?
Is the version of the data in the default dataset different from the one in the {C4C463BE-B098-4A7D-A23B-D1A92B8DCB59}  dataset?
Is the data for both datasets hosted on the 'myPC' machine?


> There had been a long running issue with sdata where it holds open the first dataset regardless of the query specifying another dataset.

I've not come across this problem before. Do we have some steps to recreate the issue?

**Comment by darroncockram** [comment]
If an error is encountered by the Sdata service there should be a message in the Windows event log that should hopefully shed some light on the issue.

**Comment by oknaru** [comment]
Thanks, I checked the log it looks like the SSMS memory issue for GET request on URI
Exception of type 'System.OutOfMemoryException' was thrown.

**Comment by darroncockram** [comment]
Neither Accounts or the Sdata adapter use SSMS so that error will be unrelated. Are there no other errors in the event log?

**Comment by asterix187** [comment]
Does it still do the same when you ad &count=1 to the end?

**Comment by darroncockram** [comment]
Do other endpoints on the same dataset work e.g. tasCodes?

**Comment by oknaru** [comment]
taxCodes and &Count=1 is working, Can you please guide where I can find more DataSets type

**Comment by asterix187** [comment]
Do you mean datasets or endpoints? 

if you do the URL /-/$schema it will list all the data schema available.

**Comment by darroncockram** [comment]
If the taxCodes endpoint is working then it would suggest there is a problem with the tradingAccounts data. It would be worth running a check data in Accounts.

**Comment by darroncockram** [comment]
Also would be worth creating a new dataset and confirming if the tradingAccounts endpoint works for that.

**Comment by oknaru** [comment]
Thank you for your time and suggestions, Not sure I have to restart service sometime as sData stop loading
and SData GET returning lots of unwanted HTML in addition to the desired XML

**Comment by darroncockram** [comment]
I've not seen any problems with the Sdata service not loading before. Is this something that you can replicate on demand?

In terms of the unwanted HTML there is an undocumented parameter you can use in your sdata URL to exclude this called IncludeContent e.g.

http://localhost:5493/sdata/accounts50/GCRM/tradingaccounts?count=10&IncludeContent=false

Note that the IncludeContent parameter, to my knowledge, is only supported by the Sage 50 Accounts Sdata adataper.

**Comment by darroncockram** [comment]
Closed due to inactivity
