### ISSUE TITLE
Sage 50 v25 sData changes

### ISSUE THREAD

**Issue by asterix187** [Sage/SData-2.0#128]
Hi, is there any documentation on the changes to the sData provider for Sage 50 UK v25 (2019)?

The default port has been changed (for 5493 to 5495) and the DLL versions are now 2.0.0.0 rather than 1.0.0.0 but there are no discernible changes to the output?

**Comment by darroncockram** [comment]
Unfortunately there is no documentation around the changes but the only change I'm aware of is an update to target v4 of the the .NET framework. Long overdue in my opinion.

**Comment by asterix187** [comment]
They have definitely changed the default port and the DLL version numbers. Obviously if these are referenced they will need to be changed. Even the service name has been changed yet no one seems to know anything about it and everyone says its supported. Bit frustrated as we pay Sage many £1k's for developer access to develop into Sage 50 and no one even knows why the name has been changed and won't answer any questions as 'sData is not supported'. Someone somewhere must have done the changes for some specific reason but there is no visible evidence as to why?

<img width="349" alt="file properties" src="https://user-images.githubusercontent.com/7346013/48640728-69f58400-e9cf-11e8-814e-1490458c057e.png">
<img width="449" alt="help guide port" src="https://user-images.githubusercontent.com/7346013/48640729-69f58400-e9cf-11e8-8845-dbe9871da3d4.png">
<img width="616" alt="service name" src="https://user-images.githubusercontent.com/7346013/48640730-69f58400-e9cf-11e8-9665-f8c890ff33f3.png">

**Comment by darroncockram** [comment]
As I say the reason for the change is to re-target to v4 of the .NET framework. The reason for the new service name and port number is to support side-by-side installation and ensure existing integrations are not broken.

I share your frustration around the lack of comms. It's not a change even I was aware of either until you mentioned it.

**Comment by asterix187** [comment]
So does that mean we can run the old sData provider against the new v25 Sage 50? If not then it will break all integration anyway as everything for everyone will need to be redone for sData 2 provider.

It just seems crazy that a service that snot supported has been updated and changed with no notice or info coming out seemingly for no apparent reason just to target a new .net version that wasn't causing any issues anyway.
