### ISSUE TITLE
Unable to locate the specified Assembly 'Sage.Integration.Accounts50.SDO.Adapter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=23836914f481b21e'

### ISSUE THREAD

**Issue by ramblex** [Sage/SData-2.0#129]
Just upgraded to Sage Accounts50 25.0.76.0 and am getting the following response when trying to use SData:

```
<?xml version="1.0" encoding="utf-8"?>
<diagnosis xmlns="http://schemas.sage.com/sdata/2008/1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:sdatasync="http://schemas.sage.com/sdata/sync/2008/1" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:sme="http://schemas.sage.com/sdata/sme/2007" xmlns:http="http://schemas.sage.com/sdata/http/2008/1">
  <sdata:severity>fatal</sdata:severity>
  <sdata:sdataCode>ApplicationDiagnosis</sdata:sdataCode>
  <sdata:applicationCode />
  <sdata:message>Exception caught during adapter load Sage.Integration.Accounts50.SDO.Adapter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=23836914f481b21e Sage.Integration.Accounts50.SDOAdapter.SDOAdapter from C:\Windows\assembly\GAC_MSIL\Sage.Integration.Accounts50.SDO.Adapter\1.0.0.0__23836914f481b21e\Sage.Integration.Accounts50.SDO.Adapter.dll: Unable to locate the specified Assembly 'Sage.Integration.Accounts50.SDO.Adapter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=23836914f481b21e'</sdata:message>
  <sdata:stackTrace />
  <sdata:payloadPath />
</diagnosis>
```

In #115 (an issue I previously opened) I used gacutil to install the missing DLLs but now they seem to be missing from the filesystem i.e. there's no `Sage.Integration.Accounts50.SDO.Adapter.dll` in `C:\Program Files (x86)\Sage\SData\Assemblies` (although there are version 2.0.0.0 DLLs in SData 2.0). Should the DLL files still exist in the SData directory?

**Comment by asterix187** [comment]
Sage have changed the dll version to 2.0.0.0 so you will need to rebuild against the v25 dll’s.

________________________________

**Comment by ramblex** [comment]
Is that just a case of using gacutil to install the DLLs from the SData 2.0 directory?

**Comment by asterix187** [comment]
It depends on how you are using them. If it’s via a VS project it will not run if you reference the v1 dll’s.

________________________________

**Comment by ramblex** [comment]
It's via the SData windows service which was installed as part of the Sage Accounts 50 client.

**Comment by ramblex** [comment]
We've worked around the problem by using the SData 2.0 service (instead of the original SData service) which runs on port 5495 but still supports the GCRM contract.

**Comment by AlfredGreene** [comment]
Ramblex any chance you can share the updated url you are using now we are heaving issues with the v25 update having stopped our own sData interface working.
Many thanks in advance.

**Comment by ramblex** [comment]
Hi @AlfredGreene Previously we were using the SData service on`http://<host ip>:5493` and now we're using the SData 2.0 service on `http://<host ip>:5495`.

**Comment by AlfredGreene** [comment]
Everything else still the same just the port updated then?
thought had a few hours of re-coding ahead of me lol.
Many thanks.

**Comment by ramblex** [comment]
Yep, I was contemplating the same thing... took me a few hours just to find that though :) Hope it works for you.

**Comment by AlfredGreene** [comment]
will let you know many thanks so wish Sage would put together some good documentation for sData.
