### ISSUE TITLE
Contact Name Cannot Be Updated

### ISSUE THREAD

**Issue by geoffo** [Sage/SData-2.0#13]
It appears that the contact name cannot be updated using SData.

I have tried using both FullName and a combination of FirstName, LastName, etc.

Here is the original name created using the SData API (which works fine):

```
  <crm:fullName>Dr. DELETE ME NOW Jr.</crm:fullName>
  <crm:salutation xsi:nil="true" />
  <crm:firstName>DELETE</crm:firstName>
  <crm:preferredName xsi:nil="true" />
  <crm:familyName>NOW</crm:familyName>
  <crm:title>Dr.</crm:title>
  <crm:middleName>ME</crm:middleName>
  <crm:suffix>Jr.</crm:suffix>
```

Here is my PUT request data using FirstName, MiddleName, and LastName:

```
<entry xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:crm="http://schemas.sage.com/crmErp/2008" xmlns:sc="http://schemas.sage.com/sc/2009" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3.org/2005/Atom">
  <sdata:payload>
    <crm:contact>
      <crm:firstName>Testing</crm:firstName>
      <crm:middleName>An</crm:middleName>
      <crm:familyName>UpdatedName</crm:familyName>
    </crm:contact>
  </sdata:payload>
</entry>
```

Here is my PUT request using FullName:

```
<entry xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:crm="http://schemas.sage.com/crmErp/2008" xmlns:sc="http://schemas.sage.com/sc/2009" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3.org/2005/Atom">
  <sdata:payload>
    <crm:contact>
      <crm:fullName>Dr. This IsA Test Sr.</crm:fullName>
    </crm:contact>
  </sdata:payload>
</entry>
```

After both of the above PUT attempts, the contact name remains the same as before:

```
  <crm:fullName>Dr. DELETE ME NOW Jr.</crm:fullName>
  <crm:salutation xsi:nil="true" />
  <crm:firstName>DELETE</crm:firstName>
  <crm:preferredName xsi:nil="true" />
  <crm:familyName>NOW</crm:familyName>
  <crm:title>Dr.</crm:title>
  <crm:middleName>ME</crm:middleName>
  <crm:suffix>Jr.</crm:suffix>
```

This appears to be a bug in SData as the contact name can be changed in the Sage 50 Software itself.

**Comment by darroncockram** [comment]
That's working OK for me. It would be the fullName property that you'd need to set. What UURL are you sending your PUT request to?

**Comment by geoffo** [comment]
Both of my update attempts were sent using the following URL:

PUT http://localhost:5493/sdata/accounts50/GCRM/-/contacts('a3f6ff1b-a80b-4019-ae5e-b1fa1bb4044d')

**Comment by darroncockram** [comment]
That looks OK provided that a3f6ff1b-a80b-4019-ae5e-b1fa1bb4044d is the correct UUID for the contact you are trying to update. That definitely works for me.

**Comment by geoffo** [comment]
I was able to get it working using the $url field that is returned in the GET response for the contact.  It is still not working though when just using the contacts URL (as show in my previous comment).  

Here is the URL that I was able to use:

PUT http://localhost:5493/sdata/accounts50/GCRM/-/contactCustomerDel('a3f6ff1b-a80b-4019-ae5e-b1fa1bb4044d') 

I can use the above but there still seems to be an issue when using the other contacts URL.

**Comment by darroncockram** [comment]
I did wonder if the problem might have been related to the sub resource Url as per your other issue but I  tried it with both the contactCustomerDel and contacts endpoints and it works both ways for me. I'm struggling to come up with a reason why it works for me but doesn't work for you.
