### ISSUE TITLE
sdata Sage 50 UK - Invoice with payment

### ISSUE THREAD

**Issue by jwilliamson1098** [Sage/SData-2.0#130]
Hi

I'm trying to create an invoice with a payment attached. The invoice raises through fine, but no sign of the payment.

Below is a code snippit of what I added to the standard invoice code. UUIDs for tradingaccount and bank are found elsewhere in the code (and checked to be correct).

            receiptFeedEntry pay = new receiptFeedEntry();
            bankAccountCustomerFeedEntry bank = new bankAccountCustomerFeedEntry();

            bank.UUID = bankuuid;
            pay.tradingAccount = account;
            pay.type = "SA";
            pay.reference = reference;
            pay.reference2 = payref;
            pay.date = DateTime.Today;
            pay.currency = "GBP";
            pay.grossTotal = -1*(decimal)payment;
            Console.WriteLine("Adding payment line of {0}\n", payment);
            pay.bankAccount = bank;
            invoice.receipts.Entries.Add(pay);

Any help much appreciated.

**Comment by darroncockram** [comment]
Unfortunately the Accounts 50 adapter does not currently support the ability to add a receipt to an invoice (the receipts property is flagged as Unsupported="true" in the schema).

**Comment by jwilliamson1098** [comment]
That's a shame. Thanks for the quick answer. Really limits what can be done with sdata.
