### ISSUE TITLE
Unable to locate the specified object 'accounts50/GCRM/-' When Connecting to SDATA URL

### ISSUE THREAD

**Issue by joebi3** [Sage/SData-2.0#132]
Hi, 
When I try to connect to the sdata url generated by sage in the Internet Options > Details Window for Sage 50 Accounts I get the following XML error

`<diagnosis xmlns="http://schemas.sage.com/sdata/2008/1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:sme="http://schemas.sage.com/sdata/sme/2007" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:http="http://schemas.sage.com/sdata/http/2008/1" xmlns:sdatasync="http://schemas.sage.com/sdata/sync/2008/1">
<sdata:severity>error</sdata:severity>
<sdata:sdataCode>ResourceKindNotFound</sdata:sdataCode>
<sdata:applicationCode/>
<sdata:message>
Unable to locate the specified object 'accounts50/GCRM/-'
</sdata:message>
<sdata:stackTrace/>
<sdata:payloadPath/>
</diagnosis>`

The URL being shown in the client window is:
Sage 50 Accounts supports GCRM integration.
[REDACTED]:
http://sage-server:5495/sdata/accounts50/GCRM/{0020404B-E2C9-41EB-9092-35BB175BF292}

Current Sage 50 Version: 25.1.128.0
Clean install on a brand new windows 2012 server (due to hardware issues on the previous server). 
We have never tried to connect via SData before. 

Any suggestions?

**Comment by asterix187** [comment]
If you add /$schema to the end does anything get shown?

________________________________

**Comment by joebi3** [comment]
Yeah, I get what looks to be the XML schema for our data, after being prompted for my sage credentials. 
I can paste it here if needed?

**Comment by asterix187** [comment]
﻿Hi, ok try /tradingaccounts?count=1 at the end instead. Does it return as customer record?

Qmulus Solutions | The UK&I No.1 Sage CRM Business Partner
Sage CRM Partner of the Year 2014 | 2015 | 2016 | 2017 | 2018

Telephone: + 44 (0)845 450 3991
Web: www.qmulus-solutions.com<http://www.qmulus-solutions.com/>

**Comment by joebi3** [comment]
It returns an XML doc that says it's from my company data, but there are 0 records:

`<?xml version="1.0" encoding="utf-8"?>
<feed xmlns:atom="http://www.w3.org/2005/Atom" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cf="http://www.microsoft.com/schemas/rss/core/2005" xmlns="http://www.w3.org/2005/Atom" xmlns:crm="http://schemas.sage.com/crmErp/2008" xmlns:sc="http://schemas.sage.com/sc/2009" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:sme="http://schemas.sage.com/sdata/sme/2007" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:http="http://schemas.sage.com/sdata/http/2008/1" xmlns:sdatasync="http://schemas.sage.com/sdata/sync/2008/1">
  <author />
  <category term="tradingAccount" />
  <generator />
  <subtitle>Provides a feed containing tradingAccount details</subtitle>
  <title>Sage Accounts 50 | tradingAccount - [COMPANY NAME REDACTED]                                 </title>
  <opensearch:totalResults>0</opensearch:totalResults>
  <opensearch:startIndex>1</opensearch:startIndex>
  <opensearch:itemsPerPage>10</opensearch:itemsPerPage>
</feed>`

Thanks,

**Comment by darroncockram** [comment]
The 404 error from the original endpoint you posted would be expected as you have not requested a valid resource kind. With the /tradingAccounts endpoint returning 0 records this may also be correct, do you have any customers or suppliers in the dataset you are connecting to? If you try the /taxCodes endpoint this should return data regardless even if you are connecting to an empty dataset.

Hope that helps.
