### ISSUE TITLE
Access SData Url via Internet

### ISSUE THREAD

**Issue by mbharanidharan88** [Sage/SData-2.0#134]
Is there a way to access the SData URL through the Internet?

[http://localhost:5495/sdata/accounts50/GCRM/-/](http://localhost:5495/sdata/accounts50/GCRM/-/)

**Comment by mbharanidharan88** [comment]
Is there a way to access the SData URL through the Internet?

[http://localhost:5495/sdata/accounts50/GCRM/-/](http://localhost:5495/sdata/accounts50/GCRM/-/)

**Comment by asterix187** [comment]
Yes, if you set up a firewall rule on your firewall to allow port forwarding from the external IP address to the internal IP address of a Sage 50 client on port 5495 it will be accessible.
For example, if your external ip address is 50.60.70.80  and your Sage 50 client internal IP address id 192.168.0.30:

Create a rule on your network firewall forwarding 5945 from 50.60.70.80 to 192.168.0.30. 

You should then be able to access Sage 50 Sdata via http://50.60.70.80:5495/sdata/accounts/GCRM/-/

**Comment by darroncockram** [comment]
If you are planning on exposing the Sdata feeds to the Internet then I would strongly recommend using HTTPS rather than HTTP.
