### ISSUE TITLE
update tradingAccount Name

### ISSUE THREAD

**Issue by mbharanidharan88** [Sage/SData-2.0#135]
I am trying to use the below code to update the **tradingAccount** with a new account name but it is running up with an error 

> PUT operation failed - A collection predicate must be specified
 >  at Sage.Integration.Accounts50.SDOAdapter.CompositeRequestHandler.OnPutRequest(IRequest request, FeedEntry feedEntry)
   at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.OnPutRequest(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.PutRequest(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.PutRequest(IRequest request) (-1)

**Code:**

```
    var uuid = "Guid to search"
    var uri = new SDataUri("SDATA_URL");

    uri.Where = string.Format("UUID eq '{0}'", uuid);

    var request = new SDataRequest(uri.Uri);

    request.Username = "Manager";
    request.Password = "";

    tradingAccountFeed feed = new tradingAccountFeed();
    request.RequestFeed<tradingAccountFeedEntry>(feed);

    if (request.IsStatusValidForVerb && feed.Entries != null && feed.Entries.Count > 0)
    {
        var account = feed.Entries[0];
        account.name = "New Name";
        var updateRequest = new SDataRequest(uri.Uri, account, Sage.Integration.Messaging.Model.RequestVerb.PUT);

        updateRequest.Username = "Manager";
        updateRequest.Password = "";
        updateRequest.Send();

```

Any ideas please?

**Comment by darroncockram** [comment]
As the error message notes you need to supply a collection predicate that identifies the resource to be updated. You can't use a a where clause on a PUT as implies batch update which is not supported in the Sdata protocol.

So basically remove this line:

`uri.Where = string.Format("UUID eq '{0}'", uuid);`

And replace it with this:

`uri.CollectionPredicate = uuid.ToString();`
