### ISSUE TITLE
Sales Invoice Payment Due Date Not updating

### ISSUE THREAD

**Issue by mbharanidharan88** [Sage/SData-2.0#137]
Hi,

I am trying to create a sales invoice and trying to update the invoice date and the payment due date but it not updating.

```
    var salesInvoice = new salesInvoiceFeedEntry
    {
          tradingAccount = account,
          salesInvoice.date = DateTime.Now.AddDays(3);
          salesInvoice.paymentDue = DateTime.Now.AddDays(14);
    };
```

But the strange part is when I use the below property it is updating the invoice date but still not the payment due date.

`salesInvoice.taxDate = DateTime.Now.AddDays(3);`

Payment Due date is always empty.

**Comment by darroncockram** [comment]
I'm a little confused. The salesInvoice type doesn't have an attribute called paymentDue. It has a paymentDueDays which is an integer and dueDate which is a DateTime but has no setter (it is a calculated field adding the paymentDueDays to the date).

**Comment by darroncockram** [comment]
The paymentDue attribute relates to a calculated field and does not have a setter. This means it really should have been flagged with the sme:IsReadOnly attribute in the schema (I'll raise that as a bug). The calculation of paymentDue is based on the date and paymentDueDays properties so they are the ones you'll need to set to get the calculation to do it's work.

Hope that helps.

**Comment by mbharanidharan88** [comment]
Got it Thank you!

**Comment by mbharanidharan88** [comment]
> The paymentDue attribute relates to a calculated field and does not have a setter. This means it really should have been flagged with the sme:IsReadOnly attribute in the schema (I'll raise that as a bug). The calculation of paymentDue is based on the date and paymentDueDays properties so they are the ones you'll need to set to get the calculation to do it's work.
> 
> Hope that helps.

I could not see any property names paymentDueDays. Is there anything else that I need to set it up?

**Comment by darroncockram** [comment]
Sorry it looks like that is an internal only field for some reason. I have no idea why this might be the case but I'll see if I can find out any reason for it.

**Comment by darroncockram** [comment]
So the reason behind it is that the GCRM contract  does not have any concept of due dates. The dueDate and internal paymentDueDays properties were added as extension properties to support retrieval of due dates for existing invoices and were always intended to be read only.

This means that it is just the IsReadOnly metadata in the schema that is missing and it's not possible to set the due details on an invoice via the Sdata feeds I'm afraid.

**Comment by mbharanidharan88** [comment]
Perfect Thank you...
