### ISSUE TITLE
Referencing Issue with Sage.Common.LinqBridge

### ISSUE THREAD

**Issue by mbharanidharan88** [Sage/SData-2.0#139]
I have referred the dll **Sage.Common.LinqBridge** in .NET Framework 4.5 Project and getting the below issue as the dll has a **System.Linq** namespace in it. Any Work around for this?

> CS0121: The call is ambiguous between the following methods or properties: 'System.Linq.Enumerable.FirstOrDefault<TSource>(System.Collections.Generic.IEnumerable<TSource>)' and 'System.Linq.Enumerable.FirstOrDefault<TSource>(System.Collections.Generic.IEnumerable<TSource>)'

**Comment by darroncockram** [comment]
Is the file not installed in the GAC?

**Comment by darroncockram** [comment]
Easiest way would be to use an alias:
https://docs.microsoft.com/en-gb/dotnet/csharp/language-reference/operators/namespace-alias-qualifier

**Comment by mbharanidharan88** [comment]
Thank you for this!

However, I cannot use an alias in the situation since the ambiguous reference is between **Sage.Common.LinqBridge** and **System.Linq**.

And **Sage.Common.LinqBridge** is used by **Sage.Common.Syndication** where I don't have any control to change and the other way adding alias to **System.Core** and  **System.Linq** is not that easy and not suggestable as well since **Linq** will be used everywhere.

The solution I came up with is adding the assembly binding,

1. Remove the reference of **Sage.Common.LinqBridge**  from any projects.
2. Copy the dll **Sage.Common.LinqBridge** to somewhere in the project.
3. Add the dependentAssembly binding by providing the above path as codeBase.

 ```
<dependentAssembly>
        <assemblyIdentity name="Sage.Common.LinqBridge" publicKeyToken="c59b718b5ca510a8" culture="neutral"/>
        <bindingRedirect oldVersion="1.0.0.0" newVersion="1.0.0.0"/>
        <codeBase version="1.0.0.0" href="MyDlls/Sage.Common.LinqBridge.dll"/>
      </dependentAssembly>
```

**Note:**  **publicKeyToken="c59b718b5ca510a8"** is important here as with this token only the project will resolve the dll.

your comments on this, please?

**Comment by darroncockram** [comment]
Sorry when I said an alias I meant to replace the global alias on your reference e.g.

```
<ItemGroup>
    <Reference Include="Sage.Common.LinqBridge">
      <HintPath>C:\Program Files (x86)\Sage\Assemblies\SData\Sage.Common.LinqBridge.dll</HintPath>
      <Aliases>sdata</Aliases>
    </Reference>
  </ItemGroup>
```

You can set this via the properties of the reference in Visual Studio if you don't want to hand edit your project file.

I should also point out that the Sage.Common.LinqBridge.dll assembly was removed in the last release of Accounts. I don't think that an updated build of the SIF has been sync'd to the GitHub repo yet so I'll chase this up. It only existed to provide Linq style support back when the SIF was still based on .NET 2. Now that it targets .NET 4.5 all the Linq goodness is baked in and readily available so it's no longer necessary.

**Comment by mbharanidharan88** [comment]
Ya, Thank you for this! However, this still copies the **Sage.Common.LinqBridge** to the bin folder which breaks into ambiguous reference again.

And that is great when the dependency of the **Sage.Common.LinqBridge** is removed.

**Comment by darroncockram** [comment]
You don't need to copy the assembly to the bin folder as it is installed in the GAC so will be loaded from there even if it exists in the bin folder too.

After renaming the global alias everything should work fine regardless of where the assembly is installed. I've run some quick tests and it works no problems for me. After setting the alias as I described did you also remove the assembly binding from your config as this may have been your issue.

**Comment by mbharanidharan88** [comment]
Thanks! I cannot rely on GAC as I've created the API which talks through SDATA Url and the api is hosted in the Azure. 

And I cannot copy the **Sage.Common.LinqBridge** to the bin folder to avoid the ambiguous reference. If I add alias reference and point to the location of the dll (inside package folder. I cannot use system path here as it is hosted as API in Azure) somehow it is copying the dll to the bin folder and it doesn't works.

The only solution in my case is I need to delete the **Sage.Common.LinqBridge** manually in the build scripts and in the Delete Task in the CICD build pipelines. With this, it works fine.

**Comment by darroncockram** [comment]
The ambiguous reference error is a build time error so I'm not sure how you could be getting an issue at run time with it being in the bin folder. I can replicate the build error but the alias fix resolves that. I can't replicate any run time error at at all I'm afraid.

**Comment by mbharanidharan88** [comment]
During run time if it tries to use to any methods from **System.Linq** then you may get the error I believe.

**Comment by darroncockram** [comment]
That works no problems for me too.
