### ISSUE TITLE
salesOrders - unable to return sales order detail 

### ISSUE THREAD

**Issue by eurekaindustries** [Sage/SData-2.0#140]
Hiya,

If I do the follow the following request I get an error saying it unable to find the sales order

Command
http://localhost:5495/sdata/accounts50/GCRM/tradingaccount/salesOrders(1)?format=json

error
```
<diagnosis xmlns="http://schemas.sage.com/sdata/2008/1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:sme="http://schemas.sage.com/sdata/sme/2007" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:http="http://schemas.sage.com/sdata/http/2008/1" xmlns:sdatasync="http://schemas.sage.com/sdata/sync/2008/1">
<sdata:severity>error</sdata:severity>
<sdata:sdataCode>ApplicationDiagnosis</sdata:sdataCode>
<sdata:applicationCode/>
<sdata:message>Unable to locate the specified object '1'</sdata:message>
<sdata:stackTrace/>
<sdata:payloadPath/>
</diagnosis>
```

But if i request a list of the sales orders it returns as expected and I can see the basic information of sales order I was requesting before.

Thanks for help

Libbie

**Comment by eurekaindustries** [comment]
Not sure if anyone is actively looking at this any more as it been a while since anything has been closed, but figured out I have to use the uuid now instead of salesorder number.

However include=orderlines doesn't seem to work?

Thanks

Libbie

**Comment by asterix187** [comment]
Try /salesorders?where=reference eq ‘1’

________________________________

**Comment by eurekaindustries** [comment]
Thanks that makes it easier than having to find out uuid first :)

Do you have any ideal why the include orderlines doesn't seem to be working for me?

**Comment by asterix187** [comment]
It’s includes not include

________________________________

**Comment by asterix187** [comment]
So includes=salesorderlines

________________________________

**Comment by eurekaindustries** [comment]
Awesome thanks :)

**Comment by eurekaindustries** [comment]
Hiya, sorry one more quick question (hopefully), the order lines don't seem to include to the product code or any reference to a product code just the text?

Thanks

**Comment by asterix187** [comment]
Have you checked the schema for the salesorderlines? I am not sure if they are available via sdata. /salesorderlines/$schema

________________________________

**Comment by eurekaindustries** [comment]
Hiya,

Yeah I've found it now is listed as "Commodities" it doesn't show as just the code but gives the full URL, I can work with that :)

It doesn't look like it is available in JSON which is a shame as the rest of the data sources i'm using on in JSON.

But hay ho, I'll get there

**Comment by eurekaindustries** [comment]
In case any one else needs this I've managed to get the details I required with the following

http://serveraddress:5495/sdata/accounts50/GCRM/dataset/salesOrders?format=json&where=reference%20eq%202&include=commodity&include=SalesOrderLines

This gives you the sales order details along with product code and information

**Comment by asterix187** [comment]
You should also be able to do something like /salesorders(‘2’)?include=salesorderlines,salesorderlines/commodities

________________________________
