### ISSUE TITLE
SalesInvoices : For larger text than 60 characters, API converts text to an empty string.

### ISSUE THREAD

**Issue by testaccount71** [Sage/SData-2.0#141]
I am attempting to insert records on SalesInvoices  table, 
and for `<crm:salesInvoiceLine>`  `<crm:text>` I am specifying : 
`<crm:salesInvoiceLine>`
          `<crm:text>` Artificial Intelligence  is intelligence demonstrated by machines. `</crm:text>`
API converts this text value (which is more than 60 characters ) to an empty string.

For values that are less than 60 characters (like the example below) insert works fine and the value does not change.
`<crm:salesInvoiceLine>`
          `<crm:text>` AI  is intelligence demonstrated by machines. `</crm:text>`

Can you please have a look at this? 
Attached you can find full postdata.
[postdata.txt](https://github.com/Sage/SData-2.0/files/3835919/postdata.txt)

**Comment by asterix187** [comment]
Hi, can you confirm which Sage accounts system you are attempting to post into?

**Comment by testaccount71** [comment]
Hello, 
I am working with Sage50UK.

**Comment by asterix187** [comment]
Ahh ok. You will need to trim the field to 60 to be able to post for Sage 50 UK. The sData provision does not do this for you. It would be worth checking the version of Sage 50 as well as the sData API changes randomly with no documentation to let you know what has been changed.

**Comment by testaccount71** [comment]
Thank you asterix187  for your information.
