### ISSUE TITLE
Get customer PriceList commodities

### ISSUE THREAD

**Issue by susaree** [Sage/SData-2.0#142]
is this possible? if so, please can you give me an example URL?

Love you,

Ma

**Comment by darroncockram** [comment]
You don't mention which product this is for but I'll assume Sage 50 Accounts UK as this is the most commonly referenced product on these forums. I'm also not 100% clear on what you are after but you can get customer price lists with something like the following

http://localhost:5495/sdata/accounts50/GCRM/-/pricelists?where=reference%20eq%20'P'

If you are after the specific commodities on a given price list then I'm afraid you can't do that through the Sdata feeds as the commodities property is flagged as Unsupported=true

**Comment by susaree** [comment]
I actually found a way! Its /prices
Uri= where ref eq 'customerId'

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by susaree** [comment]
Thank you for your reply!
________________________________

**Comment by susaree** [comment]
[Image]
PriceList where app id eq 01 shows all customer01 pricelist items


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by darroncockram** [comment]
Ah, right so you want all price lists that are specific to a given customer? The request you suggest should do that.
