### ISSUE TITLE
Pricelist commodity entry

### ISSUE THREAD

**Issue by susaree** [Sage/SData-2.0#144]
I can edit a pricelist commodity price for unique customers, but I cannot add a new commodity.

If someone has figured out how to do it I will greatly appreciate it if you can share your insight.

Thank you,

Mo

**Comment by darroncockram** [comment]
You don't say which product this is for but assuming Sage 50 Accounts UK then have a look at the sample here https://github.com/darroncockram/sdatasamples/tree/master/CreateCommodity

Hope that helps

**Comment by susaree** [comment]
Hi, yes sorry, it is for Sage 50, I used that method as a guide but I still get  "POST operation failed - Exception has been thrown by the target of an invocation.
When I try to post an XML file with postman, it says something similar
I can't figure out what I'm missing.

  priceFeedEntry entry = new priceFeedEntry();



            entry.tradingAccounts = GetCustomer(compId, companyCount);

            if (entry.tradingAccounts == null)
            {
                // No customer record means we can go no further
                Console.WriteLine("Unable to find a customer record");
                Console.ReadKey(true);
                Console.ReadLine();
                return;
            }





            // Lookup a commodity to use on the new sales invoice
            entry.commodity = GetCommodity(orderList[0].Id, productCount);
            if (entry.commodity == null)
            {
                // No commodity record means we go no further
                Console.WriteLine("Unable to find a commodity record");
                Console.ReadKey(true);
                Console.ReadLine();
                return;
            }


            entry.price = Convert.ToDecimal("20.32");



            string url = dataSourceTest + "prices";
            SDataUri priceUri = new SDataUri(url);

            SDataRequest priceRequest = new SDataRequest(priceUri.Uri, entry, Sage.Integration.Messaging.Model.RequestVerb.POST);
            priceRequest.Username = username;
            priceRequest.Password = password;

            // IF successful the POST operation will provide us with a the newly created sales invoice
            priceFeedEntry savedPrice = new priceFeedEntry();
            priceRequest.RequestFeedEntry<priceFeedEntry>(savedPrice);


            if (priceRequest.IsStatusValidForVerb)
            {

                Console.WriteLine(string.Format("Successfully created productlist {0}", savedPrice.reference));
                Console.ReadLine();
            }
            else
            {
                // There was a problem
                Console.WriteLine("Create failed. Response was {0}", priceRequest.HttpStatusCode.ToString());
                if (priceRequest.Diagnoses != null)
                {
                    foreach (Diagnosis diagnosis in priceRequest.Diagnoses)
                        Console.WriteLine(diagnosis.Message);
                    Console.ReadLine();
                }
            }
