### ISSUE TITLE
Accessing Payment Details on salesInvoices

### ISSUE THREAD

**Issue by WAT-LFrost** [Sage/SData-2.0#146]
Hello,
When retrieving details of a salesInvoice via GET, is there a way I can get the values of the fields found in the Payment tab? If there is a way, can I update those fields?

![Payment Tab](https://user-images.githubusercontent.com/42027816/70637477-36ffdd00-1c2f-11ea-9df8-05d56c6eb4c6.png)

**Comment by darroncockram** [comment]
It's a no to both questions I'm afraid.

**Comment by WAT-LFrost** [comment]
Hmm okay, thanks @darroncockram 🙂 

Another quick question if that's okay, I would like to make sure there definitely isn't a way to do this:
Does that then mean we cannot create a Payment and apply it to an invoice? If it turns out we can, how can we do that?

**Comment by darroncockram** [comment]
Unfortunately the Sdata adapter doesn't support creation of transactions at all. The only way to create a transaction would be to use SDO (the application specific SDK for Sage 50 Accounts).
