### ISSUE TITLE
Getting Printed/Posted Status of a Sales Invoice

### ISSUE THREAD

**Issue by coxeh** [Sage/SData-2.0#147]
We are trying to get the printed status of a sales order invoice on the account 50 package using the SData api. It appears that this information is not available on via this api is this correct? Could you confirm if we can get this via other means?

![Screen Shot 2020-01-07 at 14 30 44](https://user-images.githubusercontent.com/1218712/71903106-46eddc80-315b-11ea-9774-ce1034eba70a.png)

**Comment by darroncockram** [comment]
It's not available I'm afraid. The printed status is a concept specific to Sage 50 Accounts UK so not covered by the GCRM contract I'm afraid. The only way to access the printed status information would be to use SDO - the Sage 50 Accounts product-specific SDK.

Hope that helps.

**Comment by coxeh** [comment]
ok thank you for lettign me know. I will look into alternatives
