### ISSUE TITLE
Service Invoice with Free Text of longer text not creating the text,

### ISSUE THREAD

**Issue by mbharanidharan88** [Sage/SData-2.0#148]
Hi,

I am trying to create the Service Invoice with the Free Text Type with salesInvoiceLineFeedEntry. 

The Invoice is created successfully, however, the text is empty in case of the lengthy text.

This works,

**Where does it come from Contrary**

This doesn't

**Where does it come from Contrary to popular belief Lorem Ipsum is not simply random text It has roots in a piece of classical Latin literature from 45 BC**

**Code:**

     var tradingAccount = GetCustomer();

            tradingAccountFeedEntry account = new tradingAccountFeedEntry
            {
                UUID = tradingAccount.UUID
            };

            var salesInvoice = new salesInvoiceFeedEntry
            {
                type = "Service Invoice",
                tradingAccount = account
            };

    taxCodeFeedEntry taxCode = GetTaxCode();

            taxCodeFeedEntry taxReference = new taxCodeFeedEntry
            {
                UUID = taxCode.UUID
            };

            salesInvoice.taxCodes = new taxCodeFeed();
            salesInvoice.taxCodes.Entries.Add(taxReference);

            salesInvoice.carrierTotalPrice = 100;
            salesInvoice.carrierTaxPrice = 20;
            salesInvoice.carrierNetPrice = 80;

            salesInvoice.reference = "469";

            salesInvoice.copyFlag = false;
            salesInvoice.taxDate = DateTime.Now;
            salesInvoice.currency = "EUR";
            salesInvoice.operatingCompanyCurrency = "EUR";
            salesInvoice.lineCount = 1;

            salesInvoice.netTotal = 80;
            salesInvoice.discountTotal = 0;
            salesInvoice.taxTotal = 20;
            salesInvoice.grossTotal = 100;

            var text1 = "Where does it come from Contrary to popular belief Lorem Ipsum is not simply random text It has roots in a piece of classical Latin literature from 45 BC";

            salesInvoiceLineFeedEntry invoiceLine = new salesInvoiceLineFeedEntry
            {
                number = 1,
                reference = "1" ,
                type = "Free Text",
                text = text1,
                quantity = 2,
                netTotal = 50,
                taxTotal = 10,
                grossTotal = 60,
                taxCodes = new taxCodeFeed()
            };

            invoiceLine.taxCodes.Entries.Add(taxReference);

            salesInvoice.salesInvoiceLines = new salesInvoiceLineFeed();
            salesInvoice.salesInvoiceLines.Entries.Add(invoiceLine);

            SDataUri salesInvoiceUri = new SDataUri();

     salesInvoiceUri.BuildLocalPath("Accounts50", "GCRM", "-", "salesInvoices");
            salesInvoiceUri.Port = 5495;
            salesInvoiceUri.Format = MediaType.JSON;

    var invoiceRequest = new SDataRequest(salesInvoiceUri.Uri, salesInvoice, 
    Sage.Integration.Messaging.Model.RequestVerb.POST);

            invoiceRequest.Username = USERNAME;
            invoiceRequest.Password = PASSWORD;

            salesInvoiceFeedEntry savedSalesInvoice = new salesInvoiceFeedEntry();
            invoiceRequest.RequestFeedEntry<salesInvoiceFeedEntry>(savedSalesInvoice);

            if (invoiceRequest.IsStatusValidForVerb)
            {
                Console.WriteLine("Invoice Created Successfully");
            }
            else
            {
                Console.WriteLine("Failed");
            }

**Comment by darroncockram** [comment]
You don't mention which product this is for so I'm assuming it's Sage 50 Accounts UK. If that is the case then maximum length supported for the line item description is 60 characters.

**Comment by mbharanidharan88** [comment]
> You don't mention which product this is for so I'm assuming it's Sage 50 Accounts UK. If that is the case then maximum length supported for the line item description is 60 characters.

Hi,

Yes, It is Sage50 and in the Sage50 software, it allows more than 60 characters Free Text if the type is of Service Invoice but it is not allowing to create the same with the sdata feeds.

Thanks,
Bharani

**Comment by darroncockram** [comment]
The UI does allow more but I meant that the Sage 50 Accounts Sdata adapter only supports 60 character. Sorry if I wasn't clear.

**Comment by mbharanidharan88** [comment]
> The UI does allow more but I meant that the Sage 50 Accounts Sdata adapter only supports 60 character. Sorry if I wasn't clear.

Yes, that was the question I was asking. Thanks.
