### ISSUE TITLE
Service Operations

### ISSUE THREAD

**Issue by eurekaindustries** [Sage/SData-2.0#149]
Hi,

Is there request a sale order to be complete and generate the relevant dispatch and invoice?

also do anyone know where I can find a list of Operations?

Thanks

Libbie

**Comment by darroncockram** [comment]
> Is there request a sale order to be complete and generate the relevant dispatch and invoice?

Afraid not.

also do anyone know where I can find a list of Operations?

Sdata adapters are self-documenting through the $schema endpoint which will provide a list of all supported resource kinds and the operations that are supported. See this page for more details: https://sage.github.io/SData-2.0/pages/core/0401/

Hope that helps.
