### ISSUE TITLE
commodities, not showing Re-order info

### ISSUE THREAD

**Issue by Ajking11** [Sage/SData-2.0#15]
When requesting a feed of commodities, it does not show any re-order levels or qty. Is this not stored with in commodities if not.

where about would it be hiding?

URL: /sdata/accounts50/GCRM/-/commodities?where=supplierReference eq 'disp'&format=json

**Comment by darroncockram** [comment]
The reorder values aren't currently exposed to the Sdata feeds I'm afraid.

**Comment by darroncockram** [comment]
.
