### ISSUE TITLE
Sage Cloud 50 v26 post xml/json

### ISSUE THREAD

**Issue by erimicel** [Sage/SData-2.0#150]
Hi,

Is there any way to post data as json payload to Sage 50 Cloud/Accounts v26 or it is always xml payload? And i suppose there is no changelog for sage data service whithin sage version update that we can see what have been changed?

Thanks

**Comment by darroncockram** [comment]
The Sage 50 Accounts Sdata adaper only implements the 1.0/1.1 Sdata standard so the post request will need to be XML.

The data service is part of Sage 50 Accounts and not related to Sdata. I don't think that there are any release notes produced for it as it's not been made accessible to 3rd parties. If you meant the Sdata service then release notes for that should be produced although I think this was missed the last time a change was made to the service as I only found out about the port number change through this forum.

**Comment by erimicel** [comment]
Thank you Darron, i assume there is no plans to implement 2.0 Sdata with Sage 50 Accounts in the future?

**Comment by darroncockram** [comment]
None that I'm aware of I'm afraid.
