### ISSUE TITLE
Sage50 Accouns Sdata Details not available

### ISSUE THREAD

**Issue by mbharanidharan88** [Sage/SData-2.0#151]
Hi,

I am fetching data through sdata service and when i am trying to get sdata url and cannot see any datasets in Sage50 Accouns Sdata Details.

Even Sage Data Service is not running up and only  Sage Data Service 2.0 is running up. What could be the issue?

Thanks,
Bharani

**Comment by darroncockram** [comment]
If you are running the v2.0 service try this request to see if the Sdata adapter is actually registered:

http://localhost:5495/sdata/$system/registry/*/endpoints?where=endPointType%20eq%20'contract'

You should get 1 item back from that request for the GCRM contract. If you get nothing back then  the adapter is not registered so probably worth running a repair on the Accounts install.

If you do get the GCRM contract returned in the first request  try this one next:

http://localhost:5495/sdata/$system/registry/*/endpoints?where=endPointType%20eq%20'dataSet'

That should return all the available datasets. If you get something back from this then there must be something incorrect with the requests you have been trying previously. If you get nothing back from this request then it means that either you actually have no datasets on the machine, or the datasets are inaccessible to the Sdata service. For the former option launch the main Accounts app and confirm you have at least one dataset that you can connect to (note demo data and practice data are not available to Sdata). For the latter option ensure that the dataset path is valid and can be accessed by the Sdata service. Ideally it should be a path local on the machine and on a fixed drive. If it is a network path then note that mapped drives are not valid paths for Windows services so you need to use a UNC path. Furthermore as the  Sdata service runs as the LocalSystem account it will not be able to access any network resource so you would need to change the user that the service is configured as to run as an account that has access to the UNC path.

Hope that helps.
