### ISSUE TITLE
Unable to locate the specified object 'accounts50'

### ISSUE THREAD

**Issue by priyanshudon** [Sage/SData-2.0#152]
Running into this issue! Would be thankful if someone helps!
Please check the images.

![WhatsApp Image 2020-04-04 at 2 45 39 AM](https://user-images.githubusercontent.com/63307892/78693361-c042ca00-7918-11ea-9522-f2f2d154a1bc.jpeg)
![WhatsApp Image 2020-04-04 at 2 45 40 AM](https://user-images.githubusercontent.com/63307892/78693368-c33dba80-7918-11ea-85c5-cebbabd77986.jpeg)

**Comment by darroncockram** [comment]
http://localhost:5495/sdata/accounts50/a is not a valid endpoint in the Sdata schema so the error response you are getting is expected. You are missing a contract, dataset identifier and resource kind from the URL see this page for documentation on the format of the Sdata URL - https://sage.github.io/SData-2.0/pages/core/0200/.

Try something like this: http://localhost:5495/sdata/accounts50/GCRM/-/$schema

**Comment by Fik-shun** [comment]
m

**Comment by priyanshudon** [comment]
![image](https://user-images.githubusercontent.com/63307892/79994401-8d313680-84d3-11ea-8a92-14f2f7692c8f.png)
Still error!

**Comment by darroncockram** [comment]
That would suggest you have no datasets. You need at least one dataset to be available for that request to work.
