### ISSUE TITLE
GET operation failed - Value cannot be null. 

### ISSUE THREAD

**Issue by priyanshudon** [Sage/SData-2.0#153]
Running into this issue! Please check the images

![image](https://user-images.githubusercontent.com/63307892/80645921-6fdb0a00-8a89-11ea-9021-d0846284c9bb.png)
![image](https://user-images.githubusercontent.com/63307892/80645944-7a959f00-8a89-11ea-8b47-9536c89adbb6.png)

**Comment by priyanshudon** [comment]
@darroncockram

**Comment by darroncockram** [comment]
Do you have any available datasets? You can check this by visiting the URL http://localhost:5495/sdata/$system/registry/*/endpoints?where=endPointType eq 'dataSet'

Note that the case of 'dataSet' is important in that URL - it must be all lowercase except for the 'S'

**Comment by Fik-shun** [comment]
Alright I'll check and reply!

**Comment by priyanshudon** [comment]
![image](https://user-images.githubusercontent.com/63307892/80706374-d7cf3600-8b05-11ea-89e5-9ab5755dc892.png)
No there are no available datasets. @darroncockram

**Comment by darroncockram** [comment]
That's your problem then. You are trying to access the default dataset (that's what the dash represents in your URL) but there are no datasets . You need to create at least one dataset before your URL will work.

**Comment by priyanshudon** [comment]
Hey what exactly do you mean by datasets? Because when i open Sage50 Accounts application, it does show the data! Please Check the image @darroncockram 
![index](https://user-images.githubusercontent.com/63307892/80916504-bcb72d00-8d76-11ea-8721-e2051aa9aa07.png)

**Comment by asterix187** [comment]
Is it showing the demo data etc or a an actual customer dataset. If you go into Sage 50 do any datasets show under the Tools>Internet Options>SDAta Settings>Details screen. If you are using the practice or demo data that comes with Sage 50 to test you MUST add this as an actual company into Sage 50 (by going to add new company and selecting the Use Existing Company data option) and browsing to the DemoData folder location (something like C:\PROGRAMDATA\SAGE\ACCOUNTS\2020\DEMODATA). Whilst the demo data is available to use in the UI it is not available to be used by SData until it has been added as an actual company.

**Comment by darroncockram** [comment]
So whilst I can tell your screenshot  is not showing demo or practice data it's not possible to tell if it is local data or not. What path is your dataset using?

**Comment by priyanshudon** [comment]
Yes, I checked its not demo data. The data is not Local. Check the images! @darroncockram  @asterix187  
![image](https://user-images.githubusercontent.com/63307892/80945418-66df9500-8e09-11ea-8f7a-9c1d53cf4d9c.png)

**Comment by darroncockram** [comment]
The Sdata service will only work with local data by default.

**Comment by asterix187** [comment]
My point still stands. Are any datasets showing up in the Tools>Internet Options>SData Settings>Details section. If not you probably have a permissions errors on the folder. Make sure the SData service is running as a user who has network credentials onto the folder the Sage 50 data is in.

**Comment by darroncockram** [comment]
If possible access the Sdata service running on the same machine as the data. Whilst you can get Sdata to work with remote data it is a lot better from a performance point of view if you can access it locally.

**Comment by priyanshudon** [comment]
Hey! I understand the performance will decrease, I'll try to access SData Service locally if possible. But for now, could you please tell how I may be able to work with the remote data!?

**Comment by darroncockram** [comment]
The user that the Sdata service runs as will need permissions to the location of the network data. By default the Sdata service runs as the LocalSystem account and will not have any network access. You'd need to change the user that the service is configured to run as to be one that does have permissions to the data path and restart the service.
