### ISSUE TITLE
Using Postman to Test POST - Error Request Content Type 'Atom' is not acceptable

### ISSUE THREAD

**Issue by nddsoft** [Sage/SData-2.0#154]
Hi,

I'm doing some tests with SData using Postman and I can use GET to retrieve information and I can use PUT to update items like tradingAccountCustomer and salesInvoices, as per the documentation.  However, if I try to do a POST , I get the following error:
<sdata:message>Request Content Type 'Atom' is not acceptable</sdata:message>

I use (same as PUT operations) Content-Type: application/atom+xml
and Type : entry
if I remove the Content-Type, I get the same error, but instead of Atom it says XML.

The step I followed is simply GET a specific tradingAccountCustomer or salesInvoice.
Change the uuid and change the name/details. 
Then submit a POST and get this, for any kind of POST I do

`<?xml version="1.0" encoding="utf-8"?>
<diagnosis xmlns="http://schemas.sage.com/sdata/2008/1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:sdatasync="http://schemas.sage.com/sdata/sync/2008/1" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:sme="http://schemas.sage.com/sdata/sme/2007" xmlns:http="http://schemas.sage.com/sdata/http/2008/1">
    <sdata:severity>error</sdata:severity>
    <sdata:sdataCode>ApplicationDiagnosis</sdata:sdataCode>
    <sdata:applicationCode />
    <sdata:message>Request Content Type 'Atom' is not acceptable</sdata:message>
    <sdata:stackTrace />
    <sdata:payloadPath />
</diagnosis>`

Example of the beginning of the POST submitted, but it doesn't seem to be getting this far:
`<entry xmlns:sdata="http://schemas.sage.com/sdata/2008/1" 
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:crm="http://schemas.sage.com/crmErp/2008"
       xmlns="http://schemas.sage.com/crmErp/2008"
       xmlns:sc="http://schemas.sage.com/sc/2009">
<sdata:payload>...`

Any thoughts on what I'm missing?  
Thank you.

**Comment by darroncockram** [comment]
The content type should be

`Content-Type: application/atom+xml; type=entry`

See these pages for an example of PUT and POST: https://sage.github.io/SData-2.0/pages/core/0801/
https://sage.github.io/SData-2.0/pages/core/0901/

Hope that helps.

**Comment by nddsoft** [comment]
Oh yes, that helped, such a silly mistake on my part thinking the Content-Type: was only "application/atom+xml", and then a new header entry for Type:Entry... 
Thank you, all is working as expected now.
