### ISSUE TITLE
Sage 50 SData 2.0 Create Sales Order POST using JSON

### ISSUE THREAD

**Issue by mustie** [Sage/SData-2.0#155]
If anyone can help with the following question on stackoverflow, would really appricate it. 

https://stackoverflow.com/questions/62161890/sage-50-sdata-xml-to-json-post-request

**Comment by asterix187** [comment]
Do you have the error response?

________________________________

**Comment by mustie** [comment]
No it just seems to hang and then time out.

**Comment by darroncockram** [comment]
The Accounts adapter does not support JSON format for POST operations. You'll need to use XML I'm afraid.

**Comment by mustie** [comment]
Ah okay, thanks for confirming Darron! Just another question if I may, if I was to back up a sage accounts instance/company and restore it on newer version of sage accounts. Will all the UUID's stay the same?

**Comment by darroncockram** [comment]
Yes, provided the dataset is not been restored to a machine that already has a copy of the data. In that case it will get a '-1' appended to the identifier.
