### ISSUE TITLE
Sage50 InternalServerError

### ISSUE THREAD

**Issue by letoncse** [Sage/SData-2.0#157]
When trying to access the TradingAccounts endpoint, I'm getting "InternalServererror"
I’m having issue to connect sage50 application from my web application. I need to access data from sage50 to web application. The way I have connect before. It’s a c# code

var request = new SDataRequest(uri.Uri);
                request.AllowPromptForCredentials = false;
                request.Username = username;
                request.Password = password;
                request.Send();

after sending request I’m getting request.HttpStatusCode =InternalServerError

uri.Uri= {http://server:5495/sdata/accounts50/GCRM/{D84B9739-3C85-4E59-A483-FB0EC0A3676U}/tradingAccounts}

I have done port forwarding 5495 on the sage50 installed pc. Before its worked fine but suddenly got this issue. 
What could be the reason for InternalServerError ?
Please see the Fiddler view. 
![image](https://user-images.githubusercontent.com/1812631/85143404-9aec0980-b241-11ea-8573-807bfdadb913.png)

Thanks !

**Comment by darroncockram** [comment]
What does the response body show? It should hopefully provide some indication as to the error reason.

**Comment by letoncse** [comment]
I'm getting this message from Fidler response body. I'm getting large amount of data .
![image](https://user-images.githubusercontent.com/1812631/85149935-cc68d300-b249-11ea-822f-39cdba5622b0.png)

![image](https://user-images.githubusercontent.com/1812631/85149679-798f1b80-b249-11ea-96e8-e5bf381e527a.png)

**Comment by darroncockram** [comment]
If there are a lot of trading accounts in your data that certainly could cause an out of memory exception if you try to retrieve them in one go. I would always recommend retrieving data in pages. try restricting how many records are being returned e.g. add ?count=10 to the end of your URL.

**Comment by letoncse** [comment]
Thank you darron, its working from Fidler. Could you help me that how can add query string "?count=10" on c# . Below my code.Thanks!
                var request = new SDataRequest(uri.Uri);
                request.AllowPromptForCredentials = false;
                request.Username = username;
                request.Password = password;                
                request.Send();

**Comment by darroncockram** [comment]
Assuming uri is an SDataUri then simple set the Count property before crating the SDataRequest:

`uri.Count = 10;`

There's a full sample of getting trading accounts in pages here: https://github.com/darroncockram/sdatasamples/blob/master/GetTradingAccountsPaged/Program.cs

Hope that helps

**Comment by letoncse** [comment]
Thank you so much for your kind solution. @darroncockram
