### ISSUE TITLE
How to transfer payment to Sage50 ?

### ISSUE THREAD

**Issue by letoncse** [Sage/SData-2.0#158]
Dear Concern,
I'm trying to transfer payment/recipe  from application to Sage50. How I could achieved that ? I'm using .net technology. could you provide any code sample please? 

I'm able to import Receipt from sage50 to my web application the below way and its working fine. I need vise-versa to transfer sage50. Thanks
`if (filter == null) filter = new BaseSage50Filter();

                var receiptUri = new SDataUri(uri.Uri);
                receiptUri.StartIndex = filter.skip;
                receiptUri.Count = filter.take;
                receiptUri.Format = MediaType.JSON;
                receiptUri.Include = string.Format("{0},{1}", SageCollectionName.TaxCode, SageCollectionName.TradingAccount);
                var request = new SDataRequest(receiptUri.Uri);
                var list = new List<Sage50Receipt>();
                request.Username = Username;
                request.Password = Password;
                request.AllowPromptForCredentials = false;
                receiptFeed receipts = new receiptFeed();
                request.RequestFeed<receiptFeedEntry>(receipts);
                request.Send();
`

**Comment by darroncockram** [comment]
If I've understood the question correcting you are asking how you can create (POST) a receipt to the Sdata feeds in Sage 50 Accounts. Unfortunately this is not possible as the Sage 50 Accounts does not support this. If you issue a schema request you will see that the sme:CanPost, sme:CanPut and sme:CanDelete attributes are all set to false for the receipts resource kind.

**Comment by letoncse** [comment]
> If I've understood the question correcting you are asking how you can create (POST) a receipt to the Sdata feeds in Sage 50 Accounts. Unfortunately this is not possible as the Sage 50 Accounts does not support this.

You are right. Thank you !
