### ISSUE TITLE
504  - Receive Failure error while connect sage50 cloud accounts

### ISSUE THREAD

**Issue by letoncse** [Sage/SData-2.0#159]
After update sage50 to sage50 cloud Account , my system can't communicate with Sage50 cloud account. When trying to login the TradingAccounts endpoint, I'm getting "Login Failed - The operation has timed out".
I’m having issue to connect sage50 cloud application from my web application. I need to access data from sage50 cloud to web application. I'm not facing any issue to connect sage50 with same code but sage50 cloud can't connect . It’s a c# code.

There have any extra configuration on sage50 cloud software?  have any different settings for sage50 and sage50 cloud ? They way I'm trying to connect
                ```
uri.Count = 10;   
                var request = new SDataRequest(uri.Uri);
                request.AllowPromptForCredentials = false;
                request.Username = username;
                request.Password = password;                
                request.Send();
```
![image](https://user-images.githubusercontent.com/1812631/87032146-0dfef500-c1dc-11ea-8ebb-61b6022f434e.png)
Any help you might me provide @darroncockram  Thanks !

**Comment by letoncse** [comment]
Please see the fiddler result. Thanks !

![image](https://user-images.githubusercontent.com/1812631/87032698-eb211080-c1dc-11ea-91e5-362829728cd3.png)

**Comment by darroncockram** [comment]
A logon response and a time out response would be different things. A 408 error would be a timeout response code but it looks like you are getting a 401 which is an unauthorised result. Basically that means that  the username and password are not valid for the data you are trying to connect to.

**Comment by letoncse** [comment]
> A logon response and a time out response would be different things. A 408 error would be a timeout response code but it looks like you are getting a 401 which is an unauthorised result. Basically that means that the username and password are not valid for the data you are trying to connect to.

I can login with same user(Manager) pass in Sage50 could desktop software. There have any extra settings ? Thanks !

**Comment by asterix187** [comment]
Depending on the version you went from and to the port number may have changed from 5493 to 5495

________________________________

**Comment by letoncse** [comment]
> Depending on the version you went from and to the port number may have changed from 5493 to 5495

I'm using 5495 port, like below this is my url and fort forwarding is done for 5495 
http://82.XXX.231.49:5495/sdata/accounts50/GCRM/{A5F26292-B9C6-XXX-XXX-090EA501988C}

**Comment by darroncockram** [comment]
> I can login with same user(Manager) pass in Sage50 could desktop software. There have any extra settings ? Thanks !

Is it definitely the same data you are connecting to via Sdata?

>Depending on the version you went from and to the port number may have changed from 5493 to 5495

If it were the wrong port I'd expect a 503 error response unless the older version of Accounts was also running on the same machine, in which case it could conflict but would not expect a 401 response for any reason other than the username/password not being valid

**Comment by letoncse** [comment]
Sorry , actually I'm getting 504 error message. @darroncockram 

![image](https://user-images.githubusercontent.com/1812631/87035175-db0b3000-c1e0-11ea-8b56-37cd0cd67685.png)

**Comment by darroncockram** [comment]
OK so a 504 means your proxy has passed the request on to Sdata service but has timed out waiting on a response, typically this would be after waiting 30 seconds.
It is possible that for some reason the request is taking a while to complete on the Sdata service and giving you are getting the error because the proxy is not waiting long enough. That wouldn't seem too likely though as it is a fairly lightweight request and even on a large dataset it should be returning fairly quickly. One thing that could cause performance problems is if the data were locked in use by some other process e.g. performing an exclusive operation in the app. Again seems unlikely but worth checking for active sessions in the Accounts application.
The other thing that springs to mind is if the Sdata service thinks it needs to show some UI but cant as it is a background process. It's not a common thing but I have seen this happen before. If it is in that state every request will look like it has hung. Are you able to test issuing the request directly to the sdata service?

**Comment by letoncse** [comment]
Thanks for your reply . Are you able to test issuing the request directly to the sdata service?-- How can i do this? 
There have to do any settings ? below see the below image.
![image](https://user-images.githubusercontent.com/1812631/87037287-e1e77200-c1e3-11ea-864d-b332e0dd36e3.png)

I'm taking url from, please see the below image. Thanks 
![image](https://user-images.githubusercontent.com/1812631/87037534-44d90900-c1e4-11ea-8b49-5a1ad0bd697c.png)

**Comment by darroncockram** [comment]
> How can i do this?

You would just use the local URL (as in the one displayed in the Sdata settings dialog you show in your screen shot.

However one thing that I can see based on your screen shot is that the dataset Id shown in your fiddler capture does not match the Id shown in the Sdata settings dialog. This would suggest it is not the same data you are connecting to

**Comment by letoncse** [comment]
> However one thing that I can see based on your screen shot is that the dataset Id shown in your fiddler capture does not match the Id shown in the Sdata settings dialog. This would suggest it is not the same data you are connecting to

Last screenshot taking from my local pc.

**Comment by darroncockram** [comment]
Aren't you connecting to the same dataset in the Accounts UI though?

Either way the same advice would stand. Can you access the Sdata endpoint directly?

**Comment by letoncse** [comment]
> Aren't you connecting to the same dataset in the Accounts UI though?
Yes , I'm using same dataset.
> Either way the same advice would stand. Can you access the Sdata endpoint directly?

When I'm browsing url I'm getting below message because I'm not using any credential. 

```
<sdata:severity>error</sdata:severity>
<sdata:sdataCode>ResourceKindNotFound</sdata:sdataCode>
<sdata:applicationCode/>
<sdata:message>Unable to locate the specified object 'accounts50/GCRM/-'</sdata:message>
<sdata:stackTrace/>
<sdata:payloadPath/>
```

**Comment by darroncockram** [comment]
You're not specifying the resource kind in that URL. Also '-' is the identifier for the default dataset which is not necessarily the same as the one you are connecting to in the example in fiddler

**Comment by letoncse** [comment]
> You're not specifying the resource kind in that URL. Also '-' is the identifier for the default dataset which is not necessarily the same as the one you are connecting to in the example in fiddler

Sorry this is my url what is my mistake please 
http://82.XXX.231.49:5495/sdata/accounts50/GCRM/{A5F26292-B9C6-XXX-XXX-090EA501988C}

**Comment by darroncockram** [comment]
You need a resource kind and optional query parameters on the end e.g.

http://82.XXX.231.49:5495/sdata/accounts50/GCRM/{A5F26292-B9C6-XXX-XXX-090EA501988C}/tradingAccounts?count=10

However is 82.XXX.231.49 the IP address of the proxy or the machine that is running the Sdata service? I'm suggesting a test directly to the Sdata machine. Ideally even testing on the machine itself

http://localhost:5495/sdata/accounts50/GCRM/{A5F26292-B9C6-XXX-XXX-090EA501988C}/tradingAccounts?count=10

**Comment by letoncse** [comment]
> [http://82.XXX.231.49:5495/sdata/accounts50/GCRM/{A5F26292-B9C6-XXX-XXX-090EA501988C}/tradingAccounts?count=10](http://82.XXX.231.49:5495/sdata/accounts50/GCRM/%7BA5F26292-B9C6-XXX-XXX-090EA501988C%7D/tradingAccounts?count=10)

When I'm accessing directly I'm getting same error that time out exception 

> However is 82.XXX.231.49 the IP address of the proxy or the machine that is running the Sdata service? I'm suggesting a test directly to the Sdata machine. Ideally even testing on the machine itself

82.XXX.231.49 the IP address of the machine there Sdata service is running.

> [http://localhost:5495/sdata/accounts50/GCRM/{A5F26292-B9C6-XXX-XXX-090EA501988C}/tradingAccounts?count=10]

I will check on client Machine with this url and let you know . Thank you so much !

**Comment by darroncockram** [comment]
If 82.XXX.231.49 the IP address of the machine where the Sdata service is running then there's no reason to think it would work locally if it's not working remotely. Worth confirming if you can log on to the data using Accounts on that machine and if the Sdata datasets show in the Sdata options dialog on that machine too.

**Comment by letoncse** [comment]
> If 82.XXX.231.49 the IP address of the machine where the Sdata service is running then there's no reason to think it would work locally if it's not working remotely. Worth confirming if you can log on to the data using Accounts on that machine and if the Sdata datasets show in the Sdata options dialog on that machine too.

Thank you so much @darroncockram , issue is resolved. After restart the sage50 pc I'm getting data. Issue was in this url http://82.XXX.231.49:5495/.
