### ISSUE TITLE
Sales Orders not showing in UI

### ISSUE THREAD

**Issue by nathan-barques** [Sage/SData-2.0#16]
After upgrading to sage accounts 50 sales orders will no longer show in the UI. 
The orders can be seen using the SData get request, however the reference number provided seems to have already been used on a past order.

**Comment by darroncockram** [comment]
Not much to go on there I'm afraid. A couple of possibilities spring to mind though. Either the dataset you a looking at in the UI and the one you are querying via Sdata are not the same or perhaps that you have a filter applied in the UI that is excluding all orders.

**Comment by nathan-barques** [comment]
Thanks for the suggestions Darron.
I think it is somehow looking at the old dataset as new orders in the ui aren't visible either. Is there a way to change where the feed looks?
Many thanks
Nathan
On 19 May 2015 6:58 pm, Darron Cockram <notifications@github.com> wrote:Not much to go on there I'm afraid. A couple of possibilities spring to mind though. Either the dataset you a looking at in the UI and the one you are querying via Sdata are not the same or perhaps that you have a filter applied in the UI that is excluding all orders.

**Comment by darroncockram** [comment]
The feeds use the same mechanism as the UI does to load the company list but if you have more than one version of Accounts installed it will use the company list from the latest installed version (which isn't necessarily the highest version) so  install order can be a factor.
You always check where the data is being loaded from by looking in the log files. These would be found under C:\Windows\SysWOW64\config\systemprofile\AppData\Roaming\SDOAdapterLogs (assuming you havent changed the user that the service runs under and that you are running a 64 bit OS).
