### ISSUE TITLE
Access to Product Invoice > Order > Custom Fields

### ISSUE THREAD

**Issue by nddsoft** [Sage/SData-2.0#161]
Hi Again,
Using Sage Accounts 50 UK version: 24.0.68.0 with SData enabled.

I'm desperately trying to find out if I can access/write the following with SData..
In Sage, Product Invoice, "Order" tab, The 3 Custom Fields: Analysis1, Analysis2, Analysis3

They don't seem be be made available, is that correct?

Also, on the same tab, the "Customer Order Details", I know the Order Taken By can be accessed, but can the Customer Contact and Customer Tel be accessed too?  I can't find them either...

Thank you for any help.
![product-invoice-order](https://user-images.githubusercontent.com/16680001/92726199-6fd40a80-f397-11ea-8885-850263621848.jpg)

Steve

**Comment by darroncockram** [comment]
I'm afraid the invoice analysis fields are not exposed to the Sdata feeds and neither are the customer telephone and contact fields.
