### ISSUE TITLE
Having issues in SDataSamples projects. (Sage.crmErp.x2008.Feeds is not resolving)

### ISSUE THREAD

**Issue by ArshathS** [Sage/SData-2.0#164]
I'm new to this part as a developer and I'm trying connecting to Sage 50 Accounts professional using SDataSamples and the ultimate goal is to write the data into our application from Sage 50.
I run the project (ex: GetInstanceSchema) it works as expected and most of the other projects are using Sage.crmErp.x2008.Feeds dll which I don't find in the solution or anywhere.

I'm using visual studio 2017.

Here is a screenshot of the error
![image](https://user-images.githubusercontent.com/35331259/100968474-6b169100-3557-11eb-8d81-fe6a0e9a8d73.png)

Could you please help with these?

**Comment by darroncockram** [comment]
The problem you have there is that you would need to run the Sdata Tools for Visual Studio in the FeedModel project. The problem with that is that you are on Visual Studio 2017 and the Sdata Tools have not been updated to run against that version so you would be unable to run that.

There are workarounds by using older versions of Visual Studio but to make things easier I have committed the generated file to the repo. If you pull the latest it should build without error now. Bear in mind that the repo (and therefore the generated code) are not officially Sage approved. Given that Sdata is considered 'community supported' this is not likely to be a practical issue but worth keeping in mind around redistribution and support.

**Comment by ArshathS** [comment]
I got the latest and tried building the app and it still giving the same error.
I can see none of the auto-generated files are exist
![image](https://user-images.githubusercontent.com/35331259/100984050-2fd48c00-3570-11eb-9cd2-67c39089cb73.png)

If I need to download the older version what would be the latest older version of the visual studio I should download?

**Comment by ArshathS** [comment]
> The problem you have there is that you would need to run the Sdata Tools for Visual Studio in the FeedModel project. The problem with that is that you are on Visual Studio 2017 and the Sdata Tools have not been updated to run against that version so you would be unable to run that.
> 
> There are workarounds by using older versions of Visual Studio but to make things easier I have committed the generated file to the repo. If you pull the latest it should build without error now. Bear in mind that the repo (and therefore the generated code) are not officially Sage approved. Given that Sdata is considered 'community supported' this is not likely to be a practical issue but worth keeping in mind around redistribution and support.

I got the latest and tried building the app and it still giving the same error.
I can see none of the auto-generated files are exist
![image](https://user-images.githubusercontent.com/35331259/100985045-80001e00-3571-11eb-976d-3be564562686.png)


If I need to download the older version what would be the latest older version of the visual studio I should download?

**Comment by darroncockram** [comment]
> I got the latest and tried building the app and it still giving the same error.
> I can see none of the auto-generated files are exist

Sorry, that's my fault as the new Git experience in Visual Studio 2019 meant the commit did not get pushed. It has been now so pull the latest and it should build OK

**Comment by ArshathS** [comment]
> > I got the latest and tried building the app and it still giving the same error.
> > I can see none of the auto-generated files are exist
> 
> Sorry, that's my fault as the new Git experience in Visual Studio 2019 meant the commit did not get pushed. It has been now so pull the latest and it should build OK

Thanks for your help so far and now all working as expected.

This is out of this topic and needs help for this as well. When I run "GetTradingAccounts" project I'm not getting any error but **feed.Entries** do not have any data in them but i can see a lot of records from Sage 50 UI.

What could be the reason for this? No errors when running the code
![image](https://user-images.githubusercontent.com/35331259/100990189-a032db80-3577-11eb-8264-4847ead8512f.png)

**Comment by darroncockram** [comment]
Most likely thing is the data you are connecting to via Sdata is not the same data you are looking at in the Sage 50 UI.

All of the code samples rely on an assumption that the dataset to access is the 'default' one. This is deliberate for the samples as the is no way to know up front what the correct dataset identifier should be on the target machine. Datasets and their identifiers can be discovered generically but that adds complexity to the code and the intent of the samples is to keep things simple and focus each one on individual example tasks. My general advice is that you should not use the default dataset for anything other than demo code though.

There is the code sample 'DiscoverDatasetsForContract' that demonstrates how generically determine the available datasets. Armed with the results of that you could change the dataset Id (the dash) in this line of code:

`uri.BuildLocalPath("Accounts50", "GCRM", "-", "tradingAccounts");`

To be the actual dataset Id of the data you want to access.

Also one other gotcha when looking at datasets in the UI Vs Sdata. The UI may be connecting to both local data and data located on the network, but by default Sdata only accesses local data and you will not see any datasets on the network even if they show in the main UI.

Hope that helps.
