### ISSUE TITLE
GET operation failed - Cannot open database ''.  It may not be a database that your application recognizes, or the file may be corrupt.

### ISSUE THREAD

**Issue by ArshathS** [Sage/SData-2.0#166]
When I try to get data from Sage 50 Professional using sdatasamples projects I get the following error. 

> GET operation failed - Cannot open database ''.  It may not be a database that your application recognizes, or the file may be corrupt.

When I create a new company and insert a couple of records manually then I can get the data without any issues and only the problem arises when I try to use a real user with real data set who has full access level rights.

When I try to get tradingAccount by setting the count to 1 then I can get the first record but when I remove the count or set the count to > 1 then the above error pops up.

Could you please help with this?

**Comment by ArshathS** [comment]
@darroncockram Could you please suggest me what could be the reason for this? For the real data set, I restored the data from a WinRAR archive.

Creating a company and then populating a couple of records works as expected above issue is with the restored data set.

**Comment by ArshathS** [comment]
Is this something to do with the archive file? Do I need to request another back up from our client?

When I open the desktop app I can see all available data in it with the real data set.

**Comment by darroncockram** [comment]
>  I restored the data from a WinRAR archive.

I strongly suspect this is the issue a WinRAR archive is not a valid backup for Sage 50 Accounts data. I'd guess that the archive is missing a critical file that would be included in a proper backup file created in via Accounts. There are some files that are critical to the Sdata implementation that are not critical to the Accounts UI so that may be why the data looks OK on the surface in the UI. 

Best to get a proper backup - this would be a .001 file - and restore that via the Accounts UI rather than trying to use archives made using external tools.

**Comment by ArshathS** [comment]
@darroncockram 
Thanks for the answers above. It works.

I have noticed a few things.

- When getting data if, I specify a number like (uri.Count = 100;) and iterate through a while loop I can get all the records without missing a single one but when it comes to performance it takes a very long period of time to complete as requestFeed (request.RequestFeed<commodityFeedEntry>(feed);) takes more time. (In this case, the total count of the record is 8700)
You can think of GetTradingAccountsPaged project as a sample. My codebase has the exact same code as that project.

Do you have any suggestions to improve the performance? If I do not specify the count I'm always getting some error like time out or etc that is why I'm looping through "while"

**Comment by ArshathS** [comment]
@darroncockram Could you please help with any suggestion

**Comment by darroncockram** [comment]
The main thing would be don't retrieve the entire feed, paged or not. It's difficult to say without understanding more detail about your specific use case but there are very few reasons I can think of why the entirety of a feed is needed at any one time. 

As a general rule you want to limit your requests to just the data you need, when you need it. For example even if you were displaying a list of all trading accounts such as in a grid you should consider using paging in the grid and only retrieve a single page at a time if and when a user navigates between pages.

If at all possible retrieve individual records rather than multiple ones. By that I don't mean retrieve the entire feed as individual requests but instead following the above advice but to an individual record - only retrieve it if you need it e.g a user clicks a view details option in your UI.

If you do need to retrieve multiple records e.g. the grid scenario I would recommend always specifying a count to limit the size of the returned results but only retrieve that 1 page. Delay getting any other pages until you absolutely have to.

The other thing would be to minimise or remove the use of includes unless you absolutely have to. Including related data is one of the most expensive operations you can do so only do it when you if you must. Again you can combine this advice with the above e.g. do not use an include when retrieving a list of trading accounts to display on a grid but if a user selects to view the details of an individual one.

As I say that's general advice but happy to give more specific advice if you have further details on your particular use case.

**Comment by ArshathS** [comment]
@darroncockram 
The main purpose of using SData is to get all possible data and synch it to our application. It is a windows service project which runs every day or every X mins to get data from Sage and put it into our Application.

> The main thing would be don't retrieve the entire feed, paged or not. It's difficult to say without understanding more detail about your specific use case but there are very few reasons I can think of why the entirety of a feed is needed at any one time.

We create each tradingAccount as an Account in our system so I need registeredAddress,contacts, emails, phones, pricelists to populate related info into our existing Account table. So that I'm including the above properties. And passing tradingAccount reference to get contacts from Sage and linking that to the newly created Account. So that I'm including `uri.Include = "registeredAddress,contacts,emails,phones,pricelists";`

I divided the above operations into two parts one to get Customers and another method to get Suppliers using the where clause. Both the cases we write into our same Account table with a type called Supplier or Customer.

As you said it is one of the most expensive operations and removing the include entirely has an improvement.

When I loop through the result of tradingAccount I pass reference as an argument to get Contacts and seed the results into our contacts table as shown below. Again I need `"postalAddresses,phones,emails";` from contacts.
![image](https://user-images.githubusercontent.com/35331259/101975776-2381ba80-3c65-11eb-9041-a0b1752d59fe.png)

If I remove "include" what is the recommended way of getting tradingAccount related items such as registeredAddress, contacts, emails, phones, pricelists and Contacts related items such as postalAddresses,phones,emails?

Let me provide you the code segments I'm using which will be easier for you to see and understanding instead of me typing a long paragraph.

- 1st Step (Processing Price List): No issues at all it gets the data as soon as i run the service project. It has around only 387 records

- 2nd Step (Processing TradingAccount - Customer/Supplier) - Time consuming
```
           tradingAccountFeed feed = new tradingAccountFeed();

            Dictionary<string, tradingAccountFeedEntry> keyValuesCustomerTradingAccount = new Dictionary<string, tradingAccountFeedEntry>();

            // Build the request URI. This example assumes that the Accounts 50 GCRM contract implementation is available
            SDataUri uri = new SDataUri();
            uri.BuildLocalPath(_applicationName, _contract, "{" + _companyDataSetId + "}", "tradingAccounts");
            uri.Port = _sagePort;
            // Set the query based on the user input
            uri.Where = string.Format("customerSupplierFlag eq '{0}'", "Customer");
            uri.Include = "registeredAddress,contacts,emails,phones,pricelists";
            //uri.Include = "registeredAddress,phones,pricelists";
            uri.Count = 10;

            int totalCount = 0;
            long processed = 0;

            do
            {
                uri.StartIndex = processed + 1;

                // Build an Sdata request from the URI
                SDataRequest request = new SDataRequest(uri.Uri)
                {
                    AllowPromptForCredentials = false,
                    Username = _sageUserName,
                    Password = _sagePassword
                };

                // Submit the request for trading accounts

                request.RequestFeed<tradingAccountFeedEntry>(feed);

                if (request.IsStatusValidForVerb)
                {

                    if (feed.Entries == null || feed.Entries.Count == 0)
                    {
                        Console.WriteLine("No more records");
                        break;
                    }
                    totalCount = Convert.ToInt32(feed.TotalResults);

                    //this.Loggers.("{0} customer matching records found", feed.TotalResults);
                    foreach (tradingAccountFeedEntry entry in feed.Entries)
                    {
                        //this.LogInformation("Name:" + entry.name + ", ref Number:" + entry.reference + ", Balance:" + entry.financeBalance);
                        SACreateCompany createCompany = new SACreateCompany(_databaseManager, _loggers);
                        string acctId = string.Empty;
                        bool error = false;
                        bool exists = false;

                        if (_logToEventViewer)
                        {
                            this.LogStatus(string.Format("{0},{1}", "Processing Trading Account: ", entry.name));
                        }

                        createCompany.AccountExists(entry.UUID.ToString(), out acctId, out exists, out error);

                        if (!exists)
                        {
                            createCompany.CreateAccount(entry, "CST", DateTime.Now, out acctId);
                            keyValuesCustomerTradingAccount.Add(acctId, entry);
                            if (_importAddressAndContacts)
                            {
                                //GetContactsAsync(entry.reference, acctId).Wait();
                            }
                        }
                        else
                        {
                            createCompany.UpdateAccount(entry, "CST", DateTime.Now, acctId);
                            keyValuesCustomerTradingAccount.Add(acctId, entry);
                            if (_importAddressAndContacts)
                            {
                                //GetContactsAsync(entry.reference, acctId).Wait();
                            }
                        }



                        #region Invoice
                        //GetSageInvoicesAsync(entry).Wait();
                        #endregion

                        ++processed;
                        _loggers.LogInformation(processed +" Company (Customer) records reported");
                    }
                }
                else
                {
                    // There was a problem
                    //this.LogInformation("Request failed. Response was {0}", request.HttpStatusCode.ToString());
                    if (request.Diagnoses != null)
                    {
                        foreach (Diagnosis diagnosis in request.Diagnoses)
                        {
                            //this.LogError(diagnosis.Message);
                        }
                    }
                }
            } while (processed < totalCount);


            #region Import Contacts
            if (_importAddressAndContacts)
            {
                foreach (var item in keyValuesCustomerTradingAccount)
                {
                    GetContactsAsync(item.Value.reference, item.Key).Wait();
                }
            }
            #endregion

            #region Invoice
            foreach (var item in keyValuesCustomerTradingAccount)
            {
                GetSageInvoicesAsync(item.Value).Wait();
            }
            #endregion
```

> GetContactsAsync(item.Value.reference, item.Key).Wait(); method

```
            contactFeed feed = new contactFeed();
            SDataUri uri = new SDataUri();
            uri.BuildLocalPath(_applicationName, _contract, "{" + _companyDataSetId + "}", "contacts");
            uri.Port = _sagePort;
            // Set the query based on the user input
            uri.Where = string.Format("reference eq '{0}'", reference);
            uri.Include = "postalAddresses,phones,emails";
            //uri.Count = 100;

            int totalCount = 0;
            long processed = 0;

            //do
            //{
            //    uri.StartIndex = processed + 1;

                SDataRequest request = new SDataRequest(uri.Uri)
                {
                    AllowPromptForCredentials = false,
                    Username = _sageUserName,
                    Password = _sagePassword
                };

                // Submit the request for trading accounts
                request.RequestFeed<contactFeedEntry>(feed);

                if (request.IsStatusValidForVerb)
                {
                    if (feed.Entries == null || feed.Entries.Count == 0)
                    {
                        //Console.WriteLine("No more records");
                        //break;
                    }
                    totalCount = Convert.ToInt32(feed.TotalResults);

                    foreach (contactFeedEntry entry in feed.Entries)
                    {
                        SACreateContact createContact = new SACreateContact(_databaseManager, _loggers);
                        string contId = string.Empty;
                        bool error = false;
                        bool exists = false;

                        if (entry.postalAddresses != null &&
                            ((entry.postalAddresses.Entries[0].type == "Shipping" && _importDeliveryAddressAsContacts) || (entry.postalAddresses.Entries[0].type == "Registered" && _importRegisteredAddressAsContact)))// || entry.postalAddresses.Entries[0].type == "Registered"))
                        {
                            createContact.ContactExists(entry.UUID.ToString(), out contId, out exists, out error);
                            if (!exists)
                            {
                                createContact.CreateContact(entry, acctId, out contId);
                            }
                            else
                            {
                                createContact.UpdateContact(entry, acctId, contId);
                            }

                        }

                        //++processed;

                    }
                }
                else
                {
                    // There was a problem
                    //this.LogInformation("Request failed. Response was {0}", request.HttpStatusCode.ToString());
                    if (request.Diagnoses != null)
                    {
                        foreach (Diagnosis diagnosis in request.Diagnoses)
                        {
                            //this.LogError(diagnosis.Message);
                        }
                    }
                }
            //} while (processed < totalCount);
```

> GetSageInvoicesAsync(item.Value).Wait(); method

```
            if (account == null)
            {
                //Console.WriteLine("Unable to find a customer record");
                //Console.ReadKey(true);
                return;
            }
            salesInvoiceFeed invoices = new salesInvoiceFeed();

            SDataUri accountUri = new SDataUri(account.Uri);
            accountUri.AppendPath("salesInvoices");
            accountUri.Format = Sage.Common.Syndication.MediaType.Atom;
            accountUri.Port = _sagePort;

            //accountUri.Count = 100;

            int totalCount = 0;
            long processed = 0;

            //do
            //{
                //accountUri.StartIndex = processed + 1;

                SDataRequest invoiceRequest = new SDataRequest(accountUri.Uri)
                {
                    AllowPromptForCredentials = false, // Do not show any UI
                    Username = _sageUserName,
                    Password = _sagePassword
                };

                invoiceRequest.RequestFeed<salesInvoiceFeedEntry>(invoices);

                if (invoiceRequest.IsStatusValidForVerb)
                {
                    if (invoices.Entries == null || invoices.Entries.Count == 0)
                    {
                        //Console.WriteLine("No more records");
                        //break;
                    }
                    totalCount = Convert.ToInt32(invoices.TotalResults);

                    if (invoices.Entries != null)
                    {

                        foreach (salesInvoiceFeedEntry invoice in invoices.Entries)
                        {
                            SACreateInvoice createInvoice = new SACreateInvoice(_databaseManager, _loggers);
                            string invoiceId = string.Empty;
                            bool error = false;
                            bool exists = false;

                            if (_logToEventViewer)
                            {
                                this.LogStatus(string.Format("{0},{1}", "Processing Invoice: ", invoice.reference));
                            }

                            createInvoice.InvoiceExists(invoice.UUID.ToString(), out invoiceId, out exists, out error);

                            if (!exists)
                            {
                                createInvoice.CreateInvoice(invoice, account, out invoiceId);
                            }
                            else
                            {
                                createInvoice.UpdateInvoice(invoice, account, invoiceId);
                            }
                            ++processed;
                        }
                    }
                    else
                    {
                        //Console.WriteLine("Request successful. Found 0 invoices.");
                    }
                }
                else
                {

                }
            //} while (processed < totalCount);
```

- 3rd Step - Doing the same 2nd steps for Suppliers

- 4th Step - Processing commodities and Prices - Very time consuming
```
            commodityFeed feed = new commodityFeed();

            SDataUri uri = new SDataUri();
            uri.BuildLocalPath(_applicationName, _contract, "{" + _companyDataSetId + "}", "commodities");
            uri.Port = _sagePort;
            uri.Include = "prices";
            uri.Count = 10;

            int totalCount = 0;
            long processed = 0;

            do
            {
                uri.StartIndex = processed + 1;

                SDataRequest request = new SDataRequest(uri.Uri)
                {
                    AllowPromptForCredentials = false,
                    Username = _sageUserName,
                    Password = _sagePassword,
                    ResponseContentType = Sage.Common.Syndication.MediaType.JSON
                };


                request.RequestFeed<commodityFeedEntry>(feed);

                if (request.IsStatusValidForVerb)
                {
                    if (feed.Entries == null || feed.Entries.Count == 0)
                    {
                        _loggers.LogInformation("No more records");
                        break;
                    }
                    totalCount = Convert.ToInt32(feed.TotalResults);

                    foreach (commodityFeedEntry entry in feed.Entries)
                    {
                        //this.LogInformation("Name:" + entry.name + ", ref Number:" + entry.reference + ", Balance:" + entry.financeBalance);
                        SACreateProductTree createProductTree = new SACreateProductTree(_databaseManager, _loggers);
                        string ptid = string.Empty;
                        bool error = false;
                        bool exists = false;

                        if (_logToEventViewer)
                        {
                            this.LogStatus(string.Format("{0},{1}", "Processing Trading Account: ", entry.name));
                        }

                        createProductTree.ProductTreeExists(entry.UUID.ToString(), out ptid, out exists, out error);

                        if (!exists)
                        {
                            createProductTree.CreateProductTree(entry, out ptid);
                        }
                        else
                        {
                            createProductTree.UpdateProductTree(entry, ptid);
                        }

                        #region PRICE_LIST_PRODUCT
                        _loggers.LogInformation("Create or Update into PRICELIST_PRODUCT");
                        if (entry.prices!=null && entry.prices.Entries!=null && entry.prices.Entries.Count>0)
                        {
                            foreach (var price in entry.prices.Entries)
                            {
                                priceFeed pfeed = new priceFeed();
                                SDataUri puri = new SDataUri();
                                puri.BuildLocalPath(_applicationName, _contract, "{" + _companyDataSetId + "}", "prices");
                                puri.Include = "categories,pricelist";
                                puri.Where = string.Format("UUID eq '{0}'", price.UUID);

                                puri.Port = _sagePort;

                                SDataRequest prequest = new SDataRequest(puri.Uri)
                                {
                                    AllowPromptForCredentials = false,
                                    Username = _sageUserName,
                                    Password = _sagePassword
                                };

                                prequest.RequestFeed<priceFeedEntry>(pfeed);

                                if (prequest.IsStatusValidForVerb)
                                {
                                    foreach (priceFeedEntry pentry in pfeed.Entries)
                                    {
                                        SACreatePricelistProduct createPricelistProduct = new SACreatePricelistProduct(_databaseManager, _loggers);
                                        string plnpid = string.Empty;
                                        bool perror = false;
                                        bool pexists = false;

                                        SACreatePriceList sACreatePriceList = new SACreatePriceList(_databaseManager, _loggers);

                                        string plid = string.Empty;
                                        bool plerror = false;
                                        bool plexists = false;

                                        sACreatePriceList.PriceListExists(pentry.pricelist.UUID.ToString(),out plid,out plexists, out plerror);

                                        if (plexists)
                                        {
                                            createPricelistProduct.PriceListProductExists(plid, ptid, out plnpid, out pexists, out perror);

                                            if (!pexists)
                                            {
                                                string createdId = plnpid;
                                                createPricelistProduct.CreatePriceListProduct(entry, pentry, createdId, out plnpid);
                                            }
                                            else
                                            {
                                                string createdId = plnpid;
                                                createPricelistProduct.UpdatePriceListProduct(entry, pentry, createdId, out plnpid);
                                            }
                                        }
                                    }
                                }
                            }
                        }
                        #endregion

                        ++processed;
                        _loggers.LogInformation(processed + " Product Tree (Commodities) records reported");
                    }
                }
                else
                {
                    // There was a problem                  
                    if (request.Diagnoses != null)
                    {
                        foreach (Diagnosis diagnosis in request.Diagnoses)
                        {
                            //this.LogError(diagnosis.Message);
                        }
                    }
                }
            } while (processed < totalCount);
```

Trust me after implementing all of these I started my windows service and it has been running for 11 hours and It is still in the "GetSageInvoicesAsync" method that is in the 2nd method.

But slowly it is doing its job.

Could you please guide me to improve these scenarios? I want to bring it into at least 1 hour or less.

**Comment by darroncockram** [comment]
You have created multiple N+1 problems there that will definitely be impacting performance. Includes are there to help stop N+1 type problems but should be used sparingly as they are expensive operations themselves and do not support filtering options so you can end up getting more data that you actually want (slowly!). 

It looks like you are extracting significant amounts of data making it a fairly heavy ETL process that is possibly not really suited for Sdata - the thing to bear in mind is that the Sdata implementation is intended for lightweight, decoupled integrations. Importing all the data also introduces a sync issue as you need to keep that data up to date (in both directions depending on exactly what is being done with the data) and have to deal with conflict resolution issues and/or race conditions.

What I would suggest challenging is the overall architecture of your application and need to import all the data in to the separate application at all. Turning things on their head in terms of the approach _might_ help.

Why does all the data need to be extracted in to the service instead of just querying it from the feeds as it's needed in the application? What does the service do with all that data? Could the service not just query for the data dynamically? For example the service wants to create an invoice so you query the Sdata feeds to the specific customer you want o create the invoice for, specifying an include for addresses and contacts if necessary, then build the POST request for the salesInvoice type using information from the results from the previous request.

If necessary you could cache some of the responses e.g. you are going to post multiple invoices for the same customer - just get the customer once and then build multiple posts for salesInvoice based on that single cached tradingAccount response.

Hope that helps.

**Comment by ArshathS** [comment]
Thanks so much for your time to respond to my questions.

> Why does all the data need to be extracted in to the service instead of just querying it from the feeds as it's needed in the application? What does the service do with all that data? Could the service not just query for the data dynamically? For example the service wants to create an invoice so you query the Sdata feeds to the specific customer you want o create the invoice for, specifying an include for addresses and contacts if necessary, then build the POST request for the salesInvoice type using information from the results from the previous request.

It is not importing all the data into the service, instead, it is importing into our desktop app via the windows service. And our client needs all the sage data to be available in our desktop application as well. We normally synch our desktop application data with other 3rd party applications via windows service and it differs what is the 3rd party app depend on the client to client and in this case, it happened to be Sage 50 UK.

I'm not doing any post-operation as of now and all are reading and seeding into our db. And we need to support post as well in a later stage.

Just wondering if there any other options other than SData to do this. we are happy to pay for that as well (like SDK or whatever available) which will speed up things for us.

**Comment by darroncockram** [comment]
> It is not importing all the data into the service, instead, it is importing into our desktop app via the windows service. And our client needs all the sage data to be available in our desktop application as well. We normally synch our desktop application data with other 3rd party applications via windows service and it differs what is the 3rd party app depend on the client to client and in this case, it happened to be Sage 50 UK.  

Is the desktop application itself extensible? If it is then my advice around real time querying of the Sdata feeds would still stand. Especially if you are only doing read operations.

> Just wondering if there any other options other than SData to do this. we are happy to pay for that as well (like SDK or whatever available) which will speed up things for us.

Sage Data Objects (the Sage 50 Accounts product specific SDK) is the other option but for that you would need to sign up to the 3rd party developer programme - https://www.sage.com/en-gb/partners/independent-software-vendors/

There is also the option of using Report Designer to export the necessary data in to some easy to use format such as a CSV or XML file that you then import via your service.

Finally there is the ODBC driver but that is a completely unsupported option so not one I can recommend I'm afraid.

**Comment by ArshathS** [comment]
@darroncockram 
Thanks for your comments and feedback.

A quick question, Can we get the last updated date and created on date from of a record (ex: tradingAccount) ? This way I can make it very faster by retrieving only the updated or newly created records.

**Comment by darroncockram** [comment]
Yes, each resource has an updated date and you can filter on that if you need to. My other advice would still stand though and would suggest avoiding sync if at all possible.

**Comment by ArshathS** [comment]
Thanks and I agree with you on Sync. Out of my curiosity just giving it a try on this as well.

Just wanted to make sure is it a correct where clause to get the updated one?
`uri.Where = string.Format("updated ge '{0}'", lastRunDate);`

When i run this i get zero results and I know I have few records which got updated after the last run date

**Comment by darroncockram** [comment]
You need to handle the date specially .See the literals section on this page: https://sage.github.io/SData-2.0/pages/core/0212/
