### ISSUE TITLE
SIF Sage Accounts 50 2013 schema

### ISSUE THREAD

**Issue by Lazyname** [Sage/SData-2.0#17]
Hello,
Started learning SData currently fallowing a youtube video tutorial:
https://www.youtube.com/watch?v=-19BagI2bOE

I'm tring to access the schema by typing:
http://localhost:5493/sdata/accounts50/gcrm/-/$schema

When credentials window is evoced where I type MANAGER as a user name and blank password
"Index was out of range" is the error message 

<?xml version="1.0" encoding="UTF-8"?>

-<diagnosis xmlns:http="http://schemas.sage.com/sdata/http/2008/1" xmlns:sme="http://schemas.sage.com/sdata/sme/2007" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:sdatasync="http://schemas.sage.com/sdata/sync/2008/1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.sage.com/sdata/2008/1">

<sdata:severity>error</sdata:severity>

<sdata:sdataCode>ApplicationDiagnosis</sdata:sdataCode>

<sdata:applicationCode xsi:nil="true"/>

<sdata:message>Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index</sdata:message>

<sdata:stackTrace>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource) at System.ThrowHelper.ThrowArgumentOutOfRangeException() at System.Collections.Generic.List`1.get_Item(Int32 index) at System.Collections.Generic.List`1.System.Collections.IList.get_Item(Int32 index) at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.GetRequest(IRequest request) at Sage.Integration.Accounts50.SDOAdapter.SDOAdapter.GetRequest(IRequest request) at Invokeddfdf6a43d2d4ed498b7b64d6cde5a35.Invoke(Object , IRequest ) at Sage.Integration.Messaging.RequestTargetRegistration.RequestTargetInvoker.Invoke(IRequest request) at Sage.Integration.Messaging.Request.Process(RequestTargetInvoker invoker) at Sage.Integration.Adapter.AdapterController.RealAdapterController.Process(IRequest request) at Sage.Integration.Adapter.AdapterController.RealAdapterController.ProcessWorker(IProtocolRequest protocolRequest) at Sage.Integration.Adapter.AdapterController.Process(IProtocolRequest request) at Sage.Integration.Messaging.MessagingService.Process(IProtocolRequest protocolRequest)</sdata:stackTrace>

<sdata:payloadPath/>

</diagnosis>

Any input is much appreciated.
In my passed learning experiance I understood tnat this may be a verry naive question for which I cencierly apologise

Thanks.
Regards

**Comment by darroncockram** [comment]
Not an error I've seen before. What version of Accounts are you using?

**Comment by darroncockram** [comment]
Are there any datasets exposed to the Sdata feeds? What do you get if you query the available datasets - http://sage015573:5493/sdata/$system/registry/*/endpoints?where=endPointType%20eq%20%27dataSet%27

**Comment by Lazyname** [comment]
Thanks for the replay Darroncockram,

I assumed that sage’s test data is exposed to the feeds but fallowing the link you provided appears that that is not the case.
Fallowing your feeds comment I’ve done my googling but with no results to actually get me moving.
I’m posting an image to the webpage generated fallowing the link you provided.
Can you please give me some navigation how to expose Sage test data to the feeds in order for me to start playing with prototype interfaces and explore the functionalities?


![error](https://cloud.githubusercontent.com/assets/12531450/7909150/26f1b6d2-0842-11e5-95a5-e13f94741ec6.png)

Thanks a million
All the best
Regards Iliyan

**Comment by Lazyname** [comment]
Thanks for the replay Darroncockram, 


I assumed that sage’s test data is exposed to the feeds but fallowing the link you provided appears that that is not the case.

Fallowing your feeds comment I’ve done my googling but with no results to actually get me moving.

I’m posting an image to the webpage generated fallowing the link you provided.

Can you please give me some navigation how to expose Sage test data to 
the feeds in order for me to start playing with prototype interfaces and
 explore the functionalities? 


    


Thanks a million

All the best

Regards Iliyan

**Comment by darroncockram** [comment]
So that is suggesting that you have no datasets set up in Accounts. If you launch the main Accounts application it should give you options to create a new dataset. Once you have a dataset created if you restart the Sdata service and requery the endpoints feed you should see the dataset available and I suspect the schema request will work too.

**Comment by Lazyname** [comment]
Got it now,

Brilliant worked like a charm. 
Saved my day.


Thanks once again
All the best
Regards Iliyan
