### ISSUE TITLE
POST contact email - specified object error

### ISSUE THREAD

**Issue by PatrickWWork** [Sage/SData-2.0#170]
Hi,

I am trying to create an email for a contact using the `sdata/Accounts50/GCRM/-/contacts(<ContactId>)/emails` endpoint, but I am a bit stuck on the payload.

Currently I have the following as the body:
```
<entry xmlns:sdata="http://schemas.sage.com/sdata/2008/1" 
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.w3.org/2005/Atom">
    <id/>
    <title/>
    <content/>
    <sdata:payload>
        <email xmlns="http://schemas.sage.com/crmErp/2008">
            <address>john.doe@email.com</address>
            <label>Bank Email</label>
        </email>
    </sdata:payload>
</entry>
```

But I keep getting back the following error:
`POST operation failed - Unable to locate the specified object 'Accounts50/GCRM/-/contacts/emails'`
Any idea where I am going wrong? 
Thanks in advance

**Comment by darroncockram** [comment]
The error message is correct as Accounts50/GCRM/-/contacts/emails (the path you are tying to POST to) is not a valid path to a resource.
Further to this, due to the limitations of the Sage 50 Accounts implementation you cannot add a new email address record to a contact. You can update an existing contact and include an email on this or you can create an entirely new contact with an email address, but you can't add a new email record.

That may sound convoluted but fortunately in practice it is as simple as including an email when adding/updating your contact. I've updated the 'Add Contact' code sample to include specifying an email address which should hopefully set you on the right track - https://github.com/darroncockram/sdatasamples/blob/master/AddContct/Program.cs

Hope that helps.

**Comment by PatrickWWork** [comment]
Thanks for the help, it is much appreciated. I believe I have been able to attach an email to a user while creating the user thanks to your example, however it looks like it has not saved the address correctly.
Here is the email snippet of the POST request:

```
...
        <contact xmlns="http://schemas.sage.com/crmErp/2008">
            <familyName>Doe</familyName>
            <firstName>John</firstName>
            <tradingAccount sdata:uuid="<TradingAccountId>" />
            <type>Customer Delivery Contact</type>
            <emails>
                <email>
                    <address>john.doe@email.com</address>
                </email>
            </emails>
        </contact>
...
```
Which returns a 201 created, but when I try and retrieve the newly created contacts email (using ```contacts(<ContactId>)/emails```) it returns the following:

```
"$resources": [
        {
            "active": true,
            "reference": "123",
            "reference2": null,
            "type": "Business",
            "address": "",
            "url": "",
            "primacyIndicator": false,
            "notes": null,
            "label": "Customer Delivery Email"
        }
    ]
```
As you can see, the address has not been fulfilled. Is my original request incorrect?

Thanks for the continued help.

**Comment by darroncockram** [comment]
Has an email actually been added if you check in the UI? Works OK for me if I run the sample code and retrieve the emails for the created user.

**Comment by PatrickWWork** [comment]
They are not showing up in the UI either. Strange.
![image](https://user-images.githubusercontent.com/86301179/127301691-36de630c-6b48-4c2b-b627-522b71752d2b.png)
(I tried creating an alternative contact with the name shown in the image).
I have also tried adding a postal address by adding
```
<postalAddresses>
   <postalAddress>
       <address1>100 Test Road</address1>
       <country>United Kingdom</country>
   </postalAddress>
</postalAddresses>
```
to the payload of this contact, which as you can see has also not been populated. 
I also attempted updating the above contact (`PUT /sdata/Accounts50/GCRM/-/contactCustomerDel(<CustId>)`) with the following payload:
```
<entry xmlns:sdata="http://schemas.sage.com/sdata/2008/1" 
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.w3.org/2005/Atom">
    <id/>
    <title/>
    <content/>
    <sdata:payload>
        <contact xmlns="http://schemas.sage.com/crmErp/2008">
            <fullName>UpdatedTest Tester</fullName>
            <emails>
                <email>
                    <address>newEmail@email.com</address>
                </email>
            </emails>
            <postalAddresses>
                <postalAddress>
                    <address1>100 Test Road</address1>
                    <country>United Kingdom</country>
                </postalAddress>
            </postalAddresses>
        </contact>
    </sdata:payload>
</entry>
```
which returns a 200 but it seems to not have updated, which I checked by getting the customer via the API and the GUI. It updates the name, but not the email or postal address.
Again, thank you for the continued assitance with this.

**Comment by darroncockram** [comment]
Hmmm. Not seeing an issue here. If I POST a new contact with an email and a postal address it gets created with all the expected data and I see this in both the UI and Sdata feeds. Here's the cut down, relevant payload capture from the demo code:

```<?xml version="1.0" encoding="utf-8"?>
<entry xmlns:atom="http://www.w3.org/2005/Atom" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cf="http://www.microsoft.com/schemas/rss/core/2005" xmlns="http://www.w3.org/2005/Atom" xmlns:http="http://schemas.sage.com/sdata/http/2008/1" xmlns:sdatasync="http://schemas.sage.com/sdata/sync/2008/1" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:sme="http://schemas.sage.com/sdata/sme/2007" xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <author />
  <sdata:payload>
    <contact xmlns="http://schemas.sage.com/crmErp/2008">
      <type>Customer Delivery Contact</type>
      <firstName>Test</firstName>
      <preferredName xsi:nil="true" />
      <familyName>Person</familyName>
      <postalAddresses>
        <postalAddress xmlns="http://schemas.sage.com/sc/2009">
          <address1>1 Demo Way</address1>
          <country>United Kingdom</country>
        </postalAddress>
      </postalAddresses>
      <phones xsi:nil="true" />
      <emails>
        <email xmlns="http://schemas.sage.com/sc/2009">
          <address>demo@sage.com</address>
        </email>
      </emails>
      <tradingAccount sdata:uuid="7b4186be-a213-47db-ac99-06e6f3a6f0ab" />
    </contact>
  </sdata:payload>
</entry>
```

If I subsequently update the details via a PUT request is similarly works OK and I see the changes in the UI and Sdata feeds. Here's the relevant data

```<?xml version="1.0" encoding="utf-8"?>
<entry xmlns:atom="http://www.w3.org/2005/Atom" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cf="http://www.microsoft.com/schemas/rss/core/2005" xmlns="http://www.w3.org/2005/Atom" xmlns:http="http://schemas.sage.com/sdata/http/2008/1" xmlns:sdatasync="http://schemas.sage.com/sdata/sync/2008/1" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:sme="http://schemas.sage.com/sdata/sme/2007" xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <author />
  <sdata:payload>
    <contact xmlns="http://schemas.sage.com/crmErp/2008">
      <type>Customer Delivery Contact</type>
      <fullName>Different Person</fullName>
      <postalAddresses>
        <postalAddress xmlns="http://schemas.sage.com/sc/2009">
          <address1>2 Demo Way</address1>
          <country>United Kingdom</country>
        </postalAddress>
      </postalAddresses>
      <phones xsi:nil="true" />
      <emails>
        <email xmlns="http://schemas.sage.com/sc/2009">
          <address>demo2@sage.com</address>
        </email>
      </emails>
      <tradingAccount sdata:uuid="7b4186be-a213-47db-ac99-06e6f3a6f0ab" />
    </contact>
  </sdata:payload>
</entry>
```

One thing that is worth noting that is different from your request is I am including the namespace for the email and address types as the are not in the same schema as the contact type. This may actually be why it is not working correctly for you.

**Comment by PatrickWWork** [comment]
Ah that was the key, the namespace needed to be entered. Both emails and postal addresses are now updating. Thank you for all of the help, it is much appreciated.
