### ISSUE TITLE
Unable to get subresource from trading account

### ISSUE THREAD

**Issue by PatrickWWork** [Sage/SData-2.0#172]
Hi

I am trying to get the postAdresses subresource when fetching a contact. My current request is `contacts(003...)?include=tradingAccount,tradingAccount/postalAddresses` which returns a null value for the postalAddresses in the trading account (which is successfully returned) field: 
```
...
"registeredAddress": null,
"postalAddresses": null,
"shippingAddresses": null,
...
```
But when I access it directly using the following request: `tradingAccountCustomer(698...)?include=postalAddresses` valid data is returned in the postalAddresses field.

Any idea where I am going wrong?

Thanks

**Comment by darroncockram** [comment]
Unfortunately the Sage 50 Accounts Sdata adapter does not currently support child resources in the include parameter I'm afraid.
