### ISSUE TITLE
Unable to assign a Project to a Service Invoice Line

### ISSUE THREAD

**Issue by BrendanRogers12** [Sage/SData-2.0#173]
I'm new to the sage50 development and trying to get the structure right for a request. Been working on Postman to build up the request but I'm have no success in linking a Project to a Service Invoice line item

- Sage Version Number: 27.2.664.0
- Endpoint of POST:  http://{{IpAddress}}:{{port}}/sdata/accounts50/GCRM/-/salesInvoices
- Aim: to create a Service Invoice with its line items linked to a Project

**Example 1 - In the Sales Invoice Line**

`
<entry xmlns:sdata=http://schemas.sage.com/sdata/2008/1 xmlns:xsi=http://www.w3.org/2001/XMLSchema-instance xmlns=http://www.w3.org/2005/Atom>
    <sdata:payload>
        <salesInvoice xmlns=http://schemas.sage.com/crmErp/2008>
            <salesInvoiceLines>
                <salesInvoiceLine xmlns=http://schemas.sage.com/crmErp/2008>
                    <project sdata:uuid="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx" />
                </salesInvoiceLine>
                <salesInvoice xmlns=http://schemas.sage.com/sc/2009 />
            </salesInvoiceLines>
        <type>Service Invoice</type>
        </salesInvoice>
    </sdata:payload>
</entry>
`

**Example 2 – at the sales Invoice level**

`
<entry xmlns:sdata=http://schemas.sage.com/sdata/2008/1 xmlns:xsi=http://www.w3.org/2001/XMLSchema-instance xmlns=http://www.w3.org/2005/Atom>
    <sdata:payload>
        <salesInvoice xmlns=http://schemas.sage.com/crmErp/2008>
            <salesInvoiceLines>
                <salesInvoiceLine xmlns=http://schemas.sage.com/crmErp/2008>
                </salesInvoiceLine>
                <salesInvoice xmlns=http://schemas.sage.com/sc/2009 />
            </salesInvoiceLines>
            <type>Service Invoice</type>
            <projects>
                <project sdata:uuid="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx" />
            </projects>
        </salesInvoice>
    </sdata:payload>
</entry>
`

**Comment by darroncockram** [comment]
Unfortunately setting the project is not currently supported when posting a sales invoice I'm afraid.
