### ISSUE TITLE
Project Create Structure to auto create a project reference

### ISSUE THREAD

**Issue by BrendanRogers12** [Sage/SData-2.0#174]
Trying to create a Project, but I seem to override my previously created reference and project name on every create. 
Also The project reference is never linked to the new project.  

Example:
`POST http://{{IP_Addresss:Port}}{/sdata/accounts50/GCRM/-/projects`
`<entry xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3.org/2005/Atom">
    <sdata:payload>
        <project xmlns="http://schemas.sage.com/crmErp/2008">
            <name>Project Name</name>
            <active>true</active>
            <reference>UNIQUE_PROJECT_REF</reference>
            <currentRevenueBudget>10000001</currentRevenueBudget>
            <status>ACTIVE</status>
            <tradingAccount>
                <tradingAccount sdata:uuid="xx-32-digit-xx" />
                <name>My Account Name</name>
                </tradingAccount>
        </project>
    </sdata:payload>
</entry>`

**Comment by darroncockram** [comment]
Support for projects in the Sage 50 Accounts Sdata adapter is pretty rudimentary currently and the only thing that is supported is to retrieve existing projects and include projects already associated with related resources. POST (creation) is not supported for the project resource kind I'm afraid. You can see this in the schema where sme:canPost is set to false:
![image](https://user-images.githubusercontent.com/1032296/144000064-6c58a941-787b-4eaa-94ed-1c94ce7efd36.png)
