### ISSUE TITLE
Sage 50 SData multiple companies

### ISSUE THREAD

**Issue by davidhendrickmb** [Sage/SData-2.0#175]
Hi there,
Sorry if this is a bit off topic but I was wondering if Sage 50 SData can be enabled for multiple companies and if so, how to do it?
Thanks,
David

**Comment by asterix187** [comment]
Yes, within the URL of the call you include the ID of the Sage 50 dataset you require. The default is /-/ but if you go to the Sdata settings within Sage 50 you will see the URL's you need to use to query each data set.

**Comment by davidhendrickmb** [comment]
Thanks @asterix187 .
I only see one company in there and was wondering how I can add another?

**Comment by darroncockram** [comment]
You would need more added in the main Accounts UI an then they will show up in Sdata. Bear in mind that by default Sdata will not work with companies in a network location and only 'local' companies will be exposed.

**Comment by davidhendrickmb** [comment]
Thanks @darroncockram .
I'm not entirely sure what you mean by local companies? We have Sage 50 installed on a server and are accessing data via the SData feed at present.

**Comment by asterix187** [comment]
Do you have a sage 50 client on the server the data is stored on. The data should be in the same server the client you are using to access sage 50 is on. If not you will be getting folder security issues which is why you can see the other companies via sdata. One fix, if the data is on another computer, it to run the sdata service as a user who has been given rights to the folder the data is stored in.
________________________________

**Comment by mtaylor678** [comment]
do you know if it's possible to use the demo data that's provided with the default install of sage 50? It's not listed in the GCRM section. There's no way to export it to a new company (no export option in File). Would be a headache to create my own import fake data csv's.

**Comment by darroncockram** [comment]
Only 'live' datasets are accessible via Sdata so demo and practice data will not be shown I'm afraid.

**Comment by asterix187** [comment]
That said, you can "re-add" the demo data as a full dataset and it then becomes available. But this should only be done on a demo instance of Sage 50.
