### ISSUE TITLE
C# plugin

### ISSUE THREAD

**Issue by stquinn2015** [Sage/SData-2.0#18]
Hi I am looking for the vs2010/c#plugin for sdata as shown in some of youtube videos has its download location changed?

**Comment by darroncockram** [comment]
Yes, you can find the download for the plugin here: https://github.com/Sage/sdata-downloads/blob/master/SageSDataToolsforVisualStudio.zip

**Comment by stquinn2015** [comment]
Do you have any specific example of how to post in a sales invoice using c# please?

**Comment by darroncockram** [comment]
Here's some code I had kicking around that should work (assuming you have Sag 50 Accounts and have used the Visual Studio plugin to generate the code from the schema),

using System;
using System.Collections.Generic;
using System.Text;
using Sage.Common.Syndication;
using Sage.crmErp.x2008.Feeds;
using Sage.Integration.Client;

namespace CreateSalesInvoice
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create a new instance of a salesInvoice
			salesInvoiceFeedEntry salesInvoice = new salesInvoiceFeedEntry();

            // Find a customer to associate with the new sales invoice
            salesInvoice.tradingAccount = GetCustomer();

            if (salesInvoice.tradingAccount == null)
            {
                // No customer record means we can go no further
                Console.WriteLine("Unable to find a customer record");
                Console.ReadKey(true);
                return;
            }

            // Lookup a commodity to use on the new sales invoice
            commodityFeedEntry commodity = GetCommodity();
            if(commodity == null)
            {
				// No commodity record means we go no further
                Console.WriteLine("Unable to find a commodity record");
                Console.ReadKey(true);
                return;
            }
			commodityFeedEntry commodityReference = new commodityFeedEntry();
			commodityReference.UUID = commodity.UUID;

			// Lookup a commodity to use on the new sales invoice
			taxCodeFeedEntry taxCode = GetTaxCode();
			if (taxCode == null)
			{
				// No record means we go no further
				Console.WriteLine("Unable to find a tax code record");
				Console.ReadKey(true);
				return;
			}

			// Example of creating a historical invoice
			//salesInvoice.date = salesInvoice.taxDate = DateTime.UtcNow.AddDays(-2);

            // NOTE: This example omits the use of tax code for brevity.
            // Not specifying tax codes means that appropriate defaults will be used automatically.
            // However it is strongly recommended that tax codes are explicitly set to ensure expected results
			taxCodeFeedEntry taxReference = new taxCodeFeedEntry();
			taxReference.UUID = taxCode.UUID;

			salesInvoice.taxCodes = new taxCodeFeed();
			salesInvoice.taxCodes.Entries.Add(taxReference);

			salesInvoice.carrierTotalPrice = 100;
			salesInvoice.carrierTaxPrice = 20;
			salesInvoice.carrierNetPrice = 80;

            // Create a new sale invoice line using the commodity we just looked up
            salesInvoiceLineFeedEntry orderLine = new salesInvoiceLineFeedEntry();
            orderLine.type = "Standard";
            orderLine.text = commodity.description;
			orderLine.commodity = commodityReference;
            orderLine.quantity = 2;
            orderLine.netTotal = 50;
            orderLine.taxTotal = 10;
            orderLine.grossTotal = 60;
			orderLine.taxCodes = new taxCodeFeed();
			orderLine.taxCodes.Entries.Add(taxReference);

            // Create another invoice line this time as free text
            salesInvoiceLineFeedEntry freetextOrderLine = new salesInvoiceLineFeedEntry();
            freetextOrderLine.type = "Free Text"; // Equivalent to S1 stock code
            freetextOrderLine.text = "An example product";
            freetextOrderLine.quantity = 5;
            freetextOrderLine.netTotal = 100;
            freetextOrderLine.taxTotal = 20;
            freetextOrderLine.grossTotal = 120;
			freetextOrderLine.taxCodes = new taxCodeFeed();
			freetextOrderLine.taxCodes.Entries.Add(taxReference);

			// Create a 3rd invoice line this time as a message
			salesInvoiceLineFeedEntry messageOrderLine = new salesInvoiceLineFeedEntry();
			messageOrderLine.type = "Commentary"; // Equivalent to S1 stock code
			messageOrderLine.text = "A message line created via Sdata";


            // Associate the lines with our invoice
            salesInvoice.salesInvoiceLines = new salesInvoiceLineFeed();
            salesInvoice.salesInvoiceLines.Entries.Add(orderLine);
            salesInvoice.salesInvoiceLines.Entries.Add(freetextOrderLine);
			salesInvoice.salesInvoiceLines.Entries.Add(messageOrderLine);

            // Now we have constructed our new invoice we can submit it using the HTTP POST verb  
            Sage.Common.Syndication.SDataUri salesInvoiceUri = new Sage.Common.Syndication.SDataUri();
            salesInvoiceUri.BuildLocalPath("Accounts50", "GCRM", "-", "salesInvoices");

            SDataRequest invoiceRequest = new SDataRequest(salesInvoiceUri.Uri, salesInvoice, Sage.Integration.Messaging.Model.RequestVerb.POST);
            invoiceRequest.Username = "MANAGER";
            invoiceRequest.Password = "";

            // IF successful the POST operation will provide us with a the newly created sales invoice
            salesInvoiceFeedEntry savedSalesInvoice = new salesInvoiceFeedEntry();
            invoiceRequest.RequestFeedEntry<salesInvoiceFeedEntry>(savedSalesInvoice);

            if (invoiceRequest.IsStatusValidForVerb)
            {
                Console.WriteLine(string.Format("Successfully created sales invoice {0}", savedSalesInvoice.reference));
            }
            else
            {
                // There was a problem
                Console.WriteLine("Create failed. Response was {0}", invoiceRequest.HttpStatusCode.ToString());
				if (invoiceRequest.Diagnoses != null)
				{
					foreach (Diagnosis diagnosis in invoiceRequest.Diagnoses)
						Console.WriteLine(diagnosis.Message);
				}
            }

            Console.ReadKey(true);
        }

        static tradingAccountFeedEntry GetCustomer()
        {
            // Look up the first customer record 
            Sage.Common.Syndication.SDataUri accountUri = new Sage.Common.Syndication.SDataUri();
            accountUri.BuildLocalPath("Accounts50", "GCRM", "-", "tradingAccounts");
            accountUri.Where = "customerSupplierFlag eq 'Customer'";
            accountUri.Count = 1;

            SDataRequest accountRequest = new SDataRequest(accountUri.Uri);
			accountRequest.AllowPromptForCredentials = false;
            accountRequest.Username = "MANAGER";
            accountRequest.Password = "";

            tradingAccountFeed accounts = new tradingAccountFeed();
            accountRequest.RequestFeed<tradingAccountFeedEntry>(accounts);

            // If we found a customer record return it
            if (accountRequest.IsStatusValidForVerb && accounts.Entries != null && accounts.Entries.Count > 0)
                return accounts.Entries[0];
            else
            {
                // There was a problem
                Console.WriteLine("Account lookup failed. Response was {0}", accountRequest.HttpStatusCode.ToString());
				if (accountRequest.Diagnoses != null)
				{
					foreach(Diagnosis diagnosis in accountRequest.Diagnoses)
						Console.WriteLine(diagnosis.Message);
				}

                return null;
            }
        }

        static commodityFeedEntry GetCommodity()
        {
            // Look up the first commodity (product) record 
            Sage.Common.Syndication.SDataUri commodityUri = new Sage.Common.Syndication.SDataUri();
            commodityUri.BuildLocalPath("Accounts50", "GCRM", "-", "commodities");
            commodityUri.Count = 1;

            SDataRequest commodityRequest = new SDataRequest(commodityUri.Uri);
            commodityRequest.Username = "MANAGER";
            commodityRequest.Password = "";

            commodityFeed commodities = new commodityFeed();
            commodityRequest.RequestFeed<commodityFeedEntry>(commodities);

            // If we found a record return it
            if (commodityRequest.IsStatusValidForVerb && commodities.Entries != null && commodities.Entries.Count > 0)
                return commodities.Entries[0];
            else
            {
                // There was a problem
                Console.WriteLine("Commodity lookup failed. Response was {0}", commodityRequest.HttpStatusCode.ToString());
				if (commodityRequest.Diagnoses != null)
				{
					foreach (Diagnosis diagnosis in commodityRequest.Diagnoses)
						Console.WriteLine(diagnosis.Message);
				}

                return null;
            }
        }

		static taxCodeFeedEntry GetTaxCode()
		{
			// Look up the tax code record 
			Sage.Common.Syndication.SDataUri taxCodeUri = new Sage.Common.Syndication.SDataUri();
			taxCodeUri.BuildLocalPath("Accounts50", "GCRM", "-", "taxCodes");
			taxCodeUri.Where = "reference eq 'T1'";
			
			SDataRequest taxcodeRequest = new SDataRequest(taxCodeUri.Uri);
			taxcodeRequest.Username = "MANAGER";
			taxcodeRequest.Password = "";

			taxCodeFeed taxcodes = new taxCodeFeed();
			taxcodeRequest.RequestFeed<taxCodeFeedEntry>(taxcodes);

			// If we found a customer record return it
			if (taxcodeRequest.IsStatusValidForVerb && taxcodes.Entries != null && taxcodes.Entries.Count > 0)
				return taxcodes.Entries[0];
			else
			{
				// There was a problem
				Console.WriteLine("Tax code lookup failed. Response was {0}", taxcodeRequest.HttpStatusCode.ToString());
				if (taxcodeRequest.Diagnoses != null)
				{
					foreach (Diagnosis diagnosis in taxcodeRequest.Diagnoses)
						Console.WriteLine(diagnosis.Message);
				}

				return null;
			}
		}
    }
}

**Comment by stquinn2015** [comment]
Sorry to be a pain Darron

I am getting the following when i run the code can you help please :)

Create failed. Response was InternalServerError
POST operation failed - Cannot locate the mapping for the specified ID

   at Sage.Integration.Accounts50.SDOAdapter.IdentityMappingManager.GetIdentityM
apping(Guid id)
   at Sage.Integration.Accounts50.SDOAdapter.Feeds.SDOIspPost.UpdateHeaderFields
[T](T entry, Guid tradingAccountUUID)
   at Sage.Integration.Accounts50.SDOAdapter.Feeds.salesInvoiceFeedEntry.Add(IRe
quest request)
   at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.OnPostRequest(IReq
uest request)
   at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.PostRequest(IReque
st request)
   at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.PostRequest(IRequ
est request) (-1)

**Comment by darroncockram** [comment]
My guess is that it's the customer reference that it's falling over. Are you running the code exactly as above or have you modified it in any way? Also does the dataset you are running this against have at least one customer in it?

**Comment by stquinn2015** [comment]
Running the code exactly as above, yes the data set has a customer in it. I will investigate further

**Comment by darroncockram** [comment]
If you capture the XML that is being POSTed and copy it here I can see if I can replicate the issue.

**Comment by stquinn2015** [comment]
How would you go about this?

**Comment by darroncockram** [comment]
I would just use something like Fiddler http://www.telerik.com/download/fiddler. A very handy tool you're doing work on Sdata (or in fact any web work).

**Comment by stquinn2015** [comment]
Thanks Darron brillant tool thanks for the recommendation please see xml below.


<?xml version="1.0" encoding="utf-8"?>
<entry xmlns:atom="http://www.w3.org/2005/Atom" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cf="http://www.microsoft.com/schemas/rss/core/2005" xmlns="http://www.w3.org/2005/Atom" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:sme="http://schemas.sage.com/sdata/sme/2007" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:http="http://schemas.sage.com/sdata/http/2008/1" xmlns:sdatasync="http://schemas.sage.com/sdata/sync/2008/1">
  <author />
  <sdata:payload>
    <salesInvoice xmlns="http://schemas.sage.com/crmErp/2008">
      <active xsi:nil="true" />
      <reference xsi:nil="true" />
      <reference2 xsi:nil="true" />
      <status xsi:nil="true" />
      <allocationStatus xsi:nil="true" />
      <deliveryStatus xsi:nil="true" />
      <statusFlag xsi:nil="true" />
      <statusFlagText xsi:nil="true" />
      <type xsi:nil="true" />
      <tradingAccount sdata:url="http://sean-pc:5493/sdata/Accounts50/GCRM/{709ADC1A-DD2A-4659-9FCA-E045A3E02F9E}/tradingAccountCustomer(5a6e063a-29b9-4a8e-9814-26330fc1af0f)?format=atomentry">
        <active>true</active>
        <customerSupplierFlag>Customer</customerSupplierFlag>
        <companyPersonFlag>Company</companyPersonFlag>
        <invoiceTradingAccount xsi:nil="true" />
        <openedDate>2015-02-17</openedDate>
        <reference>10000000</reference>
        <reference2 xsi:nil="true" />
        <status>Open</status>
        <name>test</name>
        <shortName xsi:nil="true" />
        <type>Unknown</type>
        <registeredAddress xsi:nil="true" />
        <postalAddresses xsi:nil="true" />
        <shippingAddresses xsi:nil="true" />
        <billingAddresses xsi:nil="true" />
        <phones xsi:nil="true" />
        <emails xsi:nil="true" />
        <website />
        <contacts xsi:nil="true" />
        <deliveryContact xsi:nil="true" />
        <salesPersons xsi:nil="true" />
        <deliveryMethod xsi:nil="true" />
        <deliveryRule>true</deliveryRule>
        <currency>GBP</currency>
        <taxCode xsi:nil="true" />
        <taxReference />
        <taxationCountry>GB</taxationCountry>
        <useTaxInclusivePrices xsi:nil="true" />
        <financeBalance>12.00</financeBalance>
        <financeLimit>0.00</financeLimit>
        <financeBalanceDate xsi:nil="true" />
        <financeStatusFlag>false</financeStatusFlag>
        <financeStatusText>Open</financeStatusText>
        <settlementDiscountType>Percent</settlementDiscountType>
        <settlementDiscountAmount xsi:nil="true" />
        <settlementDiscountPercent>0.00</settlementDiscountPercent>
        <settlementDiscountTerms>0</settlementDiscountTerms>
        <settlementDiscountTermsCommencement xsi:nil="true" />
        <settlementDiscountIncludedInTotal>true</settlementDiscountIncludedInTotal>
        <paymentTerms>0</paymentTerms>
        <paymentTermsCommencement xsi:nil="true" />
        <orderDiscountType xsi:nil="true" />
        <orderDiscountAmount xsi:nil="true" />
        <orderDiscountPercent xsi:nil="true" />
        <orderText1 xsi:nil="true" />
        <orderText2 xsi:nil="true" />
        <orderLineDiscountType xsi:nil="true" />
        <orderLineDiscountAmount xsi:nil="true" />
        <orderLineDiscountPercent>0.00</orderLineDiscountPercent>
        <orderLineText1 xsi:nil="true" />
        <orderLineText2 xsi:nil="true" />
        <invoiceDiscountType xsi:nil="true" />
        <invoiceDiscountAmount xsi:nil="true" />
        <invoiceDiscountPercent>0.00</invoiceDiscountPercent>
        <invoiceText1 xsi:nil="true" />
        <invoiceText2 xsi:nil="true" />
        <bankAccounts xsi:nil="true" />
        <tenderType xsi:nil="true" />
        <defaultFulfillmentLocation xsi:nil="true" />
        <pricelists xsi:nil="true" />
        <pricingOverride xsi:nil="true" />
        <accountingType xsi:nil="true" />
        <financialAccounts xsi:nil="true" />
        <primacyIndicator>true</primacyIndicator>
        <opportunities xsi:nil="true" />
        <salesQuotations xsi:nil="true" />
        <salesOrders xsi:nil="true" />
        <salesOrderDeliveries xsi:nil="true" />
        <salesInvoices xsi:nil="true" />
        <salesCredits xsi:nil="true" />
        <purchaseOrders xsi:nil="true" />
        <purchaseOrderDeliveries xsi:nil="true" />
        <receipts xsi:nil="true" />
        <interactions xsi:nil="true" />
        <projects xsi:nil="true" />
      </tradingAccount>
      <customerReference xsi:nil="true" />
      <opportunity xsi:nil="true" />
      <pricelist xsi:nil="true" />
      <copyFlag xsi:nil="true" />
      <date xsi:nil="true" />
      <time xsi:nil="true" />
      <taxDate xsi:nil="true" />
      <taxCodes>
        <taxCode>
          <notes xsi:nil="true" />
        </taxCode>
      </taxCodes>
      <postalAddresses xsi:nil="true" />
      <deliveryMethod xsi:nil="true" />
      <deliveryTerms xsi:nil="true" />
      <deliveryRule xsi:nil="true" />
      <deliveryDate xsi:nil="true" />
      <carrierCompany xsi:nil="true" />
      <carrierTradingAccount xsi:nil="true" />
      <carrierNetPrice>80.00</carrierNetPrice>
      <carrierTaxPrice>20.00</carrierTaxPrice>
      <carrierTotalPrice>100.00</carrierTotalPrice>
      <carrierSalesInvoice xsi:nil="true" />
      <carrierTaxCodes xsi:nil="true" />
      <carrierReference xsi:nil="true" />
      <currency xsi:nil="true" />
      <operatingCompanyCurrency xsi:nil="true" />
      <operatingCompanyCurrencyExchangeRate xsi:nil="true" />
      <operatingCompanyCurrencyExchangeRateOperator xsi:nil="true" />
      <operatingCompanyCurrencyExchangeRateDate xsi:nil="true" />
      <customerTradingAccountCurrency xsi:nil="true" />
      <customerTradingAccountCurrencyExchangeRate xsi:nil="true" />
      <customerTradingAccountCurrencyExchangeRateOperator xsi:nil="true" />
      <customerTradingAccountCurrencyExchangeRateDate xsi:nil="true" />
      <buyerContact xsi:nil="true" />
      <salespersons xsi:nil="true" />
      <salesInvoiceLines>
        <salesInvoiceLine>
          <originatorDocumentLine xsi:nil="true" />
          <active xsi:nil="true" />
          <reference xsi:nil="true" />
          <reference2 xsi:nil="true" />
          <status xsi:nil="true" />
          <type>Standard</type>
          <number xsi:nil="true" />
          <commodity>
            <commodityGroup xsi:nil="true" />
            <commodityIdentifiers xsi:nil="true" />
            <unitOfMeasure xsi:nil="true" />
            <buyingUnitOfMeasure xsi:nil="true" />
            <sellingUnitOfMeasure xsi:nil="true" />
            <packingUnitOfMeasure xsi:nil="true" />
            <supplierTradingAccount xsi:nil="true" />
            <taxCodes xsi:nil="true" />
            <financialAccounts xsi:nil="true" />
            <replacement xsi:nil="true" />
            <associatedChildCommodities xsi:nil="true" />
            <associatedParentCommodity xsi:nil="true" />
            <interactions xsi:nil="true" />
            <opportunities xsi:nil="true" />
            <salesQuotationLines xsi:nil="true" />
            <salesOrderLines xsi:nil="true" />
            <salesOrderDeliveryLines xsi:nil="true" />
            <salesInvoiceLines xsi:nil="true" />
            <salesCreditLines xsi:nil="true" />
            <purchaseOrderLines xsi:nil="true" />
            <purchaseOrderDeliveryLines xsi:nil="true" />
            <pricelists xsi:nil="true" />
            <prices xsi:nil="true" />
          </commodity>
          <text xsi:nil="true" />
          <deliveryTerms xsi:nil="true" />
          <deliveryDate xsi:nil="true" />
          <carrierTradingAccount xsi:nil="true" />
          <carrierNetPrice xsi:nil="true" />
          <carrierTaxPrice xsi:nil="true" />
          <carrierTotalPrice xsi:nil="true" />
          <carrierSalesInvoiceLine xsi:nil="true" />
          <carrierTaxCodes xsi:nil="true" />
          <carrierReference xsi:nil="true" />
          <unitOfMeasure xsi:nil="true" />
          <quantity>2.00</quantity>
          <initialPrice xsi:nil="true" />
          <pricelist xsi:nil="true" />
          <settlementDiscountType xsi:nil="true" />
          <settlementDiscountAmount xsi:nil="true" />
          <settlementDiscountPercent xsi:nil="true" />
          <settlementDiscountTerms xsi:nil="true" />
          <invoiceLineDiscountType xsi:nil="true" />
          <invoiceLineDiscountAmount xsi:nil="true" />
          <invoiceLineDiscountPercent xsi:nil="true" />
          <invoiceLineSubtotalDiscountType xsi:nil="true" />
          <invoiceLineSubtotalDiscountAmount xsi:nil="true" />
          <invoiceLineSubtotalDiscountPercent xsi:nil="true" />
          <actualPrice xsi:nil="true" />
          <netTotal>50.00</netTotal>
          <chargesTotal xsi:nil="true" />
          <discountTotal xsi:nil="true" />
          <fOBPoint xsi:nil="true" />
          <taxCodes>
            <taxCode>
              <notes xsi:nil="true" />
            </taxCode>
          </taxCodes>
          <priceTax xsi:nil="true" />
          <taxTotal>10.00</taxTotal>
          <grossTotal>60.00</grossTotal>
          <costTotal xsi:nil="true" />
          <profitTotal xsi:nil="true" />
          <project xsi:nil="true" />
          <salesOrderDeliveryLines xsi:nil="true" />
          <receipts xsi:nil="true" />
          <financialAccounts xsi:nil="true" />
          <notes xsi:nil="true" />
        </salesInvoiceLine>
        <salesInvoiceLine>
          <originatorDocumentLine xsi:nil="true" />
          <active xsi:nil="true" />
          <reference xsi:nil="true" />
          <reference2 xsi:nil="true" />
          <status xsi:nil="true" />
          <type>Free Text</type>
          <number xsi:nil="true" />
          <commodity xsi:nil="true" />
          <text>An example product</text>
          <deliveryTerms xsi:nil="true" />
          <deliveryDate xsi:nil="true" />
          <carrierTradingAccount xsi:nil="true" />
          <carrierNetPrice xsi:nil="true" />
          <carrierTaxPrice xsi:nil="true" />
          <carrierTotalPrice xsi:nil="true" />
          <carrierSalesInvoiceLine xsi:nil="true" />
          <carrierTaxCodes xsi:nil="true" />
          <carrierReference xsi:nil="true" />
          <unitOfMeasure xsi:nil="true" />
          <quantity>5.00</quantity>
          <initialPrice xsi:nil="true" />
          <pricelist xsi:nil="true" />
          <settlementDiscountType xsi:nil="true" />
          <settlementDiscountAmount xsi:nil="true" />
          <settlementDiscountPercent xsi:nil="true" />
          <settlementDiscountTerms xsi:nil="true" />
          <invoiceLineDiscountType xsi:nil="true" />
          <invoiceLineDiscountAmount xsi:nil="true" />
          <invoiceLineDiscountPercent xsi:nil="true" />
          <invoiceLineSubtotalDiscountType xsi:nil="true" />
          <invoiceLineSubtotalDiscountAmount xsi:nil="true" />
          <invoiceLineSubtotalDiscountPercent xsi:nil="true" />
          <actualPrice xsi:nil="true" />
          <netTotal>100.00</netTotal>
          <chargesTotal xsi:nil="true" />
          <discountTotal xsi:nil="true" />
          <fOBPoint xsi:nil="true" />
          <taxCodes>
            <taxCode>
              <notes xsi:nil="true" />
            </taxCode>
          </taxCodes>
          <priceTax xsi:nil="true" />
          <taxTotal>20.00</taxTotal>
          <grossTotal>120.00</grossTotal>
          <costTotal xsi:nil="true" />
          <profitTotal xsi:nil="true" />
          <project xsi:nil="true" />
          <salesOrderDeliveryLines xsi:nil="true" />
          <receipts xsi:nil="true" />
          <financialAccounts xsi:nil="true" />
          <notes xsi:nil="true" />
        </salesInvoiceLine>
        <salesInvoiceLine>
          <originatorDocumentLine xsi:nil="true" />
          <active xsi:nil="true" />
          <reference xsi:nil="true" />
          <reference2 xsi:nil="true" />
          <status xsi:nil="true" />
          <type>Commentary</type>
          <number xsi:nil="true" />
          <commodity xsi:nil="true" />
          <text>A message line created via Sdata</text>
          <deliveryTerms xsi:nil="true" />
          <deliveryDate xsi:nil="true" />
          <carrierTradingAccount xsi:nil="true" />
          <carrierNetPrice xsi:nil="true" />
          <carrierTaxPrice xsi:nil="true" />
          <carrierTotalPrice xsi:nil="true" />
          <carrierSalesInvoiceLine xsi:nil="true" />
          <carrierTaxCodes xsi:nil="true" />
          <carrierReference xsi:nil="true" />
          <unitOfMeasure xsi:nil="true" />
          <quantity xsi:nil="true" />
          <initialPrice xsi:nil="true" />
          <pricelist xsi:nil="true" />
          <settlementDiscountType xsi:nil="true" />
          <settlementDiscountAmount xsi:nil="true" />
          <settlementDiscountPercent xsi:nil="true" />
          <settlementDiscountTerms xsi:nil="true" />
          <invoiceLineDiscountType xsi:nil="true" />
          <invoiceLineDiscountAmount xsi:nil="true" />
          <invoiceLineDiscountPercent xsi:nil="true" />
          <invoiceLineSubtotalDiscountType xsi:nil="true" />
          <invoiceLineSubtotalDiscountAmount xsi:nil="true" />
          <invoiceLineSubtotalDiscountPercent xsi:nil="true" />
          <actualPrice xsi:nil="true" />
          <netTotal xsi:nil="true" />
          <chargesTotal xsi:nil="true" />
          <discountTotal xsi:nil="true" />
          <fOBPoint xsi:nil="true" />
          <taxCodes xsi:nil="true" />
          <priceTax xsi:nil="true" />
          <taxTotal xsi:nil="true" />
          <grossTotal xsi:nil="true" />
          <costTotal xsi:nil="true" />
          <profitTotal xsi:nil="true" />
          <project xsi:nil="true" />
          <salesOrderDeliveryLines xsi:nil="true" />
          <receipts xsi:nil="true" />
          <financialAccounts xsi:nil="true" />
          <notes xsi:nil="true" />
        </salesInvoiceLine>
      </salesInvoiceLines>
      <lineCount xsi:nil="true" />
      <originatorDocument xsi:nil="true" />
      <salesOrderDeliveries xsi:nil="true" />
      <receipts xsi:nil="true" />
      <contract xsi:nil="true" />
      <settlementDiscountType xsi:nil="true" />
      <settlementDiscountAmount xsi:nil="true" />
      <settlementDiscountPercent xsi:nil="true" />
      <settlementDiscountTerms xsi:nil="true" />
      <settlementDiscountIncludedInTotal xsi:nil="true" />
      <invoiceDiscountType xsi:nil="true" />
      <invoiceDiscountAmount xsi:nil="true" />
      <invoiceDiscountPercent xsi:nil="true" />
      <invoiceAdditionalDiscount1Type xsi:nil="true" />
      <invoiceAdditionalDiscount1Amount xsi:nil="true" />
      <invoiceAdditionalDiscount1Percent xsi:nil="true" />
      <invoiceAdditionalDiscount2 xsi:nil="true" />
      <invoiceAdditionalDiscount2Amount xsi:nil="true" />
      <invoiceAdditionalDiscount2Percent xsi:nil="true" />
      <netTotal xsi:nil="true" />
      <discountTotal xsi:nil="true" />
      <chargesTotal xsi:nil="true" />
      <taxTotal xsi:nil="true" />
      <grossTotal xsi:nil="true" />
      <costTotal xsi:nil="true" />
      <profitTotal xsi:nil="true" />
      <text1 xsi:nil="true" />
      <text2 xsi:nil="true" />
      <projects xsi:nil="true" />
      <financialAccounts xsi:nil="true" />
      <interactions xsi:nil="true" />
      <user xsi:nil="true" />
      <notes xsi:nil="true" />
      <CustomerId>0001-01-01T00:00:00.000+00:00</CustomerId>
      <paymentDue xsi:nil="true" />
    </salesInvoice>
  </sdata:payload>
</entry>

**Comment by stquinn2015** [comment]
Not sure if u can see the xml please attached dropbox link with xml in it

https://www.dropbox.com/s/u63firbp8ofdrer/xml.txt?dl=0

**Comment by darroncockram** [comment]
I can see a couple of issues in that XML that could be the source of the error you are getting.

Firstly the commodity on the first salesInvoiceLine is empty. Do you have any products defined in the dataset you are connecting to? A commodity is not always a necessity to create a salesInvoice but the demo code assumes that there will be at least one. Simplest thing here would be to create a product record in your dataset.

Secondly the taxCode is empty in all cases. This is a little more unusual as you should always have taxCodes, even in a completely new dataset. However the demo code has another assumption, that the T1 tax code will be available, but It's possible that you are basing your dataset on a non-default schema where it might not be. In which case simply change the reference in the GetTaxCode method to whatever tax code reference you are using for standard VAT in your dataset.

Hope that helps

**Comment by stquinn2015** [comment]
There is a taxcode and product in the system, when I stepped through the code the two functions GetCommodity() and GetTaxCode() did return results, however these results where not passed through to CommodityFeedEntry() and TaxCodeEntry()?. Am I missing something Darron

**Comment by stquinn2015** [comment]
If you can provide a working code example & dataset I can work from there

**Comment by darroncockram** [comment]
>If you can provide a working code example & dataset I can work from there

I'm just using the demo data with the above code.
>GetCommodity() and GetTaxCode() did return results, however these results where not passed through to CommodityFeedEntry() and TaxCodeEntry()

What version of Accounts are you using?

**Comment by stquinn2015** [comment]
Hi Darron

I am using  sage 50 accounts version  

version 21.4.7.159
sbd desktop version 12.1.369.0

**Comment by darroncockram** [comment]
>version 21.4.7.159
>sbd desktop version 12.1.369.0

Same here so it's not that.

If you look at the tradingAccountFeedEntry and taxCodeFeedEntry classes in the auto generated code do they have an SMEResource attribute. If so what parameters does it have set?

**Comment by stquinn2015** [comment]
In TradeAccountFeedEntry

[SMEResource(CanGet=true, CanPost=true, CanPut=true, CanDelete=true, PluralName="tradingAccounts", HasUuid=true)]

in TaxCodeEntry

[SMEResource(CanGet=true, CanPut=true, PluralName="notes", HasUuid=true)]

**Comment by stquinn2015** [comment]
Hi Darron

I have uninstalled Sage Accounts and sage development sdks and tools and re installed them and now its working. Just one of those strange unexplainable things I guess

**Comment by darroncockram** [comment]
Very strange indeed. Glad to hear it's working now though.

**Comment by stquinn2015** [comment]
Thank you for your help thou Darron much appreciated

**Comment by TawTeuf** [comment]
hello everyone,
I am new to sage 50 and following Darron  example for inputting invoices through C# plugin, i have been able to do so.
May I get some help on how to input receipt using receiptfeedentry 
Thanks.

**Comment by darroncockram** [comment]
Unfortunately the receipts feed is read only in the Sage 50 Accounts Sdata adapter.

**Comment by TawTeuf** [comment]
Hello Darron ,

Thanks for your prompt answer.
Is there anyway to send a customer receipt to  sage 50 

Thanks

**Comment by asterix187** [comment]
Hi, we got around this by writing an SDO wrapper web service that extends the sData service but still provides access over the web. The issue is that you will need to use SDO so have SDO keys etc.

**Comment by darroncockram** [comment]
Yeah, SDO would be the only option currently I'm afraid.

**Comment by TawTeuf** [comment]
Hello everyone,
I have follow Darron C# coding and everything works fine. I just need to add salesperson/department in my invoice which is found in the footer details tab.
Can I get some help for that.
Thanks and regards

**Comment by darroncockram** [comment]
> I just need to add salesperson/department in my invoice which is found in the footer details tab.

Neither of those are supported by the Sage 50 Accounts Sdata adapter I'm afraid.

**Comment by JohnDederer** [comment]
Is there a plugin for VS2013 ?

**Comment by darroncockram** [comment]
> Is there a plugin for VS2013 ?
Afraid not. As a workaround I tend to simply run the code generation in VS2012 and then open the solution in a newer version.

**Comment by JohnDederer** [comment]
@darroncockram I need to consume a service operation. However I cannot find any useful documentation on how to achieve this. I already downloaded the Visual Studio plugin and it recognized the necessary schema. However I am not able to make a POST request with it. I added values to the Serviceoperation feedEntry.Schema request Object. However it seems like nothing happens. It wont Create. Can you point me to a tutorial or documentation in which I can see how to use those FeedEntries or how I can use the C# SDataClient library and communicate from there with service operations ?

The Visual Studio plugin works with FeedEntries and the C# Library with AtomEntries. How do I need to use them properly ?

Thanks a lot in advance!

**Comment by darroncockram** [comment]
>  I added values to the Serviceoperation feedEntry.Schema request Object. However it seems like nothing happens. It wont Create.

> Can you point me to a tutorial or documentation in which I can see how to use those FeedEntries or how I can use the C# SDataClient library and communicate from there with service operations ?

I created this video a while back that may help: https://www.youtube.com/watch?v=-19BagI2bOE

Just setting the properties will have no effect other than on the in memory object. You would need to POST the feed entry to the appropriate service endpoint.

> The Visual Studio plugin works with FeedEntries and the C# Library with AtomEntries. How do I need to use them properly ?

The generated *Feed and *FeedEntry classes from the Visual Studio plugin should be all you need. The SIF abstracts you away from the Atom format so all you need to do deal with the objects such as tradingAcountFeedEntry, commodityFeedEntry, etc. The above video is probably the best place to start as this should hopefully provide a reasonable insight in to how to get started with it.

**Comment by mbharanidharan88** [comment]
> > I added values to the Serviceoperation feedEntry.Schema request Object. However it seems like nothing happens. It wont Create.
> 
> > Can you point me to a tutorial or documentation in which I can see how to use those FeedEntries or how I can use the C# SDataClient library and communicate from there with service operations ?
> 
> I created this video a while back that may help: https://www.youtube.com/watch?v=-19BagI2bOE
> 
> Just setting the properties will have no effect other than on the in memory object. You would need to POST the feed entry to the appropriate service endpoint.
> 
> > The Visual Studio plugin works with FeedEntries and the C# Library with AtomEntries. How do I need to use them properly ?
> 
> The generated *Feed and *FeedEntry classes from the Visual Studio plugin should be all you need. The SIF abstracts you away from the Atom format so all you need to do deal with the objects such as tradingAcountFeedEntry, commodityFeedEntry, etc. The above video is probably the best place to start as this should hopefully provide a reasonable insight in to how to get started with things.

Hi,

I followed this video to integrate SAGE 50 using SIF. I am fetching the trading accounts and want to include registeredAddress property with it. Could you please help me with that?

   ```
tradingAccountFeed accounts = new tradingAccountFeed();
   request.RequestFeed<tradingAccountFeedEntry>(accounts);
   request.Send();
```
