### ISSUE TITLE
Sage account 50 v27 crush

### ISSUE THREAD

**Issue by shaopengwu** [Sage/SData-2.0#180]
I use SData to help import sales orders from other data formats. 

But the Sage is always crushed. The server configured as Dell power edge T640, single CPU & 64GB memory.

Anyone has any idea?

**Comment by shaopengwu** [comment]
Any solution vendor is welcome to advice.

**Comment by darroncockram** [comment]
Sorry there's not enough detail to go on here and I'm not sure I understand what you mean by "Sage is always crushed" - do you mean that it crashes perhaps? Some sample code would help.

**Comment by shaopengwu** [comment]
@darroncockram  thanks for the reply.

It should be 'crashed'.

I would like to give the some background about how we are using Sage.

We have one main computer which is Dell PowerEdge T640 1xCUP and 64GB RAM. 
We have 6 computers which access to the server by shared network at offices.
We also have about 5 people they use laptop access through remote access.
We are using V27 (upgraded to v28 but there was problem, so we downgraded) with Sage Could. 

We use Sage to store Sales orders & Invoices. It's about 170, 000 sales orders and 180,000 invoices items. 
But the transaction items are more than 700,000.
We did archive and tried to remove old data but the transaction data are still existed. (I supposed old data can be removed  after archive).

Some Crashed symptoms are:
For the light ones: 

- Sage suddenly becomes very slow and people have to wait for minutes to access
- Queue.DTA hanged, have to remove it manually

Serious ones:

-  error after data check
-  cannot synchronise from remote access to main computer (server)
- Users are kicked off repeatedly when login. 
- Various other errors we have to reload the backup files.

We had called the support team serval times every week, but the situations are not improved.

We want to get some help from the support team, such as if our server is configured powerful enough but always being send a link to the minimum configuration. I don't know where I can get helps.

I had taken some actions to mitigate the problems such as:

- to slow down the import through SData API by one by one
- To let the financial people and sales teams are working in different time
- etc

I had looked for information when I developed the SData import programme. 
I know @darroncockram you have a lot experience about Sage that's why I posted here for help.
If @darroncockram you have other communication methods, I can share our Sage account details. and you can see all of problems arisen in the past. We are UK based.

thanks in advance.

**Comment by darroncockram** [comment]
From your description is doesn't sound like this is related to Sdata specifically, or are you saying the problems of crashing, synchronising, data errors, etc are only happening when you run the import via Sdata? If it is the latter some sample code would be helpful to understand the sort of thing you are doing, but three's nothhing that I'm aware of specifically related to Sdata that would cause any of those kinds of issues,

**Comment by shaopengwu** [comment]
I am not sure if the SData causes these issues. Because when we imported the data, the system begins to slow.
I will find some sample codes for this.

**Comment by shaopengwu** [comment]
<?xml version="1.0" encoding="utf-8"?>
    <entry xmlns:atom="http://www.w3.org/2005/Atom" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cf="http://www.microsoft.com/schemas/rss/core/2005" xmlns="http://www.w3.org/2005/Atom" xmlns:http="http://schemas.sage.com/sdata/http/2008/1" xmlns:sdatasync="http://schemas.sage.com/sdata/sync/2008/1" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:sme="http://schemas.sage.com/sdata/sme/2007" xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <author/>
      <sdata:payload>
        <salesOrder xmlns="http://schemas.sage.com/crmErp/2008" sdata:uuid="00000000-0000-0000-0000-000000000000">
          <active xsi:nil="true"/>
          <reference xsi:nil="true"/>
          <reference2 xsi:nil="true"/>
          <status xsi:nil="true"/>
          <allocationStatus xsi:nil="true"/>
          <deliveryStatus xsi:nil="true"/>
          <invoiceStatus xsi:nil="true"/>
          <statusFlag xsi:nil="true"/>
          <statusFlagText xsi:nil="true"/>
          <tradingAccount sdata:uuid="2883741a-8c11-4b92-b829-5319ea0e8fe8">
          </tradingAccount>
          <customerReference>B3238683XE</customerReference>
          <opportunity xsi:nil="true"/>
          <pricelist xsi:nil="true"/>
          <supplierTradingAccount xsi:nil="true"/>
          <supplierReference xsi:nil="true"/>
          <supplierPurchaseOrders xsi:nil="true"/>
          <type xsi:nil="true"/>
          <copyFlag xsi:nil="true"/>
          <originatorDocument xsi:nil="true"/>
          <quotation xsi:nil="true"/>
          <postalAddresses xsi:nil="true"/>
          <deliveryMethod xsi:nil="true"/>
          <deliveryRule xsi:nil="true"/>
          <deliveryTerms xsi:nil="true"/>
          <deliveryDate xsi:nil="true"/>
          <dueDate>2022-11-15</dueDate>
          <carrierCompany xsi:nil="true"/>
          <carrierTradingAccount xsi:nil="true"/>
          <carrierNetPrice xsi:nil="true"/>
          <carrierTaxPrice xsi:nil="true"/>
          <carrierTotalPrice xsi:nil="true"/>
          <carrierSalesInvoice xsi:nil="true"/>
          <carrierTaxCodes xsi:nil="true"/>
          <carrierReference xsi:nil="true"/>
          <currency xsi:nil="true"/>
          <operatingCompanyCurrency xsi:nil="true"/>
          <operatingCompanyCurrencyExchangeRate xsi:nil="true"/>
          <operatingCompanyCurrencyExchangeRateOperator xsi:nil="true"/>
          <operatingCompanyCurrencyExchangeRateDate xsi:nil="true"/>
          <invoiceCurrency xsi:nil="true"/>
          <invoiceCurrencyExchangeRate xsi:nil="true"/>
          <invoiceCurrencyExchangeRateOperator xsi:nil="true"/>
          <invoiceCurrencyExchangeRateDate xsi:nil="true"/>
          <customerTradingAccountCurrency xsi:nil="true"/>
          <customerTradingAccountCurrencyExchangeRate xsi:nil="true"/>
          <customerTradingAccountCurrencyExchangeRateOperator xsi:nil="true"/>
          <customerTradingAccountCurrencyExchangeRateDate xsi:nil="true"/>
          <date xsi:nil="true"/>
          <time xsi:nil="true"/>
          <validity xsi:nil="true"/>
          <expirationDate xsi:nil="true"/>
          <buyerContact xsi:nil="true"/>
          <salesPersons xsi:nil="true"/>
          <user>mandy</user>
          <salesOrderLines><salesOrderLine>
            <salesOrder xsi:nil="true"/>
            <active xsi:nil="true"/>
            <reference xsi:nil="true"/>
            <reference2 xsi:nil="true"/>
            <number xsi:nil="true"/>
            <status xsi:nil="true"/>
            <type>Standard</type>
            <deliveryTerms xsi:nil="true"/>
            <commodity sdata:uuid="c2cd1238-60cc-4f2f-b7f4-146eec0d06fc">5006W90150</commodity>
            <actualPrice>22.47512112524492</actualPrice>
            <quantity>1</quantity>
            <text>50mm CharcoalBlack 85.0cm x 98.0cm</text>
            <associatedCommodity xsi:nil="true"/>
            <fulfillmentLocation xsi:nil="true"/>
            <deliveryDate xsi:nil="true"/>
            <dueDate>2022-11-15</dueDate>
            <carrierTradingAccount xsi:nil="true"/>
            <carrierNetPrice xsi:nil="true"/>
            <carrierTaxPrice xsi:nil="true"/>
            <carrierTotalPrice xsi:nil="true"/>
            <carrierSalesInvoiceLine xsi:nil="true"/>
            <carrierTaxCodes xsi:nil="true"/>
            <carrierReference xsi:nil="true"/>
            <unitOfMeasure xsi:nil="true"/>
            <initialPrice xsi:nil="true"/>
            <pricelist xsi:nil="true"/>
            <supplierTradingAccount xsi:nil="true"/>
            <supplierReference xsi:nil="true"/>
            <supplierPurchaseOrder xsi:nil="true"/>
            <supplierPurchaseOrderLine xsi:nil="true"/>
            <quotationLine xsi:nil="true"/>
            <postalAddresses xsi:nil="true"/>
            <orderLineDiscountType xsi:nil="true"/>
            <orderLineDiscountAmount xsi:nil="true"/>
            <orderLineDiscountPercent xsi:nil="true"/>
            <orderLineSubtotalDiscountType xsi:nil="true"/>
            <orderLineSubtotalDiscountAmount xsi:nil="true"/>
            <orderLineSubtotalDiscountPercent xsi:nil="true"/>
            <FOBPoint xsi:nil="true"/>
            <netTotal>22.47512112524492</netTotal>
            <chargesTotal xsi:nil="true"/>
            <discountTotal xsi:nil="true"/>
            <priceTax xsi:nil="true"/>
            <taxTotal xsi:nil="true"/>
            <grossTotal xsi:nil="true"/>
            <costTotal xsi:nil="true"/>
            <profitTotal xsi:nil="true"/>
            <salesInvoiceLines xsi:nil="true"/>
            <receipts xsi:nil="true"/>
            <buyerContact xsi:nil="true"/>
            <project xsi:nil="true"/>
            <salesOrderDeliveryLines xsi:nil="true"/>
            <BOMLine xsi:nil="true"/>
            <financialAccounts xsi:nil="true"/>
            <taxCodes>
              <taxCode sdata:uuid="e0300d55-2b29-4454-b4d3-3d6e4a79ace8">
                <notes xsi:nil="true"/>
              </taxCode>
            </taxCodes>
          </salesOrderLine><salesOrderLine>
            <salesOrder xsi:nil="true"/>
            <active xsi:nil="true"/>
            <reference xsi:nil="true"/>
            <reference2 xsi:nil="true"/>
            <number xsi:nil="true"/>
            <status xsi:nil="true"/>
            <type>Standard</type>
            <deliveryTerms xsi:nil="true"/>
            <commodity sdata:uuid="0e3062ab-93a2-41d6-becf-1f4e299c937f">B2EXPRESS5</commodity>
            <actualPrice>0</actualPrice>
            <quantity>1</quantity>
            <text/>
            <associatedCommodity xsi:nil="true"/>
            <fulfillmentLocation xsi:nil="true"/>
            <deliveryDate xsi:nil="true"/>
            <dueDate>2022-11-15</dueDate>
            <carrierTradingAccount xsi:nil="true"/>
            <carrierNetPrice xsi:nil="true"/>
            <carrierTaxPrice xsi:nil="true"/>
            <carrierTotalPrice xsi:nil="true"/>
            <carrierSalesInvoiceLine xsi:nil="true"/>
            <carrierTaxCodes xsi:nil="true"/>
            <carrierReference xsi:nil="true"/>
            <unitOfMeasure xsi:nil="true"/>
            <initialPrice xsi:nil="true"/>
            <pricelist xsi:nil="true"/>
            <supplierTradingAccount xsi:nil="true"/>
            <supplierReference xsi:nil="true"/>
            <supplierPurchaseOrder xsi:nil="true"/>
            <supplierPurchaseOrderLine xsi:nil="true"/>
            <quotationLine xsi:nil="true"/>
            <postalAddresses xsi:nil="true"/>
            <orderLineDiscountType xsi:nil="true"/>
            <orderLineDiscountAmount xsi:nil="true"/>
            <orderLineDiscountPercent xsi:nil="true"/>
            <orderLineSubtotalDiscountType xsi:nil="true"/>
            <orderLineSubtotalDiscountAmount xsi:nil="true"/>
            <orderLineSubtotalDiscountPercent xsi:nil="true"/>
            <FOBPoint xsi:nil="true"/>
            <netTotal>0</netTotal>
            <chargesTotal xsi:nil="true"/>
            <discountTotal xsi:nil="true"/>
            <priceTax xsi:nil="true"/>
            <taxTotal xsi:nil="true"/>
            <grossTotal xsi:nil="true"/>
            <costTotal xsi:nil="true"/>
            <profitTotal xsi:nil="true"/>
            <salesInvoiceLines xsi:nil="true"/>
            <receipts xsi:nil="true"/>
            <buyerContact xsi:nil="true"/>
            <project xsi:nil="true"/>
            <salesOrderDeliveryLines xsi:nil="true"/>
            <BOMLine xsi:nil="true"/>
            <financialAccounts xsi:nil="true"/>
            <taxCodes>
              <taxCode sdata:uuid="e0300d55-2b29-4454-b4d3-3d6e4a79ace8">
                <notes xsi:nil="true"/>
              </taxCode>
            </taxCodes>
          </salesOrderLine></salesOrderLines>
          <lineCount xsi:nil="true"/>
          <orderDiscountType xsi:nil="true"/>
          <orderDiscountAmount xsi:nil="true"/>
          <orderDiscountPercent xsi:nil="true"/>
          <orderAdditionalDiscount1Type xsi:nil="true"/>
          <orderAdditionalDiscount1Amount xsi:nil="true"/>
          <orderAdditionalDiscount1Percent xsi:nil="true"/>
          <orderAdditionalDiscount2 xsi:nil="true"/>
          <orderAdditionalDiscount2Amount xsi:nil="true"/>
          <orderAdditionalDiscount2Percent xsi:nil="true"/>
          <text1>/Users/-/workspaces/sage/sageprocess/data/inputdat</text1>
          <text2>blinds2go Limited</text2>
          <netTotal xsi:nil="true"/>
          <discountTotal xsi:nil="true"/>
          <chargesTotal xsi:nil="true"/>
          <taxTotal xsi:nil="true"/>
          <grossTotal xsi:nil="true"/>
          <costTotal xsi:nil="true"/>
          <profitTotal xsi:nil="true"/>
          <receipts xsi:nil="true"/>
          <depositFlag xsi:nil="true"/>
          <contract xsi:nil="true"/>
          <invoiceTradingAccount xsi:nil="true"/>
          <invoiceCountry xsi:nil="true"/>
          <orderCountry xsi:nil="true"/>
          <projects xsi:nil="true"/>
          <salesOrderDeliveries xsi:nil="true"/>
          <fulfillmentLocations xsi:nil="true"/>
          <financialAccounts xsi:nil="true"/>
          <interactions xsi:nil="true"/>
          <notes xsi:nil="true"/>
        </salesOrder>
      </sdata:payload>
    </entry>

**Comment by darroncockram** [comment]
> I am not sure if the SData causes these issues. Because when we imported the data, the system begins to slow. I will find some sample codes for this.

It's definitely not Sdata slowing things down or causing crashes or sync errors then. From your example there is nothing particularly wrong with it other than the decimal prescision on the line is greater than is suppported by the application, but that won't cause an issue as it will simply be rounded. 

I suspect your issues are related to the size of the data as those volumes are wel above the recommended data limits for Sage 50 Accounts https://gb-kb.sage.com/portal/app/portlets/results/viewsolution.jsp?solutionid=210114115605493&page=1&position=2&q=maximum

**Comment by shaopengwu** [comment]
@darroncockram thanks for you comments. I will see if the old data can be removed
