### ISSUE TITLE
Barcode empty

### ISSUE THREAD

**Issue by Lazyname** [Sage/SData-2.0#19]
Hello,
working on a solution to get some information from sage Accounts 50 2013 v19
I need the barcodes of the products but when I navigate to commodityIdentifiers - barcode its empty.

I have done plenty of googling but with no luck. 
Help please :)

 http://[server]/sdata/accounts50/gcrm/[ entree code ]/commodityIdentifiers
Regards Ilian

**Comment by darroncockram** [comment]
The barcode property is not currently supported in the Sage 50 Accounts Sdata implementation I'm afraid. You can see this flagged as sme:unsupported="true" in the schema.

**Comment by Lazyname** [comment]
Thanks for the replay darroncockram, thanks.
