### ISSUE TITLE
Data posting to Legder

### ISSUE THREAD

**Issue by stquinn2015** [Sage/SData-2.0#20]
Is it possible to post a sales invoice to the ledger using c sharp and data. Also can you mark a payment against a sales invoice using sdata

**Comment by darroncockram** [comment]
I take it this is Accounts 50 you're referring to? If so access to the audit trail is only available as read-only via the Sdata feeds at the moment I'm afraid.

**Comment by stquinn2015** [comment]
Hi Darron

Ok Thanks. Is this likely to change in the future?

Regards

Sean

**Comment by darroncockram** [comment]
>Ok Thanks. Is this likely to change in the future?

I'm not aware of any immediate plans for it. I can certainly raise it as an RFC with the Accounts team but I couldn't make any promises as to if or when it might be picked up to be implmented.
