### ISSUE TITLE
Incoming Invoices

### ISSUE THREAD

**Issue by stquinn2015** [Sage/SData-2.0#21]
I Implemented a program which imports invoices from our internal ordering system into Sage 50. However some of these invoices have already been paid by the time they enter sage 50. Therefore is there a way using sdata to mark these invoices as paid as soon as they are imported?

**Comment by darroncockram** [comment]
Unfortunately the Accounts 50 Sdata implementation doesn't currently allow you to post to the audit trail so it's not possible to flag the invoice as paid via the feeds either I'm afraid.
