### ISSUE TITLE
Retrieve Transactions based on Nominal Code

### ISSUE THREAD

**Issue by geoffo** [Sage/SData-2.0#22]
Is there a way to retrieve a list of transactions based on Nominal code?  I looked through the schema but don't see where Nominal Code is exposed.

**Comment by darroncockram** [comment]
Nominal codes are exposed as 'financialAccounts' but there is currently only very limited support for transactions (tradingActivities) in the Sage 50 Accounts adapter. The tradingAcivities type only exposes the audit header information, but the nominal code is held on the audit split which is not yet exposed to the Sdata feeds I'm afraid.

**Comment by Artful-dodger** [comment]
Is there any other way then to retrieve the data for say a bank account or would you have retrieve all the data from 'tradingActivies' and some how filter that data

**Comment by darroncockram** [comment]
Bank accounts are exposed via the bankAccounts resource kind.

Hope that helps

**Comment by Artful-dodger** [comment]
do you have an example on how to retrieve all the data from 1200 nominal account using bankAccounts resource I have tried  http://localhost:5493/sdata/accounts50/GCRM/-/tradingActivities?where=accountReference eq '1200' and that is why I came to the conclusion that you may need the audit split endpoint to achieve this

**Comment by asterix187** [comment]
http://localhost:5493/sdata/accounts50/GCRM/-/financialAccounts?where=reference eq '1200'

**Comment by daz-soap** [comment]
Thank you for you response asterix187 but this is all the data returned 
{
  "$descriptor": "Sage Accounts 50 | financialAccount - ",
  "$url": "http://eula-pc:5493/sdata/accounts50/GCRM/-/financialAccounts",
  "$totalResults": 1,
  "$startIndex": 1,
  "$itemsPerPage": 1,
  "$resources": [
    {
      "$url": "http://eula-pc:5493/sdata/accounts50/GCRM/-/financialAccounts(744bf736-24c1-4a46-bf3a-dd78a68f5299)?format=atomentry",
      "$uuid": "744bf736-24c1-4a46-bf3a-dd78a68f5299",
      "$httpStatus": "OK",
      "$descriptor": "",
      "active": true,
      "reference": "1200",
      "reference2": "FF476636-D4AF-4191-BDE4-891EDA349A54",
      "type": null,
      "reportingType": null,
      "accountingType": null,
      "name": "Business Account",
      "description": null,
      "account": "Business Account",
      "analysis01": null,
      "analysis02": null,
      "analysis03": null,
      "analysis04": null,
      "analysis05": null,
      "analysis06": null,
      "analysis07": null,
      "analysis08": null,
      "analysis09": null,
      "analysis10": null,
      "analysis11": null,
      "analysis12": null,
      "analysis13": null,
      "analysis14": null,
      "analysis15": null,
      "currency": "GBP",
      "balance": 0.0,
      "balanceDate": null,
      "lastTransactionDate": null,
      "primacyIndicator": false
    }
  ]
}
I am looking for all the activity to ‘1200’ bank account I am not sure how query the data base to achieve the result that I get when I look at the bank account in sage

Here is some of the data missing from my search made when using http://localhost:5493/sdata/accounts50/GCRM/-/tradingActivities?where=reference eq '1200'

{
      "$url": "http://eula-pc:5493/sdata/accounts50/GCRM/-/tradingActivities(06a6a428-bb0b-4042-a209-a78dacf798fc)?format=atomentry",
      "$uuid": "06a6a428-bb0b-4042-a209-a78dacf798fc",
      "$httpStatus": "OK",
      "$descriptor": "",
      "applicationID": "237138c5-82bc-4434-bd1d-8adc9aca018d",
      "active": true,
      "deleted": false,
      "label": "Trading Activity",
      "reference": "300006",
      "tradingAccount": null,
      "transactionType": "PP",
      "date": "\/Date(1290470400000+0000)\/",
      "details": "Purchase Payment",
      "amountNet": 20.25,
      "amountTax": 0.0,
      "amountGross": 20.25,
      "currency": "GBP",
      "amountPaid": 20.25,
      "accountReference": "MOBILE",
      "dueDate": null,
      "headerNumber": "65"
    },
I am looking for the syntax to query the database to include this

**Comment by darroncockram** [comment]
The split data is not exposed to the Sdata feeds I'm afraid so the query suggested by Artful-Dodger is the closest you will be able to get all activity for bank account 1200 with current functionality.

**Comment by Artful-dodger** [comment]
is there any likelihood of split data being exposed to sdata feed in the near future

**Comment by asterix187** [comment]
Also is there any way we can request things to be added to the sData feed in future releases?

I would love things like Comment Line 1/2 on order lines, Delivery Company Name field on orders etc

**Comment by darroncockram** [comment]
> is there any likelihood of split data being exposed to sdata feed in the near future

I'm no aware of any plans for it but I will certainly pass on the request to the Accounts team

> Also is there any way we can request things to be added to the sData feed in future releases?

I pass on all requests and bug reports that are posted here so you can keep raising things via this channel if you want. Alternatively the recently launched feedback area on the main site can be used to sumbit ideas and to up vote ones of interest/value - https://communities.sage.co.uk/ideas/i/sage_50_accounts

**Comment by xwilders** [comment]
Do you know if anything has changed over the last two years? Is there now a way to retrieve the nominal account used in a transaction activity?

**Comment by Artful-dodger** [comment]
Hi I am affraid to say that Sage have said that they are no longer supporting the Sdata modual, I have contacted them on several occasions since Version 22 but silence was the loudest reply apparently you need to subscribe to their Sage developers programme (https://my.sage.co.uk/public/help/askarticle.aspx?articleid=33851)this use to be free  but now costs over a thousand pound per year to get any further with Sdata so I have stopped my development of my Sage front end project for now.

Thanks for contacting me let me know how you get on.

________________________________

**Comment by asterix187** [comment]
Even as a developer you do not get any support on sData. 

I had asked if the sData project could be put as open source onto GitHub to let the community develop it and even offered to develop it for free but Sage do not want to go down that route.

We have now created our own version of sData to give us complete control over web service based access to Sage 50 for our integrations and only post on this forum to try to help others.

**Comment by Artful-dodger** [comment]
Thank you for your response asterix187 have you been able to expose the split data feed as this was what stopped me carrying o with my project, the only reason I thought they gave more assistance is that I have seen a company using the Sdata module in the programme albeit C# but they where using it to retrieve the data I would very much like to try your version of sData.
It appears that sage is in fear of loosing control of there software out side their controlled environment I think there are developers that use other languages like python and php that would enhance Sage 50 with better looking front ends

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by asterix187** [comment]
Effectively SData is a web wrapper for SDO interface into Sage 50. We have effectively written our own wrapper which is similar (but not exactly) like SData. Because of this we can access anything that you can access via the standard SDO interface. And have also successfully implemented functions like the ComputePrice method within SData (which doesn't actually work correctly).

However, our web service for Sage 50 is part of our IP for a Sage 50 integration we sell customers (over 100 sites now). It would be good to hear about the project you are working on to see if we can help in any way.

If you drop me an email (details in my GitHub bio) via our info@ account initial we can discuss further if you would like.
