### ISSUE TITLE
salesOrderLines not added to salesOrder via POST 

### ISSUE THREAD

**Issue by bubblemedialtd** [Sage/SData-2.0#23]
When running some test salesOrder POST requests, it is adding the salesOrder itself, but no salesOrderLines.

URL: http://it1:5493/sdata/accounts50/GCRM/-/salesOrders

Body:

```
<entry xmlns:sdata="http://schemas.sage.com/sdata/2008/1" 
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.w3.org/2005/Atom">
  <id/>
  <title/>
  <content/>
  <sdata:payload>
    <salesOrder xmlns="http://schemas.sage.com/sdata/2008">
      <date>2015-08-24</date>
      <tradingAccount sdata:uuid="9a7a0179-85cb-4b65-9d02-73387073ac83"></tradingAccount>
      <contact sdata:uuid="9a7a0179-85cb-4b65-9d02-73387073ac83"></contact>
      <subTotal>351.55</subTotal>
      <lineCount>2</lineCount>
      <orderLines>
        <salesOrderLine sdata:uuid="407334d5-438f-4b98-8623-ea0c7645f159">
          <product sdata:key="0.601.214.041"/>
          <orderQty>1</orderQty>
          <unitPrice>230.55</unitPrice>
        </salesOrderLine>
        <salesOrderLine sdata:uuid="0f397396-9ef1-4e9c-9353-481d2c533c80">
          <product sdata:key="00"/>
          <orderQty>2</orderQty>
          <unitPrice>60.50</unitPrice>
        </salesOrderLine>
      </orderLines>
    </salesOrder>
  </sdata:payload>
</entry>
```

**Comment by darroncockram** [comment]
That's because your XML is incorrect in a fairly subtle way. The lines collection property should be <salesOrderLines> note <orderLines>.

Hope that helps.

**Comment by darroncockram** [comment]
Ah, that's because the line collection property should be
```
<salesOrderLines>
```
Rather than
```
<orderLines>
```

Hope that helps.

**Comment by bubblemedialtd** [comment]
Unfortunately that hasn't made much difference. It now inserts the correct number of lines, but they are empty entirely.

I have slightly altered the XML as it wasn't working with the previous xmlns.

```<entry xmlns:sdata="http://schemas.sage.com/sdata/2008/1" 
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.w3.org/2005/Atom">
  <id/>
  <title/>
  <content/>
  <sdata:payload>
    <salesOrder xmlns="http://schemas.sage.com/crmErp/2008">
      <date>2015-08-24</date>
      <tradingAccount sdata:uuid="ebe6990c-0311-416d-a55c-3fa200e367a8"></tradingAccount>
      <salesOrderLines>
        <salesOrderLine sdata:uuid="fe07e2d1-7445-4853-a35b-dc6e9b5cd513">
          <product sdata:key="0.601.214.041"/>
          <orderQty>1</orderQty>
          <unitPrice>81.70</unitPrice>
        </salesOrderLine>
        <salesOrderLine sdata:uuid="1b2fc197-433b-4fc3-95d1-e79058f4dc10">
          <product sdata:key="00"/>
          <orderQty>2</orderQty>
          <unitPrice>60.50</unitPrice>
        </salesOrderLine>
      </salesOrderLines>
    </salesOrder>
  </sdata:payload>
</entry>
```

**Comment by bubblemedialtd** [comment]
It would seem that it isn't linking the commodity to the uuid provided in the payload.

```
<entry xmlns:sdata="http://schemas.sage.com/sdata/2008/1" 
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.w3.org/2005/Atom">
  <id/>
  <title/>
  <content/>
  <sdata:payload>
    <salesOrder xmlns="http://schemas.sage.com/crmErp/2008" sdata:uuid="319efc37-055f-42b4-910c-116ea4b8388e">
      <date>2015-08-24</date>
      <tradingAccount sdata:uuid="b70b751b-a4ca-4a91-bdda-d22e3041e5f1"></tradingAccount>
      <netTotal>202.70</netTotal>
      <taxTotal>40.54</taxTotal>
      <grossTotal>243.24</grossTotal>
      <salesOrderLines>
        <salesOrderLine sdata:uuid="40aaa849-6b0d-49a4-9a42-b985f3b2d4d3">
          <associatedCommodity>0.601.214.041</associatedCommodity>
          <quantity>1</quantity>
          <actualPrice>81.70</actualPrice>
          <priceTax>16.34</priceTax>
          <grossTotal>98.04</grossTotal>
          <text>Product 1</text>
        </salesOrderLine>
        <salesOrderLine sdata:uuid="2ec2e0e2-377b-413a-b08e-03c728500692">
          <associatedCommodity>00</associatedCommodity>
          <quantity>2</quantity>
          <actualPrice>60.50</actualPrice>
          <priceTax>24.20</priceTax>
          <grossTotal>145.20</grossTotal>
          <text>Product 2</text>
        </salesOrderLine>
      </salesOrderLines>
    </salesOrder>
  </sdata:payload>
</entry>
```

I am having to manually enter everything, but there is nowhere to put the product code

**Comment by darroncockram** [comment]
It's the commodity property that you need to use rather than the associatedCommodity. The latter is flagged as sme:unsupported="true" in the Sage 50 Accounts adapter and as such will be ignored by it. It's something along these lines that you need:

```
<!-- Other details omitted for brevity -->
<salesOrderLines>
        <salesOrderLine>
                <commodity sdata:uuid="ff991dcf-bd25-4d20-95db-813cc8dc86b9">
                <!-- Make sure to replace the UUID above with the appropriate one for your commodity -->
                </commodity>
        </salesOrderLine>
 </salesOrderLines>
```

You don't mention the technology stack you're using but if it's .NET then you might find this series of videos useful: www.youtube.com/playlist?list=PLF56D8511E5ABB680&feature=plcp which demonstrate using the Sdata Integration Framework (SIF) to interact with Sdata feeds.

Whilst it doesn't specifically demonstrate creating a salesOrder it does demonstrate POSTing resources and the principles are pretty much much the same regardless of the resource kind.

**Comment by bubblemedialtd** [comment]
Thanks Darron.

I'm actually using PHP for this task. It's part of a custom CRM for a client, which is linked to their Sage 50 Accounts.

Using the <commodity> tag has resulted in the product being mapped correctly.

**Comment by bubblemedialtd** [comment]
Darron, is it possible to replace sdata:uuid with sdata:reference to match the product?

**Comment by darroncockram** [comment]
>is it possible to replace sdata:uuid with sdata:reference to match the product?
Afraid not. The Sdata specification does not define an attribute called reference on a resource kind. The only way to uniquely identify a specific resource via Sdata is by using the UUID.

Of course you don't need to display the UUID to your end users (in fact it was never intended for display purposes) and you can always display the reference property from the commodity when the user is selecting/viewing the item in your UI.
