### ISSUE TITLE
Object Reference Exception When Filtering By $updated Date

### ISSUE THREAD

**Issue by geoffo** [Sage/SData-2.0#24]
Hi,

I am attempting to filter salesInvoices by the $updated date: 
salesInvoices?where=$updated%20gt%20@2015-09-08@

When doing so, I receive an "Object reference not set to an instance of an object" error.  Below is the complete error message.  Can you please help me understand what the issue is?  Is my request format correct? 

<sdata:message>
GET operation failed - Object reference not set to an instance of an object. at Sage.Integration.Accounts50.SDOAdapter.SDORequestHandler.OnGetRequest(IRequest request, IFeed feed) at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.OnGetRequest(IRequest request) at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.GetRequest(IRequest request) at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.OnGetResource(IRequest request) at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.GetRequest(IRequest request) (-1)
</sdata:message>

Thanks.

**Comment by darroncockram** [comment]
Ah, I think that it will be the $ that will be causing the problem Something like salesInvoices?where=updated%20gt%20@2015-09-08@ should do the trick.

Just to be clear the syntax you were trying to use is correct as per the Sdata standard but the Accounts support for protocol filters was implemented before the $ syntax was ratified as part of the standard so still uses the original syntax without the dollar sign.

**Comment by geoffo** [comment]
Thanks Darron, that worked.
