### ISSUE TITLE
TradingAccount response always shows account as Active

### ISSUE THREAD

**Issue by geoffo** [Sage/SData-2.0#25]
When retrieving a TradingAccount, the 'active' field always returns 'true'.  This occurs even after setting a customer record to Inactive within the Sage software.  Does the Active field map to a different value than the Inactive checkbox or is this an issue with the generated response data?

**Comment by darroncockram** [comment]
I don't think the active flag maps to anything. I'll raise it with the Accounts team.

**Comment by asterix187** [comment]
+1 for this. This also affects products so even if a product is marked as inactive it still shows as active in the sData feed.

**Comment by asterix187** [comment]
Any further comment/suggestion on this? It causes all sorts of issues and must be a fairly easy fix. 

To be honest I am quite surprised that Sage just don't open source the sData provider code so we can adjust it to our needs.

**Comment by darroncockram** [comment]
It's still outstanding I'm afraid. I'll let the Accounts team know the issue has been raised again but unfortunately I have no control over their backlog so cannot say if/when it might be picked up to be addressed.

There was talk of open sourcing the SIF a while back but that did not go ahead  in the end mores the pity.

**Comment by asterix187** [comment]
Hi Darron, thanks for the honest feedback. Who does have control over it?

**Comment by darroncockram** [comment]
The Accounts roadmap is on the main website here https://my.sage.co.uk/public/help.aspx#/roadmap/sage-50-accounts. It's not as detailed as the internal backlog so individual bugs typically won't be visible there but you can submit suggestions/requests and up-vote items via that.

Still no guarantees that any particular item will be picked up but obviously the more people asking for something the more likely it will be to float up the backlog.

**Comment by ArshathS** [comment]
I'm also facing the same issue. All the inactive trading accounts are coming as active. Any workarounds for this as of now?

**Comment by darroncockram** [comment]
The only workaround would be to use the status field to determine if the status is set to 'closed' or not. Note however that the actual test of the account statuses is configurable within the Accounts UI so it is possible that the specific value might not be 'closed' in any given dataset
