### ISSUE TITLE
SData is not responding on GET requests

### ISSUE THREAD

**Issue by galimru** [Sage/SData-2.0#26]
Hi Everyone

I have a trouble with Sage 50 Accounts 2014. 
When I trying to open next link in browser: http://localhost:5493/sdata/accounts50/GCRM/-/salesOrders
Browser starts loading page, but nothing does. 
I see only white page and animation of loading in browser tab. 
I am waited very long, but page has not been loaded.

If I am making request through POST method, SData is responding:

```xml
<?xml version="1.0" encoding="utf-8"?>
<diagnosis xmlns="http://schemas.sage.com/sdata/2008/1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:sdatasync="http://schemas.sage.com/sdata/sync/2008/1" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:sme="http://schemas.sage.com/sdata/sme/2007" xmlns:http="http://schemas.sage.com/sdata/http/2008/1">
  <sdata:severity>error</sdata:severity>
  <sdata:sdataCode>ApplicationDiagnosis</sdata:sdataCode>
  <sdata:applicationCode />
  <sdata:message>Request Content Type 'Atom' is not acceptable</sdata:message>
  <sdata:stackTrace />
  <sdata:payloadPath />
</diagnosis>
```

Although, requests to:
http://localhost:5493/sdata/$system/adapters
http://localhost:5493/sdata/$system/registry/endpoints
are passing normally.

![sdata-failed](https://cloud.githubusercontent.com/assets/5149355/10189060/171bcfa8-6775-11e5-888a-7a86b4387d9e.png)
![sdata-success](https://cloud.githubusercontent.com/assets/5149355/10189068/1d5d29e8-6775-11e5-94d9-06b362d8b0d2.png)

**Comment by darroncockram** [comment]
In terms of the error when POSTing it sounds like you simply have an incorrect Content-Type header specified. It should be **application/atom+xml;type=entry** rather than **Atom**

With the hanging on a GET request there are a number of possible causes I can think of. Is there a  dataset available (you can check this via an endpoints query)? If a dataset is available can you connect to to i using the main Accounts application? Is the data in a network location? If it is is the path used to access it a mapped drive or a UNC share (it must be the latter to be available to the Sdata service)? Does the service user  have access to the location in which the data is stored (the service runs as LocalSystem by default so definitely won't have access to any network locations)?

Hope that hepls.

**Comment by galimru** [comment]
Thank you for the quick reply.

> Is there a dataset available (you can check this via an endpoints query)?

You mean it is? Yes, dataset is available.

![dataset-query](https://cloud.githubusercontent.com/assets/5149355/10190901/d24b2cdc-6780-11e5-84a9-2ac53ef2215a.png)

> If a dataset is available can you connect to to i using the main Accounts application?

Yes, I can connect my data through Sage 50 Accounts.

> Is the data in a network location? If it is is the path used to access it a mapped drive or a UNC share (it must be the latter to be available to the Sdata service)? 

Database in a network location (\\\tkc-file\sage_database\SAGE\ACCDATA)

> Does the service user have access to the location in which the data is stored (the service runs as LocalSystem by default so definitely won't have access to any network locations)?

Yes, I can open UNC folder and read files.

Maybe, are there settings that enable availability of data?

**Comment by galimru** [comment]
![services-sage](https://cloud.githubusercontent.com/assets/5149355/10191235/39b5a828-6783-11e5-8bb9-b1abd0e0cf4d.png)

Service started as Local System, but database in UNC path. Because of this?

**Comment by darroncockram** [comment]
>Maybe, are there settings that enable availability of data?
There aren't any settings as such but if the data is stored in a network location the service definitely will be unable to access it when running as LocalSystem. You'd need to change the service to run as a user that does have read/write access to the network location of the data files. Alternatively you could run the Sdata Service on the machine that hosts the data and access it locally

**Comment by galimru** [comment]
Thanks a lot!
All the best.
