### ISSUE TITLE
Sage 50 Accounts cannot update (PUT) salesOrderLines

### ISSUE THREAD

**Issue by exptom** [Sage/SData-2.0#28]
I'm trying to update existing salesOrderLine entries on a salesOrder but I get this error message:

`PUT operation failed - POST of related resource salesOrderLines failed.`

I have successfully edited the delivery address and general salesOrder info via a PUT request.
I notice that requesting /salesOrders/$schema for salesOrderLines:

`<xs:element name="salesOrderLine" type="crm:salesOrderLine--type" sme:canGet="true" sme:canPost="true" sme:canPut="false" sme:canDelete="false" ...>`

Is there a workaround for not being able to PUT and DELETE? Only being able to POST severly limits the usefulness of the api on Sage 50!

**Comment by darroncockram** [comment]
Afraid not. The Sage 50 Accounts Sdata adapter doesn't currently support PUT or DELETE on salesOrderLines so the schema is providing the correct information. The error message you are seeing is simply because it's not implemented.

**Comment by exptom** [comment]
I'm using the 2015 of Sage 50 Accounts Pro, do you know if this is fixed in the 2016 version? If not what version of Sage accounts would we need to upgrade to in order to be able to do this?

**Comment by darroncockram** [comment]
There is no version of Sage 50 Accounts that currently supports PUT or DELETE on salesOrderLines I'm afraid.

**Comment by exptom** [comment]
Which Sage accounting products do support it?

**Comment by darroncockram** [comment]
I'm not familiar with any that do.
