### ISSUE TITLE
Create salesInvoice from salesOrder

### ISSUE THREAD

**Issue by exptom** [Sage/SData-2.0#29]
Using Sage 50 Accounts is it possible to create a salesInvoice from a salesOrder?
Looking at the docs it appears that originatorDocument should create the link but if I do the following:

```
<sdata:payload>
            <crm:salesInvoice>
                <crm:originatorDocument>
                    <crm:salesOrder  sdata:uuid="ee82aa4e-b7a2-4490-9701-17402978dc8f" />
                </crm:originatorDocument>
                ...
                ... salesInvoiceLines etc...
            </crm:salesInvoice>
</sdata:payload>
```

then I get this error message:

`POST operation failed - The changes you requested to the table were not successful because they would create duplicate values in the index, primary key, or relationship.  Change the data in the field or fields that contain duplicate data, remove the index, or redefine the index to permit duplicate entries and try again.`

Do I need to link each salesInvoiceLine to the salesOrderLine?

**Comment by darroncockram** [comment]
Hmmm. I think that the originatorDocument field is supposed to be read only. Do you get the same error if you omit it from the payload?

**Comment by exptom** [comment]
If originator document is empty it creates the invoice but not linked to any sales order.

**Comment by darroncockram** [comment]
That's what I'd expect. As I say I think the originator document is meant to be read only although it isn't correctly flagged as such in the schema.

**Comment by exptom** [comment]
Ok. Can you explain the process of converting a salesOrder to a salesInvoice via sdata?

**Comment by darroncockram** [comment]
There's no built in helpers so you'd have to transpose the values on the salesOrder to a new salesInvoice and POST it to the salesInvoices feed.

**Comment by exptom** [comment]
I've tried doing that - update reference2 on salesOrder with salesInvoice reference which shows the reference in the "Inv ref" field on the details tab but the invoice never shows up on the "Invoices" tab of the sales order. Is there a particular field or status that the salesInvoice needs to be set to allow that to happen?

**Comment by darroncockram** [comment]
This is probably getting a little off topic for the Sdata forums but invoices in Sage 50 Accounts will only display on the sales order once the order is either partly or fully dispatched (you can only dispatch via the Accounts UI). That isn't really anything you are/aren't doing via Sdata but rather it's just how Accounts works. You'll see the same behaviour if you created an invoice in the main Accounts application and entered an number for a sales order that has not yet been dispatched.

**Comment by exptom** [comment]
The schema makes it look like the allocationStatus, deliveryStatus and invoiceStatus can be edited but it does not seem possible to change their values. The status field is marked as unsupported but the other status field are not.

**Comment by darroncockram** [comment]
>The schema makes it look like the allocationStatus, deliveryStatus and invoiceStatus can be edited but it does not seem possible to change their values. The status field is marked as unsupported but the other status field are not.

They aren't unsupported but they are read only. I've passed that on to the Accounts team to update the schema.
