### ISSUE TITLE
Retrieve commodity information for each order line in SalesOrder feed

### ISSUE THREAD

**Issue by geoffo** [Sage/SData-2.0#3]
I am currently attempting to retrieve a salesOrder feed along with the corresponding salesOrderLines, in JSON format, from Sage 50 Accounts.  For example, my URL is:
.../sdata/accounts50/GCRM/-/salesOrders?include=salesOrderLines&format=json

My problem is that the salesOrderLine information does not contain a field that corresponds to the related commodity information when retrieving a salesOrder.  I am specifically looking to obtain the UUID or the product code to be used as a reference later.  I have tried to add an include parameter value of "salesOrderLines,salesOrderLines/commodity" but the commodity information is not being returned.

I know that I can retrieve a salesOrderLines feed with an include of "commodity" to get the product information.  However I am trying to get all the information in a single call using salesOrder.  

Is there anyway to retrieve the commodity information from a salesOrder feed?

**Comment by darroncockram** [comment]
Unfortunately the Accounts 50 Sdata adapter doesn't currently support the sub resource syntax on the include parameter. You can work around the problem by querying the salesOrderLines feed directly e.g.g http://localhost:5493/sdata/accounts50/GCRM/-/salesOrderLines?include=commodity,salesOrder&where=reference eq 1.

Hope that helps.
