### ISSUE TITLE
Where Filter with LIKE causing Server Errors

### ISSUE THREAD

**Issue by geoffo** [Sage/SData-2.0#30]
I am attempting to perform a LIKE comparison but I am receiving either a "500 Internal Server error" or "GET operation failed - Invalid URI: There is an invalid sequence in the string." error.

I am attempting the following query: where=reference like 'A%'

Below are the encoded URL values that I have tried:

tradingAccounts?where=reference%20like%20%27A%25%27

tradingAccounts?where=reference%20like%20"A%25"

tradingAccounts?where=reference%20like%20%27A%%27

tradingAccounts?where=reference%20like%20"A%"

From what I gather the issue has to do with the % being used as a wildcard in the like value.  I have tried not escaping it and escaping it but neither are working.  Can you please help me identify the % needs to be sent in a like comparison?

**Comment by darroncockram** [comment]
I would have expected this to work

```
where=reference like 'A%25'
```

However from a quick test that is giving an error. I've raised the issue with the Accounts team (I'm assuming that you're referring to the Sage 50 Accounts Sdata implementation).

The single character wildcard character (an underscore) seems to work OK so if all the references are of a standard length you could potentially workaround the issue by doing something along the lines of

```
where=reference like 'A_____'
```
Of course of the references are of variable length this might not be an effective workaround.

**Comment by geoffo** [comment]
Hi Darron, yes I am talking about the Sage 50 Accounts implementation.  

Thanks for raising this with the Accounts team and for the potential workaround, it may work in some cases.

**Comment by pncookson** [comment]
I've also tried everything to get this like working. It seems so buggy it's untrue. Was any of this tested at all or is that what I am doing now?

**Comment by darroncockram** [comment]
We do not release any software without testing. Unfortunately with something complex like the Sdata adapter where there a countless different ways in which it can be consumed and exercised bugs can slip through. This is true of all non-trivial software.

As noted above this particular issue has been passed to the Accounts team to be resolved and as part of the resolution the testing would also be enhanced to ensure this particular scenario is covered.

If you have any other issues please open an issue here and I will endeavour to assist as best I can.

**Comment by pncookson** [comment]
I’m sorry if my frustration comes through in my comment and I take your comment on board but surely something as basic as this should work out of the box. I’m just trying to get my software to look for a customer in sage by name. Unless the user types the name exactly then it doesn’t work.

**Comment by darroncockram** [comment]
That's OK I understand your frustration. It's rarely a good experience when something doesn't work as you expect and I can only apologise for this. I couldn't say how this issue managed to slip through in this case but it is on the Accounts team radar now and normal practice when addressing a bug would be to incorporate additional tests to ensure there is coverage going forwards.

I don't have an ETA for a fix yet I'm afraid but I will drop a message here as soon as I have something more concrete

**Comment by pncookson** [comment]
It's been a long week. I switched to using the post code in the end. lol. Thanks Darren. Have a good weekend.

**Comment by darroncockram** [comment]
Just heard from the Accounts team that a fix is being tested now. Still no ETA on a release for the fix but   I'll keep you posted.

**Comment by pncookson** [comment]
Thanks Darron

Sent from my Windows Phone
________________________________

**Comment by maloner** [comment]
Hi there - any update on this fix?

**Comment by darroncockram** [comment]
Doesn't look like it made it in to a patch for for the earlier versions but it was definitely fixed in the Accounts 2017 release.

**Comment by asterix187** [comment]
This is great. Is there any release notes that details what things have changes/been fixed in sData? That would be really useful!

**Comment by darroncockram** [comment]
The Accounts team don't publish release notes to that level of detail I'm afraid. There's just the high level "what's new" info but that is very feature-centric https://my.sage.co.uk/public/help/accounts/installation/sage50accountsupgrade.aspx. Having said that I don't think there were any other changes or fixes specific to Sdata in the 2017 release that I'm aware of.

**Comment by asterix187** [comment]
Thanks Darron (and sorry for hijacking the thread).

**Comment by darroncockram** [comment]
Issue fixed in 2017 release.
