### ISSUE TITLE
Adding tradingAccountFeedEntry then  request.RequestFeedEntry<tradingAccountFeedEntry>(company) causing duplicates.

### ISSUE THREAD

**Issue by pncookson** [Sage/SData-2.0#31]
Hi,
Firstly is this the only forum for sage sdata?  I'm using Sage Accounts v22.

I'm adding a tradingAccountFeedEntry which works fine.  But when I use request.RequestFeedEntry<tradingAccountFeedEntry>(company); to get an instance of the newly added company so I can get the reference used by sage it creates a duplicate company and returns the extra one. 

Any advice is very welcome.

Thanks in advance.

Paul

I'm using this code....

   public tradingAccountFeedEntry CreateCustomer(tradingAccountFeedEntry company)
        {
            SDataUri uri = new SDataUri(SageConnectionString + "tradingaccounts");

            SDataRequest request = new SDataRequest(uri.Uri, company, Sage.Integration.Messaging.Model.RequestVerb.POST);

            request.Username = SageUserName;
            request.Password = SagePassword;

            request.Send();

            // IF successful the POST operation will provide us with a the newly created sales customer
            if (request.IsStatusValidForVerb)
            {
                tradingAccountFeedEntry savedCustomer = new  tradingAccountFeedEntry() ; 
                request.RequestFeedEntry<tradingAccountFeedEntry>(savedCustomer);

                return savedCustomer ;
            }
            else
            {
                return null;
            }
        }

**Comment by pncookson** [comment]
I've found that by removing the request.send() and the if (request.IsStatusValidForVerb) etc it works.  Looks like request.RequestFeedEntry<tradingAccountFeedEntry>(savedCustomer); does the send.
Wow.

**Comment by darroncockram** [comment]
This is the only Sdata specific forum as far as I'm aware. 

That's correct behaviour. The Send method of the SDataRequest issues the request to the Sdata feeds but does not return the persisted resource (if any) whereas the RequestFeedEntry method issues the request and does return the persisted resource.

In this case you are creating a POST operation, issuing once by calling Send and then again by calling the RequestFeedEntry method so there are 2 requests to create a tradingAccount with the same details hence you end up with the duplicate.

All you need is a slight tweak to your code. Something like this should do the trick:

```
   public tradingAccountFeedEntry CreateCustomer(tradingAccountFeedEntry company)
        {
            SDataUri uri = new SDataUri(SageConnectionString + "tradingaccounts");

            SDataRequest request = new SDataRequest(uri.Uri, company, Sage.Integration.Messaging.Model.RequestVerb.POST);

            request.Username = SageUserName;
            request.Password = SagePassword;

            tradingAccountFeedEntry savedCustomer = new  tradingAccountFeedEntry();
            request.RequestFeedEntry<tradingAccountFeedEntry>(savedCustomer);

            // IF successful the POST operation will provide us with a the newly created sales customer
            if (request.IsStatusValidForVerb)
            {
                return savedCustomer ;
            }
            else
            {
                return null;
            }
        }

```

I did create some tutorial videos a while back around consuming Sdata feeds using the SIF that you can find here: http://www.youtube.com/playlist?list=PLF56D8511E5ABB680&feature=plcp. that you might find useful.

Hope that helps.

**Comment by pncookson** [comment]
Thanks Darren, thats very helpful. Easy when you know how.

**Comment by pncookson** [comment]
I've watched most of your video's Darren.  They are the only reason I have got anywhere at all.  Thanks again for your help.
