### ISSUE TITLE
Posting of Message (Commentary) line to Sage 50 changes nominal code

### ISSUE THREAD

**Issue by asterix187** [Sage/SData-2.0#34]
Hi, I am experiencing an issue where when posting a set of commodities to an order if a Commentary line is placed before a product the inherited (from product) nominal code is not used for the product line. 

An example is a set of lines (using Sage 50 demo data):

Order 1
BOARD001           4000
BOARD001           4000

Order 2
BOARD001           4000
M
BOARD001           4100

I have tried various settings etc and still cannot work out when a commodity line added after a message line does not inherit the product lines product nominal.

**Comment by darroncockram** [comment]
Looks like a bug. I'll raise it with the Accounts team. The only workaround at the moment would be to ensure that messages lines are only added after the product lines.

**Comment by asterix187** [comment]
This looks to be fixed in the newer versions of Sage 50. Thanks.
