### ISSUE TITLE
Create SalesInvoice with type Service Invoice

### ISSUE THREAD

**Issue by galimru** [Sage/SData-2.0#39]
Hi Darron!

I trying create SalesInvoice with type Service, but I can't do it.

I used a request below, but this creates invoice with a type Product Service.
```xml
<entry ...>  
	<sdata:payload>
		<crm:salesInvoice>
			<crm:type>Service Invoice</crm:type>
			<crm:tradingAccount sdata:uuid="0adf4e88-1235-403c-bc8d-b35138116924"/>       
		</crm:salesInvoice>
	</sdata:payload>
</entry>
```

POST http://localhost:5493/sdata/accounts50/GCRM/-/salesInvoices

How done right request?

P.S. Software is Sage 50 Accounts

**Comment by darroncockram** [comment]
That looks OK (well other than the fact you have no salesInvoiceLines lines, but that wouldn't stop you creating the invoice)
What version of Accounts are you using? From memory I think that support for service invoices was only enabled in the Sdata feeds with the 2015 version of Accounts.

**Comment by galimru** [comment]
I'm using Sage 50 Accounts 2013.
As I understand, this version too old.

Thanks!
