### ISSUE TITLE
Access to demo data

### ISSUE THREAD

**Issue by galimru** [Sage/SData-2.0#40]
Hi Darron!

Is there any way to get demo data through SData?

**Comment by asterix187** [comment]
If you add the demo data to Sage 50 as a company the data is exposed via the sData feed.

**Comment by galimru** [comment]
How I can add the data as company to Sage 50 Accounts 2013? 
I haven't found.

I need a test environment for developing without install new Sage instance.

**Comment by darroncockram** [comment]
The simplest thing would be to create a back up of demo data then create a new company and select to restore from the backup you created.

Hope that helps

**Comment by galimru** [comment]
Thanks!
