### ISSUE TITLE
View Nominal Ledger Data in Accounts 50

### ISSUE THREAD

**Issue by geoffo** [Sage/SData-2.0#41]
Is there a way to retrieve Nominal Ledger data via SData like what can be done using the Sage ODBC driver?  If so, can you please explain how this can be done?

**Comment by darroncockram** [comment]
Yes, the nominal ledger is exposed to Sdata (read only). It's the financialAccounts feed you need.

**Comment by geoffo** [comment]
Okay, thanks for pointing that out.  The ODBC driver has a lot of additional columns that I don't see available in SData such as PRIOR_* (i.e. PRIOR_YR_MTH1), BALANCE_* (i.e. BALANCE_MTH1), CREDIT_* (i.e. CREDIT_MTH1), among a few others.  How is this data able to be retrieved via SData?

**Comment by darroncockram** [comment]
That data isn't available via the Sdata feeds I'm afraid as there is no equivalent to it in the GCRM contract

**Comment by geoffo** [comment]
Thanks for explaining this Darron, I appreciate your help.
