### ISSUE TITLE
Multiple Dataset access crashes sData service in Sage 50

### ISSUE THREAD

**Issue by asterix187** [Sage/SData-2.0#45]
Hi,

We are experiencing an issue where when a dataset is queried and then the second data set is queried whilst it doesnt error the result from the query is blank or no results are returned. If we restart the sData service and run exactly the same query it then returns data correctly. This is happening on mulitple system and generally after large queries have been run. Is this something know and has anyone else experienced this?

Regards

Daniel

**Comment by darroncockram** [comment]
Can't say I've seen this before. Is there anything in the Windows event log to indicate what the error was?

**Comment by darroncockram** [comment]
Also, what queries are you issuing? I'll see if I can recreate it.

**Comment by darroncockram** [comment]
Closing question as no response.

**Comment by tazmon95** [comment]
I'm having the same issue.  Pitty this was closed without resolution...

**Comment by kieronmoran** [comment]
Hi Tazmon95

I work with Asterix187 and we became as frustrated as you.

We developed a .net Integration and our only solution was to programmatically restart the sData Service when switching DataSets.

It seems that the sData Service still queries the first dataset used even though you specify a different one. Hence the blank results. Restarting clears out this "memory" and, as you rightly say, allows a 2nd dataset to be used.

Hope this helps.

**Comment by kieronmoran** [comment]
In answer to Darron post about event logs, no there was nothing to indicate a problem.

**Comment by darroncockram** [comment]
The adapter does not cache anything so there is no good reason I can think of for it to query the wrong dataset. Do you have some example code/requests that replicates the issue?
