### ISSUE TITLE
Getting error while reading data from Sdata services

### ISSUE THREAD

**Issue by bagavan44** [Sage/SData-2.0#47]
When i try get the details of Product from Sage 100 ERP, i am getting the "Object reference not set to an instance of an object"  as a response. My request uri is like following http://sage100/sdata/masapp/mascontract/abc/CI_Item('SPL@#PRD'). Is it the problem with special characters? Other products are working fine.

**Comment by darroncockram** [comment]
I'm not familiar with the Sage 100 ERP implementation but if other products are working OK it will almost certainly be the special characters. Certainly some of the characters there have special meaning in a URL. You could try URL encoding the collection predicate.

**Comment by tudor06** [comment]
Hello,

In order to better help you, could you please let me know the product and the country you are working against? Sage has a number of different products sharing the same name but produced for different geographies.

With that information, I will be able to forward your query to the appropriate team.

Thanks!

**Comment by asterix187** [comment]
I would suggest you use URL encoding when calling the URI from within an app.

**Comment by bagavan44** [comment]
I have tried with URL encoding, still getting the same error. Requested url like following

http://sage100/sdata/masapp/MasContract/ABC/CI_Item('SPL%40%23PRD')
http://sage100/sdata/masapp/MasContract/ABC/CI_Item(ItemCode%20eq%20'SPL%40%23PRD')


Sage Version is : Sage 100 Advanced ERP 2015 (version 5.20.0.0) US.

**Comment by bagavan44** [comment]
I am able to read the data with the following alternate query http://sage100/sdata/masapp/MasContract/ABC/CI_Item?where=(ItemCode eq 'SPL%40%23PRD'). But I am unable to update the product details to sage. Because we have to give the item code in the resource selector property. There i have issue.

**Comment by asterix187** [comment]
I had the same issue and had to use XML encoding on the post/put.

Qmulus Solutions
Telephone: + 44 (0)845 450 3991│ Mobile: +44 (0)7584 300808 | DDI: +44 (0)1789 332131
Web: www.qmulus-solutions.com<http://www.qmulus-solutions.com/>
Twitter: @dannycrm

**Comment by bagavan44** [comment]
Where i can put that XML encoding. I am using the following library for communicating with Sdata services https://github.com/Sage/SDataCSharpClientLib

**Comment by asterix187** [comment]
We use the following code in a wrapper. We encode the json post to UTF8 prior to posting to sData. (single record update).


public string GetPUTResponse(sDataConnection sDataConnection, Qmulus.SageCRM.Helper.SageCRMEntity entity, string json, int recordid)

{

Request = (HttpWebRequest)WebRequest.Create(sDataConnection.BaseURI + Qmulus.Common.EnumHelper.GetDescription(entity) + "('" + recordid + "')");

try

{

Request.Headers.Add("Authorization", "Basic " + Base64AuthenticationString);

Request.Timeout = requestTimeout;

Request.Method = "PUT";

Request.ContentType = "application/json";


using (var streamWriter = new StreamWriter(Request.GetRequestStream(),Encoding.UTF8))

{

   streamWriter.Write(json);

}


var httpResponse = (HttpWebResponse)Request.GetResponse();

using (var streamReader = new StreamReader(httpResponse.GetResponseStream()))

{

   var result = streamReader.ReadToEnd();

   return result;

}

}

catch (Exception ex)

{

   SeverityLevel severityLevel = SeverityLevel.Critical;

   LogLevel logLevel = LogLevel.Event;

   throw new CustomException.CustomException(severityLevel, logLevel, ex.InnerException, "Error getting sData Response", Request);

}

}

For your post I would concentrate on encoding the post stream and then posting in your existing way.

**Comment by tudor06** [comment]
Hello,

It appears our US colleagues have a hot line to support such development cases. The number is 866-996-7243.
Should you continue having problems, you should contact them for assistance – they will certainly be able to help you further.

Regards!
