### ISSUE TITLE
Sage 50 Accounts - Create Product Invoice Line Items with Tax Amounts

### ISSUE THREAD

**Issue by geoffo** [Sage/SData-2.0#48]
Is it possible to create product invoice line items with tax amounts specified in the request?  Currently the tax amounts sent in the request are being ignored.  If we then open the Sage software and refresh the product invoice page, the tax amounts are calculated by sage based on the product information.  Are all tax amounts generated based on product specific information or is there a way to override the values when submitting an SData request?

**Comment by asterix187** [comment]
Hi, just to add we have experienced a similar issue except on our testing it appears to inherit the tax settings of the company the order/invoice is against.

**Comment by darroncockram** [comment]
The logic used for tax calculations used in the Sage 50 Accounts adapter are the same as those used in the main application. If you omit the tax code it will be automatically set based the settings for the product and/or customer and taking in to account any discounting rules in place.

You can override the tax code that should be used but not the calculations as these are core to the application. Best bet would be to use a tax code which has the appropriate % set already.

Hope that helps

**Comment by asterix187** [comment]
The problem I have found that is no matter what tax code you set for a line or order etc the code is not set and it just inherits the tax code from the company or product line.

**Comment by darroncockram** [comment]
What version of Accounts are you using?

**Comment by geoffo** [comment]
Thanks Darron, I have been able to specify a TaxCode (via the UUID) to override the default value.

**Comment by asterix187** [comment]
Hi Geoffo, could you please give an example of how you specified the tax code via UUID please. Thanks!

**Comment by geoffo** [comment]
Hey asterix187, below is an example for you.

`<entry xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:crm="http://schemas.sage.com/crmErp/2008" xmlns:sc="http://schemas.sage.com/sc/2009" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3.org/2005/Atom">
  <sdata:payload>
    <crm:salesInvoice>
      <crm:salesInvoiceLines>
        <crm:salesInvoiceLine>
          <crm:commodity sdata:uuid="e02599d7-9a2c-496e-9ff4-2dd479ebc468"></crm:commodity>
          <crm:quantity>3</crm:quantity>
          <crm:actualPrice>100</crm:actualPrice>
          <crm:grossTotal>120</crm:grossTotal>
          <crm:netTotal>110.00</crm:netTotal>
          <crm:text>SalesInvoiceTest</crm:text>
          <crm:taxCodes>
            <crm:taxCode sdata:uuid="56de6d09-0804-4936-b5c9-d5f65dcb2d00"></crm:taxCode>
          </crm:taxCodes>
        </crm:salesInvoiceLine>
      </crm:salesInvoiceLines>
      <crm:type>Product Invoice</crm:type>
      <crm:customerReference>CUST123</crm:customerReference>
      <crm:tradingAccount sdata:uuid="dd05a67a-c1dc-4851-96f3-43c37835019c"></crm:tradingAccount>
      <crm:active>true</crm:active>
    </crm:salesInvoice>
  </sdata:payload>
</entry>`

**Comment by asterix187** [comment]
Great thanks! I will give it a go!

**Comment by geoffo** [comment]
You're welcome, hope it helps!
