### ISSUE TITLE
Sage 50 Accounts NET & VAT Amounts Not Being Calculated Until Manual Refresh

### ISSUE THREAD

**Issue by geoffo** [Sage/SData-2.0#49]
When a product invoice is created, the NET and VAT amounts are not calculated until you login to the Sage software itself and perform a manual refresh (or do anything that causes the dialog to be refreshed).  Is there something else that needs to be done to ensure that the values get calculated properly without having to open the software and manually refresh it so the values get calculated?

Below are screenshots that demonstrate right after the invoice was created with SData and after a manual refresh.

After Invoice Created:
![after invoice created](https://cloud.githubusercontent.com/assets/11636766/14506683/05fd1b52-018d-11e6-9d63-8a233e9eabbe.jpg)

After Manual Refresh:
![after manual update](https://cloud.githubusercontent.com/assets/11636766/14506685/09002272-018d-11e6-813d-c41caa0ab8a3.jpg)

**Comment by darroncockram** [comment]
Going off memory they should be calculated automatically based on the values on the lines. Are you setting the netTotal, taxTotal and grossTotal for the lines when POSTing the salesInvoice?

**Comment by geoffo** [comment]
No, I am just setting Quantity and ActualPrice.  I have tried setting TaxTotal and GrossTotal as well but there was no change in behavior.

**Comment by geoffo** [comment]
We are also seeing a case where all invoice line items have a discount amount equal to their total gross value applied withing Sage after posting, until such time as a manual update that causes a refresh.  At this point the discounts disappear and the invoice values correct themselves.  Setting discount amount and percentage fields to various possibilities in the parent sales invoice does not affect this either.  So this issue appears to be with the invoice overall not being updated after a post via SData.

**Comment by darroncockram** [comment]
Just ran a very quick test with some code I had to hand and I am seeing the invoice totals populated. I'm using the SIF to do the heavy lifting but this is the resulting XML that is POSTed:

`<?xml version="1.0" encoding="utf-8"?>
<entry xmlns:atom="http://www.w3.org/2005/Atom" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cf="http://www.microsoft.com/schemas/rss/core/2005" xmlns="http://www.w3.org/2005/Atom" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:sme="http://schemas.sage.com/sdata/sme/2007" xmlns:sdatasync="http://schemas.sage.com/sdata/sync/2008/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:http="http://schemas.sage.com/sdata/http/2008/1">
  <author />
  <sdata:payload>
    <salesInvoice xmlns="http://schemas.sage.com/crmErp/2008">
      <active xsi:nil="true" />
      <reference xsi:nil="true" />
      <reference2 xsi:nil="true" />
      <status xsi:nil="true" />
      <allocationStatus xsi:nil="true" />
      <deliveryStatus xsi:nil="true" />
      <statusFlag xsi:nil="true" />
      <statusFlagText xsi:nil="true" />
      <type xsi:nil="true" />
      <tradingAccount sdata:url="http://sage015573:5493/sdata/Accounts50/GCRM/{C4C463BE-B098-4A7D-A23B-D1A92B8DCB59}/tradingAccountCustomer(be33197f-03c1-46e3-b789-5e078562b0c0)?format=atomentry" sdata:uuid="be33197f-03c1-46e3-b789-5e078562b0c0">
        <active>true</active>
        <customerSupplierFlag>Customer</customerSupplierFlag>
        <companyPersonFlag>Company</companyPersonFlag>
        <invoiceTradingAccount xsi:nil="true" />
        <openedDate>2013-01-02</openedDate>
        <reference>A1D001</reference>
        <reference2 xsi:nil="true" />
        <status>Open</status>
        <name>A1 Design ServicesX9</name>
        <shortName xsi:nil="true" />
        <type>Unknown</type>
        <registeredAddress xsi:nil="true" />
        <postalAddresses xsi:nil="true" />
        <shippingAddresses xsi:nil="true" />
        <billingAddresses xsi:nil="true" />
        <phones xsi:nil="true" />
        <emails xsi:nil="true" />
        <website>www.sage.co.uk</website>
        <contacts xsi:nil="true" />
        <deliveryContact xsi:nil="true" />
        <salesPersons xsi:nil="true" />
        <deliveryMethod xsi:nil="true" />
        <deliveryRule>true</deliveryRule>
        <currency>GBP</currency>
        <taxCode xsi:nil="true" />
        <taxReference>GB238 3839 38</taxReference>
        <taxationCountry>GB</taxationCountry>
        <useTaxInclusivePrices xsi:nil="true" />
        <financeBalance>12.98</financeBalance>
        <financeLimit>1000.00</financeLimit>
        <financeBalanceDate xsi:nil="true" />
        <financeStatusFlag>false</financeStatusFlag>
        <financeStatusText>Open</financeStatusText>
        <settlementDiscountType>Percent</settlementDiscountType>
        <settlementDiscountAmount xsi:nil="true" />
        <settlementDiscountPercent>2.50</settlementDiscountPercent>
        <settlementDiscountTerms>15</settlementDiscountTerms>
        <settlementDiscountTermsCommencement xsi:nil="true" />
        <settlementDiscountIncludedInTotal>true</settlementDiscountIncludedInTotal>
        <paymentTerms>30</paymentTerms>
        <paymentTermsCommencement xsi:nil="true" />
        <orderDiscountType xsi:nil="true" />
        <orderDiscountAmount xsi:nil="true" />
        <orderDiscountPercent xsi:nil="true" />
        <orderText1 xsi:nil="true" />
        <orderText2 xsi:nil="true" />
        <orderLineDiscountType xsi:nil="true" />
        <orderLineDiscountAmount xsi:nil="true" />
        <orderLineDiscountPercent>0.00</orderLineDiscountPercent>
        <orderLineText1 xsi:nil="true" />
        <orderLineText2 xsi:nil="true" />
        <invoiceDiscountType xsi:nil="true" />
        <invoiceDiscountAmount xsi:nil="true" />
        <invoiceDiscountPercent>0.00</invoiceDiscountPercent>
        <invoiceText1 xsi:nil="true" />
        <invoiceText2 xsi:nil="true" />
        <bankAccounts xsi:nil="true" />
        <tenderType xsi:nil="true" />
        <defaultFulfillmentLocation xsi:nil="true" />
        <pricelists xsi:nil="true" />
        <pricingOverride xsi:nil="true" />
        <accountingType xsi:nil="true" />
        <financialAccounts xsi:nil="true" />
        <primacyIndicator>true</primacyIndicator>
        <opportunities xsi:nil="true" />
        <salesQuotations xsi:nil="true" />
        <salesOrders xsi:nil="true" />
        <salesOrderDeliveries xsi:nil="true" />
        <salesInvoices xsi:nil="true" />
        <salesCredits xsi:nil="true" />
        <purchaseOrders xsi:nil="true" />
        <purchaseOrderDeliveries xsi:nil="true" />
        <receipts xsi:nil="true" />
        <interactions xsi:nil="true" />
        <projects xsi:nil="true" />
      </tradingAccount>
      <customerReference xsi:nil="true" />
      <opportunity xsi:nil="true" />
      <pricelist xsi:nil="true" />
      <copyFlag xsi:nil="true" />
      <date xsi:nil="true" />
      <time xsi:nil="true" />
      <taxDate xsi:nil="true" />
      <taxCodes>
        <taxCode sdata:uuid="59507cdb-5997-4ee8-92f5-14456e101c54">
          <notes xsi:nil="true" />
        </taxCode>
      </taxCodes>
      <postalAddresses xsi:nil="true" />
      <deliveryMethod xsi:nil="true" />
      <deliveryTerms xsi:nil="true" />
      <deliveryRule xsi:nil="true" />
      <deliveryDate xsi:nil="true" />
      <carrierCompany xsi:nil="true" />
      <carrierTradingAccount xsi:nil="true" />
      <carrierNetPrice>80.00</carrierNetPrice>
      <carrierTaxPrice>20.00</carrierTaxPrice>
      <carrierTotalPrice>100.00</carrierTotalPrice>
      <carrierSalesInvoice xsi:nil="true" />
      <carrierTaxCodes xsi:nil="true" />
      <carrierReference xsi:nil="true" />
      <currency xsi:nil="true" />
      <operatingCompanyCurrency xsi:nil="true" />
      <operatingCompanyCurrencyExchangeRate xsi:nil="true" />
      <operatingCompanyCurrencyExchangeRateOperator xsi:nil="true" />
      <operatingCompanyCurrencyExchangeRateDate xsi:nil="true" />
      <customerTradingAccountCurrency xsi:nil="true" />
      <customerTradingAccountCurrencyExchangeRate xsi:nil="true" />
      <customerTradingAccountCurrencyExchangeRateOperator xsi:nil="true" />
      <customerTradingAccountCurrencyExchangeRateDate xsi:nil="true" />
      <buyerContact xsi:nil="true" />
      <salespersons xsi:nil="true" />
      <salesInvoiceLines>
        <salesInvoiceLine>
          <originatorDocumentLine xsi:nil="true" />
          <active xsi:nil="true" />
          <reference xsi:nil="true" />
          <reference2 xsi:nil="true" />
          <status xsi:nil="true" />
          <type>Standard</type>
          <number xsi:nil="true" />
          <commodity sdata:uuid="ff991dcf-bd25-4d20-95db-813cc8dc86b9">
            <commodityGroup xsi:nil="true" />
            <commodityIdentifiers xsi:nil="true" />
            <unitOfMeasure xsi:nil="true" />
            <buyingUnitOfMeasure xsi:nil="true" />
            <sellingUnitOfMeasure xsi:nil="true" />
            <packingUnitOfMeasure xsi:nil="true" />
            <supplierTradingAccount xsi:nil="true" />
            <taxCodes xsi:nil="true" />
            <financialAccounts xsi:nil="true" />
            <replacement xsi:nil="true" />
            <associatedChildCommodities xsi:nil="true" />
            <associatedParentCommodity xsi:nil="true" />
            <interactions xsi:nil="true" />
            <opportunities xsi:nil="true" />
            <salesQuotationLines xsi:nil="true" />
            <salesOrderLines xsi:nil="true" />
            <salesOrderDeliveryLines xsi:nil="true" />
            <salesInvoiceLines xsi:nil="true" />
            <salesCreditLines xsi:nil="true" />
            <purchaseOrderLines xsi:nil="true" />
            <purchaseOrderDeliveryLines xsi:nil="true" />
            <pricelists xsi:nil="true" />
            <prices xsi:nil="true" />
          </commodity>
          <text xsi:nil="true" />
          <deliveryTerms xsi:nil="true" />
          <deliveryDate xsi:nil="true" />
          <carrierTradingAccount xsi:nil="true" />
          <carrierNetPrice xsi:nil="true" />
          <carrierTaxPrice xsi:nil="true" />
          <carrierTotalPrice xsi:nil="true" />
          <carrierSalesInvoiceLine xsi:nil="true" />
          <carrierTaxCodes xsi:nil="true" />
          <carrierReference xsi:nil="true" />
          <unitOfMeasure xsi:nil="true" />
          <quantity>2.00</quantity>
          <initialPrice xsi:nil="true" />
          <pricelist xsi:nil="true" />
          <settlementDiscountType xsi:nil="true" />
          <settlementDiscountAmount xsi:nil="true" />
          <settlementDiscountPercent xsi:nil="true" />
          <settlementDiscountTerms xsi:nil="true" />
          <invoiceLineDiscountType xsi:nil="true" />
          <invoiceLineDiscountAmount xsi:nil="true" />
          <invoiceLineDiscountPercent xsi:nil="true" />
          <invoiceLineSubtotalDiscountType xsi:nil="true" />
          <invoiceLineSubtotalDiscountAmount xsi:nil="true" />
          <invoiceLineSubtotalDiscountPercent xsi:nil="true" />
          <actualPrice xsi:nil="true" />
          <netTotal>50.00</netTotal>
          <chargesTotal xsi:nil="true" />
          <discountTotal xsi:nil="true" />
          <fOBPoint xsi:nil="true" />
          <taxCodes>
            <taxCode sdata:uuid="59507cdb-5997-4ee8-92f5-14456e101c54">
              <notes xsi:nil="true" />
            </taxCode>
          </taxCodes>
          <priceTax xsi:nil="true" />
          <taxTotal>10.00</taxTotal>
          <grossTotal>60.00</grossTotal>
          <costTotal xsi:nil="true" />
          <profitTotal xsi:nil="true" />
          <project xsi:nil="true" />
          <salesOrderDeliveryLines xsi:nil="true" />
          <receipts xsi:nil="true" />
          <financialAccounts xsi:nil="true" />
          <notes xsi:nil="true" />
        </salesInvoiceLine>
        <salesInvoiceLine>
          <originatorDocumentLine xsi:nil="true" />
          <active xsi:nil="true" />
          <reference xsi:nil="true" />
          <reference2 xsi:nil="true" />
          <status xsi:nil="true" />
          <type>Free Text</type>
          <number xsi:nil="true" />
          <commodity xsi:nil="true" />
          <text>An example product</text>
          <deliveryTerms xsi:nil="true" />
          <deliveryDate xsi:nil="true" />
          <carrierTradingAccount xsi:nil="true" />
          <carrierNetPrice xsi:nil="true" />
          <carrierTaxPrice xsi:nil="true" />
          <carrierTotalPrice xsi:nil="true" />
          <carrierSalesInvoiceLine xsi:nil="true" />
          <carrierTaxCodes xsi:nil="true" />
          <carrierReference xsi:nil="true" />
          <unitOfMeasure xsi:nil="true" />
          <quantity>5.00</quantity>
          <initialPrice xsi:nil="true" />
          <pricelist xsi:nil="true" />
          <settlementDiscountType xsi:nil="true" />
          <settlementDiscountAmount xsi:nil="true" />
          <settlementDiscountPercent xsi:nil="true" />
          <settlementDiscountTerms xsi:nil="true" />
          <invoiceLineDiscountType xsi:nil="true" />
          <invoiceLineDiscountAmount xsi:nil="true" />
          <invoiceLineDiscountPercent xsi:nil="true" />
          <invoiceLineSubtotalDiscountType xsi:nil="true" />
          <invoiceLineSubtotalDiscountAmount xsi:nil="true" />
          <invoiceLineSubtotalDiscountPercent xsi:nil="true" />
          <actualPrice xsi:nil="true" />
          <netTotal>100.00</netTotal>
          <chargesTotal xsi:nil="true" />
          <discountTotal xsi:nil="true" />
          <fOBPoint xsi:nil="true" />
          <taxCodes>
            <taxCode sdata:uuid="59507cdb-5997-4ee8-92f5-14456e101c54">
              <notes xsi:nil="true" />
            </taxCode>
          </taxCodes>
          <priceTax xsi:nil="true" />
          <taxTotal>20.00</taxTotal>
          <grossTotal>120.00</grossTotal>
          <costTotal xsi:nil="true" />
          <profitTotal xsi:nil="true" />
          <project xsi:nil="true" />
          <salesOrderDeliveryLines xsi:nil="true" />
          <receipts xsi:nil="true" />
          <financialAccounts xsi:nil="true" />
          <notes xsi:nil="true" />
        </salesInvoiceLine>
        <salesInvoiceLine>
          <originatorDocumentLine xsi:nil="true" />
          <active xsi:nil="true" />
          <reference xsi:nil="true" />
          <reference2 xsi:nil="true" />
          <status xsi:nil="true" />
          <type>Commentary</type>
          <number xsi:nil="true" />
          <commodity xsi:nil="true" />
          <text>A message line created via Sdata</text>
          <deliveryTerms xsi:nil="true" />
          <deliveryDate xsi:nil="true" />
          <carrierTradingAccount xsi:nil="true" />
          <carrierNetPrice xsi:nil="true" />
          <carrierTaxPrice xsi:nil="true" />
          <carrierTotalPrice xsi:nil="true" />
          <carrierSalesInvoiceLine xsi:nil="true" />
          <carrierTaxCodes xsi:nil="true" />
          <carrierReference xsi:nil="true" />
          <unitOfMeasure xsi:nil="true" />
          <quantity xsi:nil="true" />
          <initialPrice xsi:nil="true" />
          <pricelist xsi:nil="true" />
          <settlementDiscountType xsi:nil="true" />
          <settlementDiscountAmount xsi:nil="true" />
          <settlementDiscountPercent xsi:nil="true" />
          <settlementDiscountTerms xsi:nil="true" />
          <invoiceLineDiscountType xsi:nil="true" />
          <invoiceLineDiscountAmount xsi:nil="true" />
          <invoiceLineDiscountPercent xsi:nil="true" />
          <invoiceLineSubtotalDiscountType xsi:nil="true" />
          <invoiceLineSubtotalDiscountAmount xsi:nil="true" />
          <invoiceLineSubtotalDiscountPercent xsi:nil="true" />
          <actualPrice xsi:nil="true" />
          <netTotal xsi:nil="true" />
          <chargesTotal xsi:nil="true" />
          <discountTotal xsi:nil="true" />
          <fOBPoint xsi:nil="true" />
          <taxCodes xsi:nil="true" />
          <priceTax xsi:nil="true" />
          <taxTotal xsi:nil="true" />
          <grossTotal xsi:nil="true" />
          <costTotal xsi:nil="true" />
          <profitTotal xsi:nil="true" />
          <project xsi:nil="true" />
          <salesOrderDeliveryLines xsi:nil="true" />
          <receipts xsi:nil="true" />
          <financialAccounts xsi:nil="true" />
          <notes xsi:nil="true" />
        </salesInvoiceLine>
      </salesInvoiceLines>
      <lineCount xsi:nil="true" />
      <originatorDocument xsi:nil="true" />
      <salesOrderDeliveries xsi:nil="true" />
      <receipts xsi:nil="true" />
      <contract xsi:nil="true" />
      <settlementDiscountType xsi:nil="true" />
      <settlementDiscountAmount xsi:nil="true" />
      <settlementDiscountPercent xsi:nil="true" />
      <settlementDiscountTerms xsi:nil="true" />
      <settlementDiscountIncludedInTotal xsi:nil="true" />
      <invoiceDiscountType xsi:nil="true" />
      <invoiceDiscountAmount xsi:nil="true" />
      <invoiceDiscountPercent xsi:nil="true" />
      <invoiceAdditionalDiscount1Type xsi:nil="true" />
      <invoiceAdditionalDiscount1Amount xsi:nil="true" />
      <invoiceAdditionalDiscount1Percent xsi:nil="true" />
      <invoiceAdditionalDiscount2 xsi:nil="true" />
      <invoiceAdditionalDiscount2Amount xsi:nil="true" />
      <invoiceAdditionalDiscount2Percent xsi:nil="true" />
      <netTotal xsi:nil="true" />
      <discountTotal xsi:nil="true" />
      <chargesTotal xsi:nil="true" />
      <taxTotal xsi:nil="true" />
      <grossTotal xsi:nil="true" />
      <costTotal xsi:nil="true" />
      <profitTotal xsi:nil="true" />
      <text1 xsi:nil="true" />
      <text2 xsi:nil="true" />
      <projects xsi:nil="true" />
      <financialAccounts xsi:nil="true" />
      <interactions xsi:nil="true" />
      <user xsi:nil="true" />
      <notes xsi:nil="true" />
      <CustomerId>0001-01-01T00:00:00.000+00:00</CustomerId>
      <paymentDue xsi:nil="true" />
    </salesInvoice>
  </sdata:payload>
</entry>`

Not sure why you don't see the same results as I do but if you capture the XML you are POSTing we can compare and see if anything stands out.

**Comment by geoffo** [comment]
Hi Darron, below is the xml that I am POSTing

<entry xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:crm="http://schemas.sage.com/crmErp/2008" xmlns:sc="http://schemas.sage.com/sc/2009" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3.org/2005/Atom">
  <sdata:payload>
    <crm:salesInvoice>
      <crm:salesInvoiceLines>
        <crm:salesInvoiceLine>
          <crm:commodity sdata:uuid="e02599d7-9a2c-496e-9ff4-2dd479ebc468"></crm:commodity>
          <crm:quantity>3</crm:quantity>
          <crm:actualPrice>100</crm:actualPrice>
          <crm:grossTotal>120</crm:grossTotal>
          <crm:text>SalesInvoiceTest</crm:text>
        </crm:salesInvoiceLine>
        <crm:salesInvoiceLine>
          <crm:commodity sdata:uuid="0a47b43d-7115-4863-9689-1a53666e67c8"></crm:commodity>
          <crm:quantity>1</crm:quantity>
          <crm:actualPrice>0.99</crm:actualPrice>
          <crm:text>My Second Item</crm:text>
        </crm:salesInvoiceLine>
      </crm:salesInvoiceLines>
      <crm:type>Product Invoice</crm:type>
      <crm:customerReference>CUST123</crm:customerReference>
      <crm:tradingAccount sdata:uuid="dd05a67a-c1dc-4851-96f3-43c37835019c"></crm:tradingAccount>
      <crm:active>true</crm:active>
      <crm:postalAddresses>
        <sc:postalAddress>
          <sc:name>Sales Order Delivery Address</sc:name>
          <sc:type>Shipping</sc:type>
          <sc:address1>123 Main St</sc:address1>
          <sc:townCity>MyCity</sc:townCity>
          <sc:stateRegion>NY</sc:stateRegion>
        </sc:postalAddress>
        <sc:postalAddress>
          <sc:name>Sales Order Billing Address</sc:name>
          <sc:type>Billing</sc:type>
          <sc:address1>987 Center Road</sc:address1>
        </sc:postalAddress>
      </crm:postalAddresses>
    </crm:salesInvoice>
  </sdata:payload>
</entry>

**Comment by darroncockram** [comment]
It's the netTotal that's the key. This works:

`<?xml version="1.0" encoding="utf-8"?>
<entry xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:crm="http://schemas.sage.com/crmErp/2008" xmlns:sc="http://schemas.sage.com/sc/2009" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3.org/2005/Atom">
	<sdata:payload>
		<crm:salesInvoice>
			<crm:salesInvoiceLines>
				<crm:salesInvoiceLine>
					<crm:commodity sdata:uuid="ff991dcf-bd25-4d20-95db-813cc8dc86b9"/>
					<crm:quantity>3</crm:quantity>
					<crm:netTotal>100</crm:netTotal>
					<crm:grossTotal>120</crm:grossTotal>
					<crm:text>SalesInvoiceTest</crm:text>
				</crm:salesInvoiceLine>
				<crm:salesInvoiceLine>
					<crm:commodity sdata:uuid="6f54bf25-2725-47a6-a870-c751c6c9bff4"/>
					<crm:quantity>1</crm:quantity>
					<crm:netTotal>0.99</crm:netTotal>
					<crm:text>My Second Item</crm:text>
				</crm:salesInvoiceLine>
			</crm:salesInvoiceLines>
			<crm:type>Product Invoice</crm:type>
			<crm:customerReference>CUST123</crm:customerReference>
			<crm:tradingAccount sdata:uuid="be33197f-03c1-46e3-b789-5e078562b0c0"/>
			<crm:active>true</crm:active>
			<crm:postalAddresses>
				<sc:postalAddress>
					<sc:name>Sales Order Delivery Address</sc:name>
					<sc:type>Shipping</sc:type>
					<sc:address1>123 Main St</sc:address1>
					<sc:townCity>MyCity</sc:townCity>
					<sc:stateRegion>NY</sc:stateRegion>
				</sc:postalAddress>
				<sc:postalAddress>
					<sc:name>Sales Order Billing Address</sc:name>
					<sc:type>Billing</sc:type>
					<sc:address1>987 Center Road</sc:address1>
				</sc:postalAddress>
			</crm:postalAddresses>
		</crm:salesInvoice>
	</sdata:payload>
</entry>`

**Comment by geoffo** [comment]
Thanks Darron, setting NetTotal caused the amounts to be calculated upon POSTing without having to perform a manual refresh.
