### ISSUE TITLE
Sage 50 Accounts Create Invoice Line Items with Discount Amounts

### ISSUE THREAD

**Issue by geoffo** [Sage/SData-2.0#50]
I am trying to specify a discount amount for invoice line items, however the discount amounts sent in the request are being ignored.  Is there a way to specify discount amounts that will actually be applied?  Maybe there are some specific settings that must be set for them to take affect?  Any help you can provide would be appreciated.

**Comment by darroncockram** [comment]
Again this is from memory but I believe that the Accounts adapter applies the same discounting rules as the application but you can set whatever netTotal, taxTotal and grossTotal that you want on the request so you could always calculate the discount to be applied and subtract it accordingly before POSTing.

Hope that helps.
