### ISSUE TITLE
Unable to retrieve JSON formated responses

### ISSUE THREAD

**Issue by hamster503** [Sage/SData-2.0#52]
I am trying to utilize the SData 2.0 specification, namely getting back json formatted responses from our Sage instance.  Following the Sage 100 ERP installation guide, I was able to successfully test my local Sage 100 SData installation with Atom formatted responses.  Using [cURL](https://curl.haxx.se/download.html), I tried both the HTTP Accept header approach (**Accept: application/json;vnd.sage=sdata**) and the format query parameter (**?format=application/json;vnd.sage=sdata**) and neither one gives me back JSON, always Atom formated responses.

Is there a specific install I need to run in order to get the SDATA 2.0 working? I have installed Sage 100 Standard ERP 2015.  I checked the **Enable Native SData Provider and Access with Role Maintenance** and I installed the **Sage 100 ERP Native SData Provider Adapter**.  

Thank you for any assistance you can provide.

**Comment by darroncockram** [comment]
I don't think that the Sage 100 ERP implements the Sdata 2.0 standard. Pretty sure it only implements the 1.1 standard I'm afraid

**Comment by hamster503** [comment]
That was what I was afraid of.  Thanks for the information!
