### ISSUE TITLE
Shipping Addresses - Incorrect?

### ISSUE THREAD

**Issue by RKBad** [Sage/SData-2.0#53]
Hi,
I'm using Sage L50 UK, V22. Using the url http://Localhost:5493/sdata/Accounts50/GCRM/-/postalAddresses?where=applicationId eq '37665'
I get the output below:
![postaladdrs](https://cloud.githubusercontent.com/assets/19502768/15453956/f2882eb4-2021-11e6-8c3b-1739ff25cf1e.PNG)
The name field in both shipping/billing should (I think!) be the first line of the addresses and description field should be "Invoice Address/Invoice Delivery Address", if not so how do I obtain the first line of both addresses?

**Comment by darroncockram** [comment]
Not sure if I've misunderstood the question or not. The name property holds the name/type of the  address e.g. 'Invoice Delivery Address'  whereas the description contains the description of the address e.g. 'Head Office'. If you want the first line of the address it's the address1 property you want.

If you only want the address1 property returned you can use the select parameter e.g.
http://Localhost:5493/sdata/Accounts50/GCRM/-/postalAddresses?where=applicationId eq '37665'&select=address1

Hope that helps.

**Comment by RKBad** [comment]
Please see below
![billing](https://cloud.githubusercontent.com/assets/19502768/15454658/54db5658-2037-11e6-8d07-340961e84891.PNG)
![delivery](https://cloud.githubusercontent.com/assets/19502768/15454659/56edd3c6-2037-11e6-8aaa-932e27ed9e47.PNG)
I'm trying to locate "Billing Name/Shipping Name" from the invoice as shown. address1 returns "Billing L1/Shipping L1".
Thanks.

**Comment by darroncockram** [comment]
Ah, you mean the delivery name. That's not exposed to the Sdata feeds I'm afaid.

**Comment by RKBad** [comment]
OK, thanks for your time. It does seem to be a pretty large omission though!

**Comment by asterix187** [comment]
I agree! this is causing me no end of hassle. I have had to write an SDO web service wrapper to expose this (and line item comment lines).

**Comment by darroncockram** [comment]
I'l pass on the request to the Accounts team include it in the Sdata feeds.

**Comment by RKBad** [comment]
Thanks for that.

**Comment by Artful-dodger** [comment]
so @asterix187 is it possible to make a wrapper to expose the audit splits as my project is on hold till I figure out a way to link all transationActivities with nominal codes. do you have an example?

**Comment by asterix187** [comment]
Hi, yes but you will need to use SDO (Sage Data Objects) which will require an SDO key for both your dev machine and the clients (unless you are the client). We do this in part by extending the class that uses sData. Somethings ike the below:

`ConnectSDO(username, password, companyPath);
                SopRecord sdoSalesOrderRecord = (SopRecord)oWS.CreateObject("SopRecord");
                sdoSalesOrderRecord.Fields.Item("ORDER_NUMBER").Value = orderReference;
                if (sdoSalesOrderRecord.Find(false))
                {
                    sdoSalesOrderRecord.Fields.Item("DELIVERY_NAME").Value = deliveryName;
                    sdoSalesOrderRecord.Update();
                }
                sdoSalesOrderRecord = null;`

`public bool ConnectSDO(string sage50username, string sage50password, string sageCompanyDataPath)
        {          
            oSDO.Workspaces.Clear();
            oWS = (WorkSpace)oSDO.Workspaces.Add("xxx" + DateTime.Now.Millisecond);
            if (!SDOConnected)
            {
                try
                {
                    oWS.Connect(sageCompanyDataPath, sage50username, sage50password, oWS.Name);
                    SDOConnected = true;
                }
                catch (Exception ex)
                {
                    SDOConnected = false;
                    oWS = null;
                }
            }
            return SDOConnected;
        }`

One issue with this though is that you need to include the SageDataObjectxxx.dll based on the version of Sage 50 you use which, unlike sData, means you need to rebuild it for each new version. This is why we tend to use this as a referenced webservice rather than coding into the sData adaptor.

**Comment by Artful-dodger** [comment]
Thank you @asterix187 by the way yesterday https://communities.sage.co.uk/ideas/i/sage_50_accounts/ advised they would look into exposing Audit split but it may take up to 18 months

**Comment by asterix187** [comment]
Wow, we will all be on oData for Sage 50 or Sage Live by then!

**Comment by markayling** [comment]
Sorry to resurrect an old thread, but @asterix187 did you manage to get the code above to work?  I am trying to do the exact same thing but upon calling .Update() I get an "illegal mode for update" error.  Any ideas?

TIA
