### ISSUE TITLE
Trading Accounts with orders

### ISSUE THREAD

**Issue by asterix187** [Sage/SData-2.0#54]
Hi, Not really an issue, more an assistance request. 

Is it possible to return a set of trading accounts via sData where more than x orders have been placed on the account. 

I was hoping something like:

http://localhost:5493/sdata/accounts50/gcrm/-/tradingaccounts?count=1&include=salesorders&where=salesOrders.totalResults gt 1

I could get the fill list the sub query but it would be nice to filter in the one call if possible.

Thanks

**Comment by darroncockram** [comment]
Afraid not. Sdata doesn't provide a mechanism for summing/grouping in it's query language. The best you could do would be to query against the tradingAccounts feed, include salesOrders and then remove any unwanted tradingAccounts from the results (i.e. those with zero orders) in your consumer.

Hope that helps

**Comment by asterix187** [comment]
Ok no worries.
