### ISSUE TITLE
TaxCoded updated date

### ISSUE THREAD

**Issue by asterix187** [Sage/SData-2.0#55]
Hi, the tax codes updated date always shows the date the feed was queries not the actual updated date of the tax code.

**Comment by darroncockram** [comment]
I suspect that will be because the main Accounts application does not track changes to tax codes but I'll confirm with the Accounts team.

**Comment by darroncockram** [comment]
The Accounts team have confirmed my suspicions. The created and update dates are not tracked in the main application for tax codes so the dates presented in the Sdata feeds for taxCodes are always the current date/time.

**Comment by asterix187** [comment]
Ok, thanks for finding out Darron :)
