### ISSUE TITLE
Sage 50 UK: Setting tax code on new tradingAccount

### ISSUE THREAD

**Issue by asterix187** [Sage/SData-2.0#56]
Is it possible to set the tax code on new trading accounts? the account.taxCode has a type of TaxCodeFeed but when I set it to any feed containing a tax code it doesn't get applied and causes an error. At present all tax codes get set to the default tax code (normally T1) but I need to be able to set it to, for example T0, for foreign accounts.

Thanks

**Comment by darroncockram** [comment]
Doesn't look like this is supported in the Sdata feeds at the moment I'm afraid. I've logged a request with the Accounts team though.

**Comment by asterix187** [comment]
:( that is disappointing. Thanks for logging it though.
