### ISSUE TITLE
Proforma Orders

### ISSUE THREAD

**Issue by asterix187** [Sage/SData-2.0#57]
Hi, It appears that proforma orders are not exposed via sData. Is there anyway of creating and orders and then switching its type to a pro forma order to get sData to create pro forma orders?

Thanks

**Comment by darroncockram** [comment]
Unfortunately not. The invoice/order type isn't exposed to the Sdata feeds so, whilst you can create an invoice or order via the salesInvoices and salesOrders feeds respectively  you would be unable to change the type to proforma.

As ever I can pass the request on the Accounts team but can't promise if/when it might get picked up for implementation I'm afraid.
