### ISSUE TITLE
Sage 50 Sdata invoices

### ISSUE THREAD

**Issue by davidhendrickmb** [Sage/SData-2.0#58]
Hi,
I'm trying to use the Sage 50 SDATA service to create customers and invoices. 
I've managed to create customers no problem, but am getting the "object reference not set to an instance of an object message" when I try to post an invoice. 
Below is a simple example I'm trying to post. 
Not sure if and what I should set on the trading account and if I'm setting the line items correctly.
I've omitted the login details here.
Any help would be greatly appreciated. 
Thanks,
David

`var service = new SDataService();

            // set user name to authenticate with
            service.UserName = "";
            // set password to authenticate with
            service.Password = "";

            service.Protocol = "HTTP";
            service.ServerName = "localhost:5493";
            service.ApplicationName = "accounts50";
            service.VirtualDirectory = "sdata";

            AtomFeed feed;
            AtomEntry entry;
            AtomEntry lineEntry;
            SDataPayload payload;
            SDataPayload linePayload;
            // read the template for accounts
            var tru1 = new SDataTemplateResourceRequest(service);
            tru1.ContractName = "GCRM";
            tru1.ResourceKind = "salesInvoices";

            // read the entry from the server
            entry = service.ReadEntry(tru1);

            // TODO: Make changes to the entry payload
            payload = entry.GetSDataPayload();
            payload.Values["CustomerId"] = "GRANDDUN";
            payload.Values["type"] = "Product Invoice";
            payload.Values["customerReference"] = "";
            payload.Values["settlementDiscountAmount"] = "0";
            payload.Values["settlementDiscountPercent"] = "0";
            payload.Values["settlementDiscountTerms"] = "0";
            payload.Values["invoiceDiscountAmount"] = "0";
            payload.Values["invoiceDiscountPercent"] = "0";
            payload.Values["netTotal"] = "0";
            payload.Values["taxTotal"] = "0";
            payload.Values["grossTotal"] = "0";

            var tsol = new SDataTemplateResourceRequest(service);
            tsol.ContractName = "GCRM";
            tsol.ResourceKind = "salesInvoiceLines";
            lineEntry = service.ReadEntry(tsol);
            linePayload = lineEntry.GetSDataPayload();
            linePayload.Values["quantity"] = "1";
            linePayload.Values["type"] = "0";
            linePayload.Values["number"] = "1";
            linePayload.Values["initialPrice"] = "0";
            linePayload.Values["invoiceLineDiscountAmount"] = "0";

            linePayload.Values["actualPrice"] = "0";
            linePayload.Values["netTotal"] = "0";
            linePayload.Values["discountTotal"] = "0";
            linePayload.Values["taxTotal"] = "0";
            linePayload.Values["grossTotal"] = "0";

            
            payload.Values["salesInvoiceLines"] = linePayload.Values;
            entry.SetSDataPayload(payload);

            var sru1 = new SDataSingleResourceRequest(service);
            sru1.ContractName = "GCRM";
            sru1.ResourceKind = "salesInvoices";

            var newEntry = service.CreateEntry(sru1, entry);
            SDataPayload newEntryPayload = newEntry.GetSDataPayload();
            return "";`

**Comment by darroncockram** [comment]
You're right that you'd need to set the tradingAccount property. At the very least it would need to include the UUID of the tradingAccount as this is what links the invoice to the customer (the CustomerId is an extension property that is ignored in the POST).

Looks like you're using the SDataCSharpClientLib there. I'm not too familiar with it so I'm not sure on the syntax you'd need but here's a working example that uses the SIF that demonstrates how to create a salesInvoice that you may find useful.

```c#
using System;
using System.Collections.Generic;
using System.Text;
using Sage.Common.Syndication;
using Sage.crmErp.x2008.Feeds;
using Sage.Integration.Client;

namespace CreateSalesInvoice
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create a new instance of a salesInvoice
			salesInvoiceFeedEntry salesInvoice = new salesInvoiceFeedEntry();

            // Find a customer to associate with the new sales invoice
            salesInvoice.tradingAccount = GetCustomer();

            if (salesInvoice.tradingAccount == null)
            {
                // No customer record means we can go no further
                Console.WriteLine("Unable to find a customer record");
                Console.ReadKey(true);
                return;
            }

            // Lookup a commodity to use on the new sales invoice
            commodityFeedEntry commodity = GetCommodity();
            if(commodity == null)
            {
				// No commodity record means we go no further
                Console.WriteLine("Unable to find a commodity record");
                Console.ReadKey(true);
                return;
            }
			commodityFeedEntry commodityReference = new commodityFeedEntry();
			commodityReference.UUID = commodity.UUID;

			// Lookup a commodity to use on the new sales invoice
			taxCodeFeedEntry taxCode = GetTaxCode();
			if (taxCode == null)
			{
				// No record means we go no further
				Console.WriteLine("Unable to find a tax code record");
				Console.ReadKey(true);
				return;
			}

			// Example of creating a historical invoice
			//salesInvoice.date = salesInvoice.taxDate = DateTime.UtcNow.AddDays(-2);

            // NOTE: This example omits the use of tax code for brevity.
            // Not specifying tax codes means that appropriate defaults will be used automatically.
            // However it is strongly recommended that tax codes are explicitly set to ensure expected results
			taxCodeFeedEntry taxReference = new taxCodeFeedEntry();
			taxReference.UUID = taxCode.UUID;

			salesInvoice.taxCodes = new taxCodeFeed();
			salesInvoice.taxCodes.Entries.Add(taxReference);

			salesInvoice.carrierTotalPrice = 100;
			salesInvoice.carrierTaxPrice = 20;
			salesInvoice.carrierNetPrice = 80;

            // Create a new sale invoice line using the commodity we just looked up
            salesInvoiceLineFeedEntry orderLine = new salesInvoiceLineFeedEntry();
            orderLine.type = "Standard";
            orderLine.text = commodity.description;
			orderLine.commodity = commodityReference;
            orderLine.quantity = 2;
            orderLine.netTotal = 50;
            orderLine.taxTotal = 10;
            orderLine.grossTotal = 60;
			orderLine.taxCodes = new taxCodeFeed();
			orderLine.taxCodes.Entries.Add(taxReference);

            // Create another invoice line this time as free text
            salesInvoiceLineFeedEntry freetextOrderLine = new salesInvoiceLineFeedEntry();
            freetextOrderLine.type = "Free Text"; // Equivalent to S1 stock code
            freetextOrderLine.text = "An example product";
            freetextOrderLine.quantity = 5;
            freetextOrderLine.netTotal = 100;
            freetextOrderLine.taxTotal = 20;
            freetextOrderLine.grossTotal = 120;
			freetextOrderLine.taxCodes = new taxCodeFeed();
			freetextOrderLine.taxCodes.Entries.Add(taxReference);

			// Create a 3rd invoice line this time as a message
			salesInvoiceLineFeedEntry messageOrderLine = new salesInvoiceLineFeedEntry();
			messageOrderLine.type = "Commentary"; // Equivalent to M stock code
			messageOrderLine.text = "A message line created via Sdata";


            // Associate the lines with our invoice
            salesInvoice.salesInvoiceLines = new salesInvoiceLineFeed();
            salesInvoice.salesInvoiceLines.Entries.Add(orderLine);
            salesInvoice.salesInvoiceLines.Entries.Add(freetextOrderLine);
			salesInvoice.salesInvoiceLines.Entries.Add(messageOrderLine);

            // Now we have constructed our new invoice we can submit it using the HTTP POST verb  
            Sage.Common.Syndication.SDataUri salesInvoiceUri = new Sage.Common.Syndication.SDataUri();
            salesInvoiceUri.BuildLocalPath("Accounts50", "GCRM", "-", "salesInvoices");

            SDataRequest invoiceRequest = new SDataRequest(salesInvoiceUri.Uri, salesInvoice, Sage.Integration.Messaging.Model.RequestVerb.POST);
            invoiceRequest.Username = "MANAGER";
            invoiceRequest.Password = "";

            // IF successful the POST operation will provide us with a the newly created sales invoice
            salesInvoiceFeedEntry savedSalesInvoice = new salesInvoiceFeedEntry();
            invoiceRequest.RequestFeedEntry<salesInvoiceFeedEntry>(savedSalesInvoice);

            if (invoiceRequest.IsStatusValidForVerb)
            {
                Console.WriteLine(string.Format("Successfully created sales invoice {0}", savedSalesInvoice.reference));
            }
            else
            {
                // There was a problem
                Console.WriteLine("Create failed. Response was {0}", invoiceRequest.HttpStatusCode.ToString());
				if (invoiceRequest.Diagnoses != null)
				{
					foreach (Diagnosis diagnosis in invoiceRequest.Diagnoses)
						Console.WriteLine(diagnosis.Message);
				}
            }

            Console.ReadKey(true);
        }

        static tradingAccountFeedEntry GetCustomer()
        {
            // Look up the first customer record 
            Sage.Common.Syndication.SDataUri accountUri = new Sage.Common.Syndication.SDataUri();
            accountUri.BuildLocalPath("Accounts50", "GCRM", "-", "tradingAccounts");
            accountUri.Where = "customerSupplierFlag eq 'Customer'";
            accountUri.Count = 1;

            SDataRequest accountRequest = new SDataRequest(accountUri.Uri);
			accountRequest.AllowPromptForCredentials = false;
            accountRequest.Username = "MANAGER";
            accountRequest.Password = "";

            tradingAccountFeed accounts = new tradingAccountFeed();
            accountRequest.RequestFeed<tradingAccountFeedEntry>(accounts);

            // If we found a customer record return it
            if (accountRequest.IsStatusValidForVerb && accounts.Entries != null && accounts.Entries.Count > 0)
                return accounts.Entries[0];
            else
            {
                // There was a problem
                Console.WriteLine("Account lookup failed. Response was {0}", accountRequest.HttpStatusCode.ToString());
				if (accountRequest.Diagnoses != null)
				{
					foreach(Diagnosis diagnosis in accountRequest.Diagnoses)
						Console.WriteLine(diagnosis.Message);
				}

                return null;
            }
        }

        static commodityFeedEntry GetCommodity()
        {
            // Look up the first commodity (product) record 
            Sage.Common.Syndication.SDataUri commodityUri = new Sage.Common.Syndication.SDataUri();
            commodityUri.BuildLocalPath("Accounts50", "GCRM", "-", "commodities");
            commodityUri.Count = 1;

            SDataRequest commodityRequest = new SDataRequest(commodityUri.Uri);
            commodityRequest.Username = "MANAGER";
            commodityRequest.Password = "";

            commodityFeed commodities = new commodityFeed();
            commodityRequest.RequestFeed<commodityFeedEntry>(commodities);

            // If we found a record return it
            if (commodityRequest.IsStatusValidForVerb && commodities.Entries != null && commodities.Entries.Count > 0)
                return commodities.Entries[0];
            else
            {
                // There was a problem
                Console.WriteLine("Commodity lookup failed. Response was {0}", commodityRequest.HttpStatusCode.ToString());
				if (commodityRequest.Diagnoses != null)
				{
					foreach (Diagnosis diagnosis in commodityRequest.Diagnoses)
						Console.WriteLine(diagnosis.Message);
				}

                return null;
            }
        }

		static taxCodeFeedEntry GetTaxCode()
		{
			// Look up the tax code record 
			Sage.Common.Syndication.SDataUri taxCodeUri = new Sage.Common.Syndication.SDataUri();
			taxCodeUri.BuildLocalPath("Accounts50", "GCRM", "-", "taxCodes");
			taxCodeUri.Where = "reference eq 'T1'";
			
			SDataRequest taxcodeRequest = new SDataRequest(taxCodeUri.Uri);
			taxcodeRequest.Username = "MANAGER";
			taxcodeRequest.Password = "";

			taxCodeFeed taxcodes = new taxCodeFeed();
			taxcodeRequest.RequestFeed<taxCodeFeedEntry>(taxcodes);

			// If we found a customer record return it
			if (taxcodeRequest.IsStatusValidForVerb && taxcodes.Entries != null && taxcodes.Entries.Count > 0)
				return taxcodes.Entries[0];
			else
			{
				// There was a problem
				Console.WriteLine("Tax code lookup failed. Response was {0}", taxcodeRequest.HttpStatusCode.ToString());
				if (taxcodeRequest.Diagnoses != null)
				{
					foreach (Diagnosis diagnosis in taxcodeRequest.Diagnoses)
						Console.WriteLine(diagnosis.Message);
				}

				return null;
			}
		}
    }
}
```

**Comment by davidhendrickmb** [comment]
Thanks Darron.
I managed to get this working in the end pulling in a feed, similar to how you have done it.
I couldn't get the SIF working as I have VS2015, is there a version compatible with this?
Is it possible to specify the nominal code to use in the message?
Thanks,
David

**Comment by darroncockram** [comment]
The SIF can be used from  Visual Studio. 2015 but there isn't a plugin for that version to help auto generate the resourse and feed classes. I typically work around that by generating the helper classes in VS 2013 and simply upgrade the solution afterwards.

**Comment by davidhendrickmb** [comment]
Ok thanks. Are there instructions for setting that up?

**Comment by darroncockram** [comment]
Best bet in terms of instructions would be this series of instruction videos on consuming Sdata feeds: https://www.youtube.com/playlist?list=PLF56D8511E5ABB680&feature=plcp. It's video number 2 that covers setting up the helper classes.

**Comment by davidhendrickmb** [comment]
Thanks Darren. I was wondering if you could tell me what field corresponds to "Details" in a sales invoice line item? I'd like to set the text in that but can't seem to find the field.
Thank you.

**Comment by davidhendrickmb** [comment]
Or failing that is there anywhere I can store a note, even on the invoice? I've tried to create a note already on the invoice, but I'm not sure what to set for reference2 and if that would cause issues.
I need to store a few lines of text that is used to produce the PDF print.
Thanks.

**Comment by darroncockram** [comment]
> I was wondering if you could tell me what field corresponds to "Details" in a sales invoice line item? I'd like to set the text in that but can't seem to find the field.

Details on an invoice line in Accounts covers multiple fields. Do you mean 'Description'? If so it's the text property that you need to set. Bear in mind though that if you are associating a commodity to the line the commodity description will override any value you set in the text field.

> Or failing that is there anywhere I can store a note, even on the invoice? I've tried to create a note already on the invoice, but I'm not sure what to set for reference2 and if that would cause issues.
> I need to store a few lines of text that is used to produce the PDF print.

Sounds like perhaps you mean a commentary line (a message line line Accounts parlance). For this you just need to set the type property to Commentary and the text property to whatever message you want to include on the invoice (there's an example of this in the above code snippet).

Hope that helps.

**Comment by davidhendrickmb** [comment]
Hi Darron,
When you enter a line item against an invoice there is a details field as
well as a description field. It's also there for a service invoice I
believe though I'm using product as I believe service isn't supported until
2015 and we are on 2014.
Thanks
David

**Comment by davidhendrickmb** [comment]
By the way the details field is multi line, hence why I need that over the
description one. I need to pass a few lines of text up.

**Comment by darroncockram** [comment]
The details field on a service item can only be set indirectly. Both the description and details values in Accounts are set via the text property. You can include carriage returns by simply embedding them in the value you set the text property e.g.

serviceOrderLine.text = "An example\r\n service description"

Product items do not have a details field so message lines would be the best way to handle it if you need  to include additional info on product invoices.

**Comment by davidhendrickmb** [comment]
Thanks Darren. On the invoice line when I tried to include more characters
it didn't save as there seems to be a short number available. How many
characters can a comment line support?

**Comment by darroncockram** [comment]
I'm going off memory here but I think the limit is 60 character.

**Comment by davidhendrickmb** [comment]
Hi Darron,
I need to support more than this, hence why I'd like to use the details
field as it is multi line.
Thanks
David

**Comment by darroncockram** [comment]
The only other option would be to message lines I'm afraid.

**Comment by davidhendrickmb** [comment]
Hi Darron,
See below the details field I mean. As you can see, this isn't populating at all for me.

![image](https://cloud.githubusercontent.com/assets/18259436/16797380/2b8eb774-48df-11e6-81f2-b8feba58af25.png)

**Comment by davidhendrickmb** [comment]
I can work around this by using various notes.
One bug I encountered is that when I create an invoice, it doesn't bring across the VAT number on the invoice. Do I need to set this somewhere on invoice creation? I expected it to pull from the customer.
Thanks,
David

**Comment by darroncockram** [comment]
> See below the details field I mean. As you can see, this isn't populating at all for me.

Ah you are using 'service' commodities on a product invoice as opposed to  a service item on a service invoice. Looks like there is an issue there where the description is not making it through from the Sdata feeds in that scenario. I'll pass that on to the Accounts team.
In the meantime the only workaround would be to use a commentary (message) line to include any extra detail needed.

**Comment by darroncockram** [comment]
> One bug I encountered is that when I create an invoice, it doesn't bring across the VAT number on the invoice. Do I need to set this somewhere on invoice creation? I expected it to pull from the customer.

Do you mean the Tax code? If so this should be set to whatever tax code is specified when you POST the invoice. If one is not included the tax code will be automatically inherited from the commodity (product) record unless tradingAccount (customer) has an override set.

**Comment by davidhendrickmb** [comment]
Hi Darron,
Sorry, I mean the VAT_REG_NUMBER field in S50. I assumed it would populate from the company as it does when you create one from the interface, but I must be missing something. Any ideas?
Thanks,
David

![image](https://cloud.githubusercontent.com/assets/18259436/16833178/fe936914-49a5-11e6-85db-9c5c8699a592.png)

**Comment by darroncockram** [comment]
That screen shot is from Report Designer which is somewhat off topic for this forum but all the default layouts display the VAT number from the customer record not from the invoice record so as long as there is a VAT reg number already set on the customer it will be shown on he invoice when it is printed regardless of what is set on the invoice.
