### ISSUE TITLE
commodities feed error is no data returned

### ISSUE THREAD

**Issue by asterix187** [Sage/SData-2.0#60]
Hi, we have found a weird issue with Sage 50 sData when a where clause is used against the commodities sData feed and no data is returned. For example if the following url is used for a system with no updated commodities it errors : http://localhost:5493/sdata/accounts50/gcrm/-/commodities?select=%27uuid%27&precedence=0&where=updated%20gt%20@2016-08-08T09:00:00@

![commodities not working](https://cloud.githubusercontent.com/assets/7346013/17474836/eefe9920-5d4f-11e6-9f5c-f650b8197844.png)

Whereas is the updated date is set back a month to before a commodities is changed then it doesnt error : http://localhost:5493/sdata/accounts50/gcrm/-/commodities?select=%27uuid%27&precedence=0&where=updated%20gt%20@2016-07-08T09:00:00@

![commodities working](https://cloud.githubusercontent.com/assets/7346013/17474835/eee35b92-5d4f-11e6-8ea5-4eb9806d44d2.png)

It also writes multiple entries to the windows event log indicating an issue with the sData service.

**Comment by darroncockram** [comment]
Looks like its not just commodities. It happens on a number of other feeds too. It's definitely incorrect behaviour - the Sdata specification states:

> If the query executes successfully but does not select any resources, it MUST return a success code: 200 with an empty feed (or 304 if caching applies). This is not an error and it would be incorrect to return a 404 status in this case.

I'll raise it as a bug with the Accounts team
