### ISSUE TITLE
Sage 50 Accounts Create SalesOrder Line Items with Discount Percentages

### ISSUE THREAD

**Issue by geoffo** [Sage/SData-2.0#61]
I am attempting to create a SalesOrder with Line Items that contain a Discount Percentage.  When we submit the discount percentage, it is sent in the request correctly.  If I open the Sage Software itself and view the line item, it correctly shows the Discount Percentage.  However when I use the SData API to retrieve the line item, the value is incorrect (it actually seems to be returning the DiscountAmount value instead).  

Here is the request data for these two fields:
```
<crm:orderLineDiscountAmount>46.9744</crm:orderLineDiscountAmount>
<crm:orderLineDiscountPercent>68</crm:orderLineDiscountPercent>
```

Here is the response data for these fields:
```
"orderLineDiscountAmount": 46.97,
"orderLineDiscountPercent": 46.9744,
```

Any idea why the orderLineDiscountPercent is incorrect when returned via SData?

**Comment by darroncockram** [comment]
It's possible that what you are seeing in the UI is not actually what is persisted in the data. When you view a sales order in the Sage 50 Accounts UI  (I'm assuming that's the Sdata provider you are using) it refreshes the calculation results for line discounts fror display purposes so this might not necessarily match up with what is actually stored in the data. Conversely the Sdata feeds simply surface the raw details from the data files. If you execute a direct query against the data files e.g. via SDO or the ODBC driver I suspect you will see the data matches that shown in the Sdata feeds.

**Comment by geoffo** [comment]
Thanks Darron.  Can you explain why I send an orderLineDiscountPercent amount but a different amount is stored in the actual data?

**Comment by darroncockram** [comment]
The discount amount and discount percent are both functions of each other and both are affected by the various pricing and discounting rules provided by Sage 50 Accounts so my guess is that they are being recalculated due to one or more of these rules.

**Comment by geoffo** [comment]
Thanks Darron.  It seems that this is just how the Sage software works then as we are sending everything correctly in the request.
