### ISSUE TITLE
Invoice with multiple lines

### ISSUE THREAD

**Issue by TawTeuf** [Sage/SData-2.0#62]
Hello,
I am new to sage 50 sdata. I have gone through different comments from this blog and now I have begin to  understand how to make invoices using sdata through c#. My Problem is that how can i input multiple items on the same  invoice.

My Code is : 
 public void AddInvoice()
        {
            salesInvoiceFeedEntry salesInvoice = new salesInvoiceFeedEntry();

            // Find a customer to associate with the new sales invoice
            salesInvoice.tradingAccount = GetCustomer();

            if (salesInvoice.tradingAccount == null)
            {
                // No customer record means we can go no further
                Console.WriteLine("Unable to find a customer record");
                Console.ReadKey(true);
                return;
            }

            string strProdCode = "";
            salesInvoiceLineFeedEntry orderLine = new salesInvoiceLineFeedEntry();
         
            salesInvoice.salesInvoiceLines = new salesInvoiceLineFeed();

  

            SDataRequest invoiceRequest = null;

            for (int i = 0; i < 2; i++)
            {
                if (i == 0)
                    strProdCode = "P001";
                else
                    strProdCode = "P002";

                // Lookup a commodity to use on the new sales invoice
                commodityFeedEntry commodity = GetCommodity(strProdCode);
                if (commodity == null)
                {
                    // No commodity record means we go no further
                    Console.WriteLine("Unable to find a commodity record");
                    Console.ReadKey(true);
                    return;
                }
                commodityFeedEntry commodityReference = new commodityFeedEntry();
                commodityReference.UUID = commodity.UUID;

                // Lookup a commodity to use on the new sales invoice
                taxCodeFeedEntry taxCode = GetTaxCode();
                if (taxCode == null)
                {
                    // No record means we go no further
                    Console.WriteLine("Unable to find a tax code record");
                    Console.ReadKey(true);
                    return;
                }

                taxCodeFeedEntry taxReference = new taxCodeFeedEntry();
                taxReference.UUID = taxCode.UUID;

                salesInvoice.taxCodes = new taxCodeFeed();
                salesInvoice.taxCodes.Entries.Add(taxReference);
                /*
                salesInvoice.carrierTotalPrice = 100;
                salesInvoice.carrierTaxPrice = 20;
                salesInvoice.carrierNetPrice = 80;
                 * 
                 * 
                */

                if (i == 0)
                {
                    orderLine.type = "Standard";
                    orderLine.text = commodity.description;
                    orderLine.commodity = commodityReference;
                    orderLine.quantity = 2;
                    orderLine.netTotal = 50;
                    orderLine.taxTotal = 10;
                    orderLine.grossTotal = 60;
                    orderLine.taxCodes = new taxCodeFeed();
                    orderLine.taxCodes.Entries.Add(taxReference);
                }
                else
                {
                    orderLine.type = "Standard";
                    orderLine.text = commodity.description;
                    orderLine.commodity = commodityReference;
                    orderLine.quantity = 5;
                    orderLine.netTotal = 100;
                    orderLine.taxTotal = 10;
                    orderLine.grossTotal = 110;
                    orderLine.taxCodes = new taxCodeFeed();
                    orderLine.taxCodes.Entries.Add(taxReference);
                }

                salesInvoice.salesInvoiceLines.Entries.Add(orderLine);
              

            }

                // Now we have constructed our new invoice we can submit it using the HTTP POST verb  
                Sage.Common.Syndication.SDataUri salesInvoiceUri = new Sage.Common.Syndication.SDataUri();
                salesInvoiceUri.BuildLocalPath("Accounts50", "GCRM", "-", "salesInvoices");

                invoiceRequest = new SDataRequest(salesInvoiceUri.Uri, salesInvoice, Sage.Integration.Messaging.Model.RequestVerb.POST);
                invoiceRequest.Username = "MANAGER";
                invoiceRequest.Password = "";
            
           

                // IF successful the POST operation will provide us with a the newly created sales invoice
                salesInvoiceFeedEntry savedSalesInvoice = new salesInvoiceFeedEntry();
                invoiceRequest.RequestFeedEntry<salesInvoiceFeedEntry>(savedSalesInvoice);
               

                if (invoiceRequest.IsStatusValidForVerb)
                {
                    Console.WriteLine(string.Format("Successfully created sales invoice {0}", savedSalesInvoice.reference));
                    

                }
                else
                {
                    // There was a problem
                    LogSyncErr("", "", "", "", "");

                }
            

                Console.ReadKey(true);
            
            

           
        }

its always saving the last product ( 2 lines with same item)

**Comment by darroncockram** [comment]
Looking at that code I'd fully expect it to be creating an invoice with 2 items every time. You have a for loop that will run for 2 iterations (you've hard coded this). In the for loop you are adding a line on each iteration with this line:

`salesInvoice.salesInvoiceLines.Entries.Add(orderLine);`

If you want to add more lines you need to construct further salesInvoiceLine instances, set the appropriate details on them and add them to the salesInvoice.salesInvoiceLines.Entries as per the above line.

Hope that helps.

**Comment by asterix187** [comment]
Hi, This is because of the way you are adding the lines to the invoice object. You first need to add the lines to the lines feed then once all the lines are in the feed assign the feed to the lines collection.

Something like:

salesInvoiceFeedEntry salesInvoice = new salesInvoiceFeedEntry();
salesInvoiceLinesFeed orderLines = new salesInvoiceLineFeed();

 for (int i = 0; i < 2; i++)
 {
      string strProdCode = "";
      salesInvoiceLineFeedEntry orderLine = new salesInvoiceLineFeedEntry();
      if (i == 0)
            strProdCode = "P001";
      else
            strProdCode = "P002";

      orderLine.type = "Standard";
      orderLine.text = commodity.description;
      orderLine.commodity = commodityReference;
      orderLine.quantity = 2;
      orderLine.netTotal = 50;
      orderLine.taxTotal = 10;
      orderLine.grossTotal = 60;

      salesInvoiceLinesFeed.Entries.Add(orderLine);
}

salesInvoice.salesInvoiceLines = salesInvoiceLinesFeed;
   

Obviously not working but you should get the principal.

**Comment by TawTeuf** [comment]
Thanks you....will try it and revert back if i am having some issues



Sent from my Samsung device


-------- Original message --------
