### ISSUE TITLE
Sage 50 Accounts - Create negative values on invoices

### ISSUE THREAD

**Issue by geoffo** [Sage/SData-2.0#68]
In version 23, it is now possible to add negative lines to invoices: https://my.sage.co.uk/public/help/askarticle.aspx?articleid=14130

It seems there are special steps required to perform this within the application.  So what is the process in SData to add negative lines to a sales invoice?

**Comment by asterix187** [comment]
Its very likely you can't. It Sage 50 v22 you can mark products as inactive but they still show as active in Sage 50 sData regardless of settings.

**Comment by darroncockram** [comment]
Unfortunately negative value invoice lines aren't supported in the Accounts 50 Sdata adapter. I'll pass the request on to the Accounts team though.

**Comment by geoffo** [comment]
Okay, thanks asterix187 and Darron, I appreciate the responses.  I will just mark as closed since this is not available yet.
