### ISSUE TITLE
Method will not be invoked

### ISSUE THREAD

**Issue by jkischel** [Sage/SData-2.0#7]
I have made a simple "hello world" method in VB that just should return a message string via the Application Server. Unfortunately, it won't get invoked by calling it via soap.

I configured my server in .config file as http://localhost/seife/, the service is named Lagerverwaltung. My Method is named HelloWorld. According to the .pdf file on your home page, my guess was to call it this way: http://localhost:7777/seife/Lagerverwaltung/HelloWorld/ -- but nothing happens. As I added a test output to a local file, it's simply not invoked.

Unfortunately, C# is not of the programming languages I can code, so is there any sample "Hello World" template which can be triggered by a browser and returns a simple string in a SOAP XML?

**Comment by darroncockram** [comment]
This question doesn't appear to be related to Sdata.SOAP and Sdata are two completely different protocols.  I'm not sure what PDF you are referring to but documentation on Sdata can be found here: http://sage.github.io/SData-2.0/.

Hope that helps.

**Comment by darroncockram** [comment]
Closing issue as not Sdata related
