### ISSUE TITLE
Unable to retrieve objects from "RealTimeData" in Sage OfficeLine Evolution 2015

### ISSUE THREAD

**Issue by ThomasReinhardt** [Sage/SData-2.0#70]
Hi,
Am I supposed to query "RealTimeData" in OL with SData? When I do a HTTP GET at https://test-sage-003:5493/sdata/ol/RealTimeData/OLDemoReweAbfD;123/dtsBDELogbuch.Sage.PPS the response is a HTTP/1.1 500 Internal Server Error with body:

> `<diagnoses xmlns="http://schemas.sage.com/sdata/2008/1">
>     <diagnosis>
>         <severity>error</severity>
>         <sdataCode/>
>         <applicationCode/>
>         <message>Object reference not set to an instance of an object.</message>
>         <stackTrace>   at Sagede.Shared.RealTimeData.Core.Handlers.DataSourceHandler.FromDataSource(String dataSourceKey, AppConfigRequest requestParams, ApplicationContext context, IRealTimeDataCore core)
>    at Sagede.OfficeLine.ControlCenter.SDataService.RealTimeDataResourceHandler.GetList(SDataRequest request)</stackTrace>
>     </diagnosis>
> </diagnoses>`

Adding query parameters startIndex=0&count=10 does not change the response.

The ATOM fragment indicates this resource as a collection and I should be able to fetch those the way I am trying:

> `<entry>
>   <id>https://test-sage-003:5493/sdata/ol/RealTimeData/OLDemoReweAbfD;123/dtsBDELogbuch.Sage.PPS</id>
>   <title type="text">dtsBDELogbuch.Sage.PPS</title>
>   <updated>2016-09-08T12:24:54Z</updated>
>   <link
>       href="https://test-sage-003:5493/sdata/ol/RealTimeData/OLDemoReweAbfD;123/dtsBDELogbuch.Sage.PPS"
>       rel="self" type="application/atom+xml;type=entry"/>
>   <link
>       href="https://test-sage-003:5493/sdata/ol/RealTimeData/OLDemoReweAbfD;123/dtsBDELogbuch.Sage.PPS"
>       rel="alternate" type="application/atom+xml;type=entry"/>
>   <category label="Collection"
>       scheme="http://schemas.sage.com/sdata/categories" term="collection"/>
>   <content type="text">dtsBDELogbuch</content>
> </entry>`

I should say this is a test installation so maybe the error code is just complaining about something completely unrelated.

**Comment by asterix187** [comment]
Hi, I have no clue on OL sData but have seen this before with other sData systems when no data is available to is returned. Can you add a /$schema and query the schema of the feed correctly?

**Comment by ThomasReinhardt** [comment]
Wow, impressive response time :)

Yes, a GET on .../$schema gives a valid looking result (only relevant section quoted):

> `<xs:element name="dtsBDELogbuch.Sage.PPS" sme:canGet="true"
>         sme:hasTemplate="false" sme:label="dtsBDELogbuch"
>         sme:pluralName="dtsBDELogbuch.Sage.PPS" sme:role="resourceKind" type="dtsBDELogbuch.Sage.PPS--type"/>
>     <xs:complexType name="dtsBDELogbuch.Sage.PPS--type">
>         <xs:all>
>             <xs:element minOccurs="0" name="Benutzer" nillable="true"
>                 sme:precedence="5" type="xs:string"/>
>             <xs:element minOccurs="0" name="DatumZeit" nillable="true"
>                 sme:precedence="3" type="xs:dateTime"/>
>             <xs:element minOccurs="0" name="Fehlercode" nillable="true"
>                 sme:precedence="0" type="xs:integer"/>
>             <xs:element minOccurs="0" name="Fehlertext" nillable="true"
>                 sme:precedence="4" type="xs:string"/>
>             <xs:element minOccurs="0" name="Funktion" nillable="true"
>                 sme:precedence="2" type="xs:string"/>
>             <xs:element minOccurs="0" name="Konvertername"
>                 nillable="true" sme:precedence="1" type="xs:string"/>
>             <xs:element minOccurs="0" name="Konvertertyp"
>                 nillable="true" sme:precedence="0" type="xs:string"/>
>             <xs:element minOccurs="0" name="LogID" nillable="true"
>                 sme:precedence="0" type="xs:integer"/>
>             <xs:element minOccurs="0" name="Mandant" nillable="true"
>                 sme:precedence="0" type="xs:integer"/>
>         </xs:all>
>     </xs:complexType>
>     <xs:complexType name="dtsBDELogbuch.Sage.PPS--list">
>         <xs:sequence>
>             <xs:element maxOccurs="unbounded" minOccurs="0"
>                 name="dtsBDELogbuch.Sage.PPS" type="dtsBDELogbuch.Sage.PPS--type"/>
>         </xs:sequence>
>     </xs:complexType>`

**Comment by asterix187** [comment]
I would suggest then it 'should' be query-able. I have a slightly similar issue with the Sage 50 UK feeds. 

https://github.com/Sage/SData-2.0/issues/60

I guess the key similarity is the object reference not set error when queried that should at least return a no data feed rather than an error. 

Sorry I can't help more, I don't have an OfficeLine system to test on.

**Comment by ThomasReinhardt** [comment]
Ok thank you for your input. I'll try to get my hands on a system with actual data in it. Hopefully you are right and the "no data" case is just broken.

**Comment by ThomasReinhardt** [comment]
I tried with another object (also from RealTimeData contract) with definitely holds data. Same result. I suspect this is either not implemented at all or I misunderstand how to use it. Can someone with more insight than me try to get some data out of this contract please?
