### ISSUE TITLE
Invoice date changes after creation

### ISSUE THREAD

**Issue by dankennedy** [Sage/SData-2.0#73]
I've had this report from a person in our Accounts team where we're using SData to create purchase orders and sales invoices.

"They are originally created with the correct date and then once the invoices are in the purchase order screen you have to do ‘Place Orders’ then ‘Receive Deliveries’ in both of these the dates are fine but then when we do ‘Update Ledgers’ to send them to their own correct account it changes the date to today for example."

Can you think of a reason why this might happen?  This is how I'm creating the purchase order where transactionDate is the correct date.

`return new purchaseOrderFeedEntry
            {
                tradingAccount = account,
                customerReference = account.reference,
                reference = orderReference,
                purchaseOrderLines = new purchaseOrderLineFeed(),
                deliveryDate = transactionDate,
                date = transactionDate,
                dueDate = transactionDate
            };
`

**Comment by dankennedy** [comment]
Bump?

**Comment by darroncockram** [comment]
That's not how Sage 50 Accounts works. It's the same for purchase orders created in the UI.

**Comment by dankennedy** [comment]
Is there a way to post the purchase order directly to the trading account then without going through the Place Orders - Receive Deliveries flow?

**Comment by darroncockram** [comment]
That is the process used by the application. It's just how it's designed I'm afraid. Using SDO, the product specific SDK, it is possible to post directly transactions directly to the audit trail (i.e. the transactions that would result from the place order -> receive order process) but unfortunately this is not currently possible via the Sdata adataper as it only exposes a limited part of the audit trail and even then its in a read-only form.

**Comment by dankennedy** [comment]
Understood Darron. Thanks for the response.
