### ISSUE TITLE
termsAgreed - tradingAccountSummaries vs tradingAccountCustomer

### ISSUE THREAD

**Issue by malard** [Sage/SData-2.0#74]
Hi,

I am trying to programmatically create tradingAccounts into sage accounts50, I can POST/PUT etc without issue, although having to use atom as i get a 415 error if i use JSON, anyway thats besides the point.

If I POST a new tradingAccountCustomer the account is created in sage without the "termsAgreed" flag set to true, I cannot see in the schema this property, nor can I see any reference to it if i reflect the Sage.Integration.Accounts50.SDO.Adapter.GCRM.Feeds.dll , infact the only reference I can find to it is in the tradingAccountSummaries feed, but this feed is read only.

How do I programmatically set "termsAgreed" via sdata? or is this an oversight in the feed schema and it should be exposed in tradingAccountCustomer?

Thanks

**Comment by asterix187** [comment]
Hi, unfortunately this is not a field that can be set. We have found quite a few as the whole SDO framework is not exposed.

________________________________

**Comment by malard** [comment]
"we" as in Sage, or "we" as the company you work for?

Regardless, do you have a list of fields that cannot be set?

**Comment by asterix187** [comment]
We as in the company I work for. The available fields are shown by querying the $schema for the object. I don't have a specific document detailing what's not available.

________________________________

**Comment by darroncockram** [comment]
We (Sage) do not maintain a list of fields that cannot be set as SDO and the GCRM contract are unrelated technologies. As @asterix187 mentions you can determine the list of supported fields in the sData feeds by querying the $schema endpoint. As he also mentions it is unfortunately not possible to set the terms agreed flag via the sData feeds you would need to use SDO if you wish to set that field.

**Comment by malard** [comment]
Hi,

Thanks for the clarification, what is SDO? And why can you not permit termsAgreed via GCRM, could you make it possible and add it to the schema for tradeAccountCustomer?

Thanks

**Comment by darroncockram** [comment]
SDO is Sage Data Objects, the product-specific software development kit for Sage 50 Accounts. You must be a member of the 3rd party developer programme to access SDO.

The terms agreed fields is a product-specific concept and as there is no similar concept for it within the GCRM contract. The sData standard does allow for extension properties and resource kinds (in fact that is exactly what the tradingAccountSummaries feed is) but it is entirely up to the implementation of the provider as to what it exposes and unfortunately in this case the Accounts team have not chosen to expose  that field in a writable form.

**Comment by malard** [comment]
I looked into the developer program, but given this is an internal tool i am writing, i found it a bit rich to be asked for £1500 per annum to get access to this, the fact i accessing sdata over the network is a boon and wanted to carry on this way.

I guess i will have to solve it another way.
