### ISSUE TITLE
Accounts 50 - Only a single Sales Invoice record is being returned

### ISSUE THREAD

**Issue by geoffo** [Sage/SData-2.0#75]
We are seeing a case where only a single Sales Invoice record is being returned when making an SData call.  In the software itself, there are many sales invoices.  However when making a call like the below example, only a single record is returned.

http://localhost:5493/sdata/accounts50/GCRM/{232D6BE4-119A-4EDD-B5FB-EA4D1ADC2302}/salesInvoices?count=1000&include=postalAddresses,tradingAccount,buyerContact

Has anyone seen this behavior before?  The URL itself is correct so I'm not sure why SData would only be returning a single record.  Any ideas?

**Comment by darroncockram** [comment]
No good reason I can think of off the top of my head to return only 1 record if there are more in the dataset. Just tested this using the demo data and it is returning all the records for me. Are you sure the dataset you are connecting to definitely has more than one record? What happens if you drop the includes?

**Comment by geoffo** [comment]
I ran the same query without the includes and it is still only returning a single record.  Any other ideas in how to troubleshoot this?

http://localhost:5493/sdata/accounts50/GCRM/{232D6BE4-119A-4EDD-B5FB-EA4D1ADC2302}/salesInvoices?count=1000

**Comment by darroncockram** [comment]
A few things you could try:

Confirm the Sdata dataset is definitely the same dataset you are viewing in the Accounts UI. Try making a change to the invoice via the Accounts UI (e.g. change) the date and then re-issue the query against the Sdata feeds. Do you then see the change?

Create another dataset and add multiple invoices to it. Do these all appear in the Sdata feeds for that dataset?

Backup and restore the data to a different PC. Do all of the invoices appear if you issue the Sdata query against the other PC?

**Comment by geoffo** [comment]
Thanks for the responses Darron.  The issue was with how the customer was storing records in Sage.  They needed to call a different endpoint to retrieve the records they were storing.  So everything is working well.
