### ISSUE TITLE
Is it possible to create Batch Supplier Invoice?

### ISSUE THREAD

**Issue by binish007** [Sage/SData-2.0#79]
Is it possible to create Batch Supplier Invoice?

Basically, we are using ecommerse site to create purchase invoices and sales invoices.
Once these are created they needs to pushed to Sage for accounting purposes.
Please could you provide some sample codes..

**Comment by darroncockram** [comment]
I assume this is Sage 50 Accounts we are referring to? If so then the batch invoice facility is not exposed via the Sdata feeds as there is no matching concept in the GCRM contract I'm afraid.

**Comment by binish007** [comment]
Okay.. thanks for the confirmation.. We have managed to create sales invoice (not using batch invoicing). Is there any alternative option available to create Purchase invoicing please?

**Comment by darroncockram** [comment]
Afraid not. The Sage 50 Accounts main application only supports the concept of batch purchase invoices which posts directly to the audit trail. There is no equivalent to this in the GCRM contract so there is nothing exposed to the Sdata feeds that you could use to generate a purchase invoice I'm afraid.

**Comment by jasond-s** [comment]
@darroncockram Appreciate that this is closed, but this is where searching online leads you to if you have a similar issue. 

Is there any way to do this now? Or maybe create an expense? Can we, or should we, use SDO if we want to do this? 

Would be helpful if we could get a short answer of where to look for alternative solutions/examples, it must be possible to create PI type records in Sage 50 Accounts somehow, we would really appreciate some guidance for best practice.
