### ISSUE TITLE
How to retrieve memos from Product records

### ISSUE THREAD

**Issue by geoffo** [Sage/SData-2.0#8]
How do I retrieve memos from product records (commodities)? Looking at the schema information, I don't currently see any field related to memos.

**Comment by darroncockram** [comment]
Unfortunately it's not possible to do currently. The GCRM contract doesn't define a notes property on the commodity type.

**Comment by geoffo** [comment]
Okay, thanks for the response.  Is support for memos going to be added anytime in the future?

**Comment by darroncockram** [comment]
I'm not aware of any plans but I'll definitely feed it back to the team.

**Comment by geoffo** [comment]
Alright, thanks Darron I appreciate your help
