### ISSUE TITLE
Accounts 50 - Deleted Flag Not Usable in SDATA

### ISSUE THREAD

**Issue by tazmon95** [Sage/SData-2.0#83]
Hello,  I've been working on creating an analytics platform using the SData api and need a way to filter out transactions which have been deleted.  I see the flag present, however the values are always set to "false" when viewing the tradingActivities data.  However when looking at the same data in the Sage 50 Accounts application, 1500 records are deleted.  

I've tried adding in a filter for the deleted part of the record but the filter doesn't seem to work.  Filters on the other columns do work.  

`~/sdata/accounts50/GCRM/-/tradingActivities?where=transactionType eq 'SC' and Deleted eq 'false'`

Here is the error when the Deleted column is included in the query.

```<diagnosis xmlns="http://schemas.sage.com/sdata/2008/1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:sdatasync="http://schemas.sage.com/sdata/sync/2008/1" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:sme="http://schemas.sage.com/sdata/sme/2007" xmlns:http="http://schemas.sage.com/sdata/http/2008/1">
    <sdata:severity>error</sdata:severity>
    <sdata:sdataCode>ApplicationDiagnosis</sdata:sdataCode>
    <sdata:applicationCode />
    <sdata:message>GET operation failed - Object reference not set to an instance of an object.

   at Sage.Integration.Accounts50.SDOAdapter.SDORequestHandler.OnGetRequest(IRequest request, IFeed feed)
   at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.OnGetRequest(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.GetRequest(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.OnGetResource(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.GetRequest(IRequest request) (-1)</sdata:message>
    <sdata:stackTrace />
    <sdata:payloadPath />
</diagnosis>```

Thanks,

**Comment by darroncockram** [comment]
It looks like the deleted flag in the Sdata feeds for tradingActivities is hard coded to true so does not provide any in indication of if the record has been deleted in the main application. The fact that it is hard coded is also the reason you get an error when trying to filter on that field.

I've logged a bug with the Accounts team
