### ISSUE TITLE
Departments Not In SData?

### ISSUE THREAD

**Issue by tazmon95** [Sage/SData-2.0#84]
Hello,

I've been doing some process configuration and have run into an issue where we want to use the Departments capability for the different branches of our company.  I can create the departments, and I can assign each invoice line with a product to a specific department.  However I can not find any references to departments within the SData schema or linked to the SalesInvoiceLines.  Is there any way to pull this reference through the SData API?

Thanks,
John

**Comment by darroncockram** [comment]
Departments are not exposed to the Sdata feeds I'm afraid.
