### ISSUE TITLE
Sdata - GET operation failed - Unable to cast COM object of type 'System.__ComObject' to interface type 'Sage.Integration.Accounts50.SDOAdapter.ISDOEngine'

### ISSUE THREAD

**Issue by Paul-FSD** [Sage/SData-2.0#86]
Hi, 

Has anyone seen the error : GET operation failed - Unable to cast COM object of type 'System.__ComObject' to interface type 'Sage.Integration.Accounts50.SDOAdapter.ISDOEngine'

I have been using sdata on a test company on a development copy, with no issues.

However when I try and use sdata in the live environment, I get the above error.
If I run /sdata/$system/adapters or /sdata/accounts50/%24endPoints then everything looks fine, but as soon as I look at anything else I get the error! 

Thanks,

Paul.

Full error message : 

<?xml version="1.0" encoding="UTF-8"?>
-<diagnosis xmlns:http="http://schemas.sage.com/sdata/http/2008/1" xmlns:sme="http://schemas.sage.com/sdata/sme/2007" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:sdatasync="http://schemas.sage.com/sdata/sync/2008/1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.sage.com/sdata/2008/1"> <sdata:severity>error</sdata:severity> <sdata:sdataCode>ApplicationDiagnosis</sdata:sdataCode> <sdata:applicationCode/> <sdata:message>GET operation failed - Unable to cast COM object of type 'System.__ComObject' to interface type 'Sage.Integration.Accounts50.SDOAdapter.ISDOEngine'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{DE4DA901-EEF8-11D0-9E5F-008048AADD4E}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)). at Sage.Integration.Accounts50.SDOAdapter.SDOWorkspaceManager.GetEngine(Byte version) at Sage.Integration.Accounts50.SDOAdapter.SDOWorkspaceManager.GetWorkspace(IRequest request) at Sage.Integration.Accounts50.SDOAdapter.SDOWorkspaceScope..ctor(IRequest request) at Sage.Integration.Accounts50.SDOAdapter.Feeds.Company.GetActiveCompany() at Sage.Integration.Accounts50.SDOAdapter.Feeds.tradingAccountFeed..ctor() at RuntimeRequestHandlercfbeaf9bd1fd4b5e8054f917b0f6f913.CreateFeedInstance() at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.CreateFeedInstance() at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.OnGetRequest(IRequest request) at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.GetRequest(IRequest request) at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.OnGetResource(IRequest request) at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.GetRequest(IRequest request) (-1)</sdata:message> <sdata:stackTrace/> <sdata:payloadPath/> </diagnosis>

**Comment by darroncockram** [comment]
That happens is you try to connect to version of the data files that is not supported by the server you are connecting to.

**Comment by darroncockram** [comment]
Is Accounts installed on the server you connecting to. If so can you connect to the dataset via the Accounts UI?

**Comment by Paul-FSD** [comment]
Hi Darron, thanks for getting back to me so quickly.
When I first tried to connect the server's UI was out of date, and thought that it would be an issue.
So I've got it upgraded this morning, and can access via the UI, but the same error persists.
I will try rebooting the server or uninstalling completely if it's a version issue.

Thanks again,

Paul.

**Comment by darroncockram** [comment]
The upgrade should have sorted it out although the Sdata service will cache the company connection so a failed connection could be getting held on to. Rebooting the server should sort that or even simpler you could just restart the Sdata service.

**Comment by Paul-FSD** [comment]
Still no joy, restarted the service first, and then rebooted the server.
I have even tried reanaming the "C:\Program Files (x86)\Common Files\Sage SData" folder and repairing the install!

Looks like I will have to reinstall completely and try again. 

Thanks again Darron, much appreciated,
Paul.

**Comment by darroncockram** [comment]
I don't think a resinstall will help I'm afraid.

From the interface Id it would appear that the version of the data files it is trying to connect to is 15, which would mean it is Accounts 2009 version data. You do not say what version of Accounts you are running but Sdata support was only introduced in the 2012 release so data that old would not be natively supported by even the earliest version of the Accounts Sdata provider. You would need to either install Accounts 2009 or, probably the better option, upgrade the data to a version that is supported.

**Comment by Paul-FSD** [comment]
This is so weird, this server has never had 2009 on it, we are using V22 and pretty sure this server has only ever has V21 on it before. 
Thanks for the reply!

![untitled-1](https://cloud.githubusercontent.com/assets/28529989/25847513/5f305c3e-34ae-11e7-86d4-1717a4b784e0.gif)

**Comment by Paul-FSD** [comment]
Ok got it sorted, there was an old version of Sage HR that must have been interfering, uninstalled that and repaired accounts 50, now working. Thanks for all the help
