### ISSUE TITLE
How to enable SData datafeeds?

### ISSUE THREAD

**Issue by danieltharris** [Sage/SData-2.0#87]
Sorry this isn't directly related to the code sample, but when we go into Tools -> Internet Options -> SData Settings tab we can see that everything is turned on as expected and the firewall is configured correctly.

However, when we click onto Details (Next to the On checkbox) we just see a GCRM Tab explaining that the available datafeeds are shown below. However, there are no data feeds showing as available/enabled.

Is there any guidance as to how we can turn these on? There's no option in that tab specifically and the help pages don't specify how to do this - I assume once we turn on the customer datafeed (somehow) then the same application will start to be able to read that data back.

Struggling to find the appropriate documentation for this so any help would be greatly appreciated.

We are using Sage 50 Accounts v19 (2013 I believe)

**Comment by asterix187** [comment]
HI, is the data file on a different machine to the Sage 50 client you are using for sData? If so the sData Provider service on the Sage 50 client needs to be run as a user account the has network access to the folder the data is stored on.

**Comment by danieltharris** [comment]
There is a central server in the office where the data is stored (That I don't have RDP access to at the moment).

I logged into the Sage 50 Client on one of the users computers in the office (Which accesses the data from the network location) when I checked the SData settings - This is where I saw that the list of datafeeds was blank.

Do I need to get remote access to the server where the data is stored, log into the Sage 50 client locally on that server and re-check the settings there?

Ultimately once configured I am looking to make a call to (for example):
http://serverwheredatastored:5493/sdata/accounts50/gcrm/-/customer

So I want to hit another machine on the same network and get the response back - The machine making the call may not necessarily have Sage50 client installed at all.

If I've misunderstood how SData is configured and worked thanks for any help you can offer.

**Comment by asterix187** [comment]
Hi,

You won't need remote access but security is your issue. If you run task services.msc from a command prompt on the Sage 50 client then find the 'Sage SData Service'>Right Click Properties>Log On tab and change the Log on as to 'This Account' and enter in a username and password of a user who have rights to the folder the sdata is stored on. I would suggest for testing to use the user credentials you are logging on to the computer as (assuming its a network logon). Then restart the server and, assuming it starts, go back to Sage 50 to test the data feed shows up.

**Comment by danieltharris** [comment]
Thanks I'll try that and see how it goes - Just wanted to double check on the final sentence, it is the SData Service I need to restart rather than rebooting the server where the data is stored right?

Once I've done this, I assume it will just let me see the available data feeds? By default are all the datafeeds turned on and can they be enabled/disabled individually if we want?

**Comment by asterix187** [comment]
just the sData Service on the client machine.

**Comment by asterix187** [comment]
All datafeeds are available baed on what has been added to the Sage 50 client. We have written a Sage 50 (UK) connector and tend to set up a Sage 50 client on the CRM server and then just add the datasets to the client that we need to link to.

**Comment by darroncockram** [comment]
> However, when we click onto Details (Next to the On checkbox) we just see a GCRM Tab explaining that the available datafeeds are shown below. However, there are no data feeds showing as available/enabled.

The datasets shown in the Accounts UI are those retrieved via the localhost installation of the Sdata service and not necessarily those on one particular server. As @asterix187 mentions if you are trying to access data on the network whatever user this service is running as will require permissions to the location of the data. Hope that helps.

**Comment by danieltharris** [comment]
Thanks very much that's given me an idea of how the data is accessed and a few things to look into.

I'll see if I can get it working through one of the users machines here by changing who the service runs as and then make all the calls through that machine to get it working.

Do you know if the datafeeds allow writing to Sage 50 in v19? It's a product invoice that we want to be able to create via an SData endpoint so that they don't need to be entered manually

**Comment by darroncockram** [comment]
> Do you know if the datafeeds allow writing to Sage 50 in v19? It's a product invoice that we want to be able to create via an SData endpoint so that they don't need to be entered manually

They do although not all feeds are writable. You'd need to issue a schema request to the adapter to get the full list of which feeds support GET/PUT/POST/DELETE operations. The salesInvoice feed, which is the one you will need, supports GET and POST only in the Sag 50 Accounts adapter.

**Comment by asterix187** [comment]
Yes the sData feed is bi-drectional BUT there are some differences between what is available in each version of Sage 50. Also not all 'fields' of data are writable to in Sage 50 via sData. If you query the $schema you can get some of the info.

http://localhost:5493/sData/Accounts50/GCRM/-/salesinvoices/$schema as an example.
