### ISSUE TITLE
Sage 50 UK sData SalesOrders

### ISSUE THREAD

**Issue by asterix187** [Sage/SData-2.0#88]
Hello, I have found that the SalesOrders feed for UK Sage 50 does not expose, or set, the VAT number for the associated tradingAccount is not set against the SDO VAT_REG_NUMBER field. This causes an issue when creating orders for non uk customer via sData (for example Germany) as an error appears when setting the tax code against the line in Sage 50. This value is also not able to be set directly via sData. 

Is there a specific way to set this when posting an order? 

<img width="468" alt="ecvat" src="https://user-images.githubusercontent.com/7346013/27771583-56aa14ae-5f49-11e7-9952-dc835c8eaa6d.png">

**Comment by asterix187** [comment]
Hi Darron, I as under the impression that Sage 50 UK sData was in effect a wrapper over SDO? With SDO you need to set the VAT number against a sales order where the order is non UK. However, this can't be set via sData from what I can find.

**Comment by darroncockram** [comment]
> I as under the impression that Sage 50 UK sData was in effect a wrapper over SDO?

There was an SDO wrapper adapter created in the early days of Sdata support in Accounts 50 but this was discontinued before the official Sdata support was introduced in the 2012 release. The GCRM contract adapter is the only one available/supported currently.

> With SDO you need to set the VAT number against a sales order where the order is non UK. However, this can't be set via sData from what I can find.

You don't set the VAT number on the sales order, not even when using SDO. The VAT number is picked up from the customer record. In Sdata you just need to create the tradingAccount with an appropriate VAT number, using the taxReference field as mentioned above, and then create the salesOrder setting the appropriate taxCode on the salesOrderLine.

Hope that helps.

**Comment by asterix187** [comment]
You would think that BUT if it appears that if you create an order in Sage 50 against a, for example, Germany account and then query the data (via SDO sales_order) the field VAT_REG_NUMBER is populated. However, create an order via sData and the same field is null. This would indicate that either there is a field on the sales order in 50 called VAT_REG_NUMBER that is filled in when the order is create (and hence the error being thrown) or that somehow some kind of lookup isn't being used when creating the order via sData. If you go to the sData set order and reselect the same company account the field is then populated and the error is not thrown.

**Comment by asterix187** [comment]
I am pretty certain sData uses SDO. I have seen various references to things like Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.

**Comment by darroncockram** [comment]
I take it you mean ODBC rather than SDO. SDO does not expose a field called VAT_REG_NUMBER on the sales order (SOPData) but the ODBC driver does (SALES_ORDER table).

It turns out that when a sales order is created in the main Accounts UI it copies the data from the VAT number on the customer record to the VAT number on the sales order record. However this field is not exposed as writable outside of the UI so the Sdata adaper is unfortunately unable to replicate the functionality.

**Comment by asterix187** [comment]
Ahh so i was right (sort of! ODBC indeed). This is a bit of a nightmare as it makes the adaptor not support none UK customers for order creation. Is it not even writable for SDO?

**Comment by darroncockram** [comment]
Afraid not. It's not exposed to SDO at all.
