### ISSUE TITLE
Creating TradingAccount using Json

### ISSUE THREAD

**Issue by Superflyfox** [Sage/SData-2.0#89]
Pulling my hair out trying to create a customer using JSON and Java - keep getting 415 Unsupported Media Type error... Is this even possible to do this using JSON? I'm using this endpoint /sdata/accounts50/GCRM/-/tradingaccounts with a POST request (PUT brings up a 500 error). Any ideas or a sample JSON payload with minimum fields that need to be there??

I am able to update an existing record fine (using PUT) but can't create anything.

Also.... Is it possible to complete order using Sdata?

**Comment by darroncockram** [comment]
> keep getting 415 Unsupported Media Type error

The SIF and the Accounts Sdata adapter only support v1.0 and v1.2 of the Sdata standard. This means that although you can retrieve data in JSON format you cannot use it in a PUT or POST operation. You have to use XML.

> Also.... Is it possible to complete order using Sdata?

Afraid not.

**Comment by Superflyfox** [comment]
Thanks Darron, thought it may be possible as can update fine with JSON, spent hours trying with no luck...

**Comment by darroncockram** [comment]
The JSON support in the SIF is very limited. Unless you have bandwidth concerns I would always recommend using XML for operations on v1.0 or v1.1 Sdata adapters.
