### ISSUE TITLE
JSON and $updated field

### ISSUE THREAD

**Issue by kieronmoran** [Sage/SData-2.0#9]
The presence of the $updated field is inconsistent across feeds when using the JSON format.

For example - 
The presence of the $updated field is inconsistent across feeds when using the JSON format.

For example - 
http://localhost:5493/sdata/accounts50/GCRM//{C4C463BE-B098-4A7D-A23B-D1A92B8DCB59}/commodityGroups?format=json
will return 
{
$updated: "/Date(1430924678685+0100)/"
$url: "http://localhost:5493/sdata/accounts50/GCRM/{C4C463BE-B098-4A7D-A23B-D1A92B8DCB59}/commodityGroups(223770bf-dcd3-44ed-af9d-4b8c6ac395f3)?format=atomentry"
$uuid: "223770bf-dcd3-44ed-af9d-4b8c6ac395f3"
$httpStatus: "OK"
$descriptor: ""
active: true
type: null
reference: "1"
reference2: null
name: "Paper Products"
description: null
countryOfOrigin: null
financialAccounts: null
commodities: null
notes: null
}
whereas
http://localhost:5493/sdata/accounts50/GCRM/-/commodities?format=json
will return 
{
$url: "http://localhost:5493/sdata/accounts50/GCRM/{C4C463BE-B098-4A7D-A23B-D1A92B8DCB59}/commodities(e8012d90-469a-4c23-8258-78e2f5b7c31b)?format=atomentry"
$uuid: "e8012d90-469a-4c23-8258-78e2f5b7c31b"
$httpStatus: "OK"
$descriptor: ""
active: true
commodityGroup: null
commodityIdentifierType: "Total"
commodityIdentifiers: null
reference: "BOARD001"
reference2: null
status: null
name: "Whiteboard - Drywipe (900 x 1200)"
shortName: null
description: null
alternativeDescription1: "Whiteboard - Drywipe (900 x 1200)"
alternativeDescription2: null
type: "Presentation Supplies"
unitOfMeasure: null
buyingAllowedFlag: true
buyingUnitOfMeasure: null
buyingUnitOfMeasureNumber: null
sellingAllowedFlag: true
sellingUnitOfMeasure: null
sellingUnitOfMeasureNumber: null
packingUnitOfMeasure: null
packingUnitOfMeasureNumber: null
catalogueNumber: "U143"
supplierTradingAccount: null
supplierReference: "UNI001"
manufacturerCompany: ""
manufacturerReference: null
material: null
countryOfOrigin: null
weight: 0
weightKg: null
classification: ""
taxCodes: null
financialAccounts: null
dutyApplicableFlag: null
dutyRate: null
tradeIdentificationNumber: null
replacement: null
replacementDate: null
leadTime: null
cost: 15
associatedChildCommodities: null
associatedParentCommodity: null
version: null
commissionType: null
commissionAmount: null
commissionPercent: null
interactions: null
opportunities: null
salesQuotationLines: null
salesOrderLines: null
salesOrderDeliveryLines: null
salesInvoiceLines: null
salesCreditLines: null
purchaseOrderLines: null
purchaseOrderDeliveryLines: null
pricelists: null
prices: null
inStock: 5
allocated: 0
freeStock: 5
onOrder: 0
salesPrice: 18
}
These feeds are returned from the “Stationary & Mart” demo data company.
Please can this be looked at and an updated date field be added to all Sage 50 sData feeds.

**Comment by darroncockram** [comment]
Not sure why that would be the case as the commodity resource kind does have an updated property and it is returned in the ATOM feed format but I've raised the issue with the Accounts team.

**Comment by kieronmoran** [comment]
Thanks Darron.

I have also found that the same occurs for Prices and PriceLists.

If I find anymore, I will comment on this thread.

Regards,

Kieron

**Comment by geoffo** [comment]
Hi Darron,  I am seeing the same issue across some other tables as well (such as salesOrders, salesInvoices, etc.).  Is there a plan to add support for the $updated field?

**Comment by darroncockram** [comment]
It's definitely on the list of issues to be fixed but is with the Accounts team at the moment so I don't have an ETA at the moment I'm afraid. I'll post back here as soon as I hear something though.

**Comment by maloner** [comment]
Hi Guys - any news on when the $updated field will be available in JSON feed - makes it difficult to do any kind of sync between these systems without a date modified!

Thanks
