### ISSUE TITLE
Change Default Nominal Code in a TradingAccountCustomer

### ISSUE THREAD

**Issue by matiusmonkey** [Sage/SData-2.0#90]
Hi,

I am trying to work out how to change the Default Nominal Codes for tradingAccounts in Sage 50c (v23.2.4.278)

I am able to POST a new account, then PUT all the information I require into the relative fields and child fields (email, address, contacts etc) but the financialAccounts child seems to work a different way. The number doesn't seem to be amendable or GETable directly from tradingAccounts.

I can GET the default nominal code for the account using:

/sdata/accounts50/GCRM/-/tradingAccountCustomer(UUID OF ACCOUNT)/financialAccounts

But SData seems to reject any PUT requests to this url.

Any help would be greatly appreciated.

Thanks in advance,

Mat

**Comment by darroncockram** [comment]
You cannot set the default nominal code via the Sdata feeds I'm afraid.

**Comment by matiusmonkey** [comment]
OK, thanks for your mega quick response.
