### ISSUE TITLE
Sage 50 mark Invoice payed amount and post to ledger

### ISSUE THREAD

**Issue by AlfredGreene** [Sage/SData-2.0#91]
Hi
I am looking for a Sdata method to mark invoices payment amount and method and post to ledger although Ledger is not essential at this time.
I have created Invoice with no problem but can not find the method to mark as payment made at this time.
Thanks for your help in advance.
Regards
JD

**Comment by darroncockram** [comment]
This cannot be achieved using the Sdata feeds I'm afraid.

**Comment by AlfredGreene** [comment]
pitty would have been great final function for our needs.
