### ISSUE TITLE
Sage 50 UK - Sales Orders - Carrier Fields

### ISSUE THREAD

**Issue by geoffo** [Sage/SData-2.0#92]
Hi, I am trying to retrieve the Carriage details from the Footer tab of a Sales Order via SData but have not been successful in retrieving them.  I believe they should come back via the Carrier*** fields in the response but all these fields are either null or 0, even though the Sage UI displays values in these fields.  Is there a way to retrieve these Carriage fields, such as Courier, via SData?

**Comment by darroncockram** [comment]
Just checked on this and the only supported properties for the carriage details are carrierTaxCodes, carrierNetPrice and carrierTaxPrice. The other carrier properties should be flagged as sme:isUnsupported="true" but this flag is not currently set correctly by the looks of things.
