### ISSUE TITLE
Sage 50 UK - Create new Invoice

### ISSUE THREAD

**Issue by marcosholgado** [Sage/SData-2.0#93]
Hi,

I'm trying to create a new Invoice just as a test to see if we could do some simple integrations with Sage, mainly create a new invoice for a customer automatically. I guess that is something do-able but I just have no idea about how I can do it.

So far I have been able to get the invoices but I can get any POST to work, I get this error message all the time

'Object reference not set to an instance of an object.'

I have tried posting a JSON object but (unless I'm wrong) I've read that only xml is accepted for posting in most cases which is what I'm doing right now but I just can't get a correct xml and can't find which information should I put in.

What I've done is, I got an entry from the invoices we currently have in Sage, stripped it out and create a new xml which then I'm using to trying to create a new invoice but as said I get the error above. This is the XML I'm currently using.

`<entry xmlns:atom=“http://www.w3.org/2005/Atom“ xmlns:xs=“http://www.w3.org/2001/XMLSchema“ xmlns:cf=“http://www.microsoft.com/schemas/rss/core/2005“ xmlns=“http://www.w3.org/2005/Atom“ xmlns:http=“http://schemas.sage.com/sdata/http/2008/1“ xmlns:sdatasync=“http://schemas.sage.com/sdata/sync/2008/1“ xmlns:opensearch=“http://a9.com/-/spec/opensearch/1.1/“ xmlns:sme=“http://schemas.sage.com/sdata/sme/2007“ xmlns:sdata=“http://schemas.sage.com/sdata/2008/1“ xmlns:xsi=“http://www.w3.org/2001/XMLSchema-instance“>`
`<id/> `
`<title>Test</title>`  
`<content>Test</content> `
`<updated/>`
`<author><name/></author>`
`<sdata:payload>`
`<salesInvoice sdata:uri=“http://localhost:5493/sdata/accounts50/GCRM/{0E5BCFC4-CAC6-4545-9AAF-675E863DD137}/salesInvoice“ xmlns=“http://schemas.sage.com/crmErp/>`
`<CustomerID>HOLGADO</CustomerID>`
`<netTotal>0.1</netTotal>`
`<tradingAccount xsi:nil=“true“ /> `
`<grossTotal>0.1</grossTotal>`
`<date>2017-08-026</date>`
 `<time xsi:nil=“true“ />`
 `<taxDate>2017-08-26</taxDate>`
 `<taxCodes xsi:nil='true' />`
 `</salesInvoice>`
 `</sdata:payload>`
 `</entry>`

**Comment by darroncockram** [comment]
The problem is that you are giving it a null trading account, which is not supported by Sage 50 Accounts. You need to specify a valid for a tradingAccount that the salesInvoice is to be associated with e.g.

<crm:tradingAccount sdata:uuid="4FCCB79B-57B5-4D30-90BC-0688E8C6AEB8"/>

Hope that helps.

**Comment by marcosholgado** [comment]
Thanks for the help @darroncockram 

I didn't really know which was the minimum information I could send to create an invoice so I figured that previous xml out by looking at some invoices that we already had using http://192.168.110.55:5493/sdata/accounts50/GCRM/-/salesInvoices?count=10 

From those invoices is where I got the tradingAccount to null. I think is a bit confusing that sage50 requires a tradingAccount but the invoices that I get (somebody created them using sage) have it set to null. 

I'll give it a go using a tradingAccount and report back :)

Here is an example of the payload that I get from the previous URL.

` <sdata:payload>`
      `<crm:salesInvoice sdata:url="http://localhost:5493/sdata/accounts50/GCRM/{0E5BCFC4-CAC6-4545-9AAF-675E863DD137}/salesInvoices(23e84b4e-882b-4f57-a8fb-e8392be8daf2)?format=atomentry" sdata:uuid="23e84b4e-882b-4f57-a8fb-e8392be8daf2">`
        `<crm:active>true</crm:active>`
`        <crm:reference>20012</crm:reference>`
`        <crm:reference2 />`
 `       <crm:status>Written</crm:status>`
  `      <crm:allocationStatus xsi:nil="true" />`
   `     <crm:deliveryStatus xsi:nil="true" />`
    `    <crm:statusFlag xsi:nil="true" />`
     `   <crm:statusFlagText xsi:nil="true" />`
      `  <crm:type>Product Invoice</crm:type>`
    `    <crm:tradingAccount xsi:nil="true" />`
  `      <crm:customerReference />`
   `     <crm:opportunity xsi:nil="true" />`
    `    <crm:pricelist xsi:nil="true" />`
    `    <crm:copyFlag xsi:nil="true" />`
   `     <crm:date>2017-05-02</crm:date>`
    `    <crm:time xsi:nil="true" />`
    `    <crm:taxDate>2017-05-02</crm:taxDate>`
    `    <crm:taxCodes xsi:nil="true" />`
      `  <crm:postalAddresses xsi:nil="true" />`
     `   <crm:deliveryMethod xsi:nil="true" />`
      `  <crm:deliveryTerms xsi:nil="true" />`
      `  <crm:deliveryRule xsi:nil="true" />`
      `  <crm:deliveryDate xsi:nil="true" />`
      `  <crm:carrierCompany xsi:nil="true" />`
        `<crm:carrierTradingAccount xsi:nil="true" />`
        `<crm:carrierNetPrice>0.00</crm:carrierNetPrice>`
        `<crm:carrierTaxPrice>0.00</crm:carrierTaxPrice>`
        `<crm:carrierTotalPrice>0.00</crm:carrierTotalPrice>`
        `<crm:carrierSalesInvoice xsi:nil="true" />`
        `<crm:carrierTaxCodes xsi:nil="true" />`
        `<crm:carrierReference xsi:nil="true" />`
        `<crm:currency>GBP</crm:currency>`
        `<crm:operatingCompanyCurrency>GBP</crm:operatingCompanyCurrency>`
        `<crm:operatingCompanyCurrencyExchangeRate>1.00</crm:operatingCompanyCurrencyExchangeRate>`
        `<crm:operatingCompanyCurrencyExchangeRateOperator>/</crm:operatingCompanyCurrencyExchangeRateOperator>`
        `<crm:operatingCompanyCurrencyExchangeRateDate xsi:nil="true" />`
        `<crm:customerTradingAccountCurrency xsi:nil="true" />`
        `<crm:customerTradingAccountCurrencyExchangeRate xsi:nil="true" />`
        `<crm:customerTradingAccountCurrencyExchangeRateOperator xsi:nil="true" />`
        `<crm:customerTradingAccountCurrencyExchangeRateDate xsi:nil="true" />`
        `<crm:buyerContact xsi:nil="true" />`
        `<crm:salespersons xsi:nil="true" />`
        `<crm:salesInvoiceLines xsi:nil="true" />`
        `<crm:lineCount>0</crm:lineCount>`
        `<crm:originatorDocument xsi:nil="true" />`
        `<crm:salesOrderDeliveries xsi:nil="true" />`
        `<crm:receipts xsi:nil="true" />`
        `<crm:contract xsi:nil="true" />`
        `<crm:settlementDiscountType xsi:nil="true" />`
        `<crm:settlementDiscountAmount>0.00</crm:settlementDiscountAmount>`
        `<crm:settlementDiscountPercent>0.00</crm:settlementDiscountPercent>`
        `<crm:settlementDiscountTerms>0</crm:settlementDiscountTerms>`
        `<crm:settlementDiscountIncludedInTotal>true</crm:settlementDiscountIncludedInTotal>`
        `<crm:invoiceDiscountType xsi:nil="true" />`
        `<crm:invoiceDiscountAmount>0.00</crm:invoiceDiscountAmount>`
        `<crm:invoiceDiscountPercent>0.00</crm:invoiceDiscountPercent>`
        `<crm:invoiceAdditionalDiscount1Type xsi:nil="true" />`
        `<crm:invoiceAdditionalDiscount1Amount xsi:nil="true" />`
        `<crm:invoiceAdditionalDiscount1Percent xsi:nil="true" />`
        `<crm:invoiceAdditionalDiscount2 xsi:nil="true" />`
        `<crm:invoiceAdditionalDiscount2Amount xsi:nil="true" />`
        `<crm:invoiceAdditionalDiscount2Percent xsi:nil="true" />`
        `<crm:netTotal>40.80</crm:netTotal>`
        `<crm:discountTotal xsi:nil="true" />`
        `<crm:chargesTotal xsi:nil="true" />`
        `<crm:taxTotal>0.00</crm:taxTotal>`
        `<crm:grossTotal>40.80</crm:grossTotal>`
        `<crm:costTotal xsi:nil="true" />`
        `<crm:profitTotal xsi:nil="true" />`
        `<crm:text1 />`
        `<crm:text2 />`
        `<crm:projects xsi:nil="true" />`
        `<crm:financialAccounts xsi:nil="true" />`
        `<crm:interactions xsi:nil="true" />`
        `<crm:user>flight desk</crm:user>`
        `<crm:notes xsi:nil="true" />`
        `<crm:CustomerId>MCGREGOR</crm:CustomerId>`
      `</crm:salesInvoice>`
`    </sdata:payload>`

**Comment by darroncockram** [comment]
> From those invoices is where I got the tradingAccount to null. I think is a bit confusing that sage50 requires a tradingAccount but the invoices that I get (somebody created them using sage) have it set to null.

That is the way that Sdata works. It will only include complex properties if you explicitly request them to be included (see this page for details http://sage.github.io/SData-2.0/pages/core/0605/#include)

**Comment by marcosholgado** [comment]
That worked pretty well @darroncockram. Thanks again.

**Comment by jagrutisnsitindia-arch** [comment]
public function postToSage(Request $request)
    {
        $invoiceNumber = $request->invoice_number;

        // ?? Get invoice
        $invoice = DB::table('ready_invoices')
            ->where('InvoiceNumber', $invoiceNumber)
            ->first();

        if (!$invoice) {
            return back()->with('error', 'Invoice not found');
        }

        // ?? Use REAL Sage UUID (from tradingAccounts API)
        $sageCustomerUUID = "1aaf8f98-14f7-4bde-8bd9-fb1008829853";

        try {

            $url = $this->baseUrl . "/salesInvoices";

            // ? MINIMAL SAFE XML (NO tax, NO nominal, NO invoiceTradingAccount)
          $xml = '<?xml version="1.0" encoding="utf-8"?>
                    <entry xmlns="http://www.w3.org/2005/Atom"
                        xmlns:sdata="http://schemas.sage.com/sdata/2008/1">
                        <content type="application/xml">
                            <sdata:payload>
                                <salesInvoice xmlns="http://schemas.sage.com/accounts50">

                                    <reference>TEST123</reference>

                                    <date>2026-03-26T00:00:00</date>

                                    <tradingAccount 
                                        xmlns:sdata="http://schemas.sage.com/sdata/2008/1"
                                        sdata:uuid="1aaf8f98-14f7-4bde-8bd9-fb1008829853"/>

                                    <salesInvoiceLines>
                                        <salesInvoiceLine>
                                            <text>Test</text>
                                            <quantity>1</quantity>
                                            <actualPrice>10</actualPrice>
                                            <nominalCode>4000</nominalCode>
                                            <taxCode>T1</taxCode>
                                        </salesInvoiceLine>
                                    </salesInvoiceLines>

                                </salesInvoice>
                            </sdata:payload>
                        </content>
                    </entry>';

            // dd($xml);
            // ?? API CALL
            $response = Http::withBasicAuth($this->username, $this->password)
                ->withHeaders([
                    'Content-Type' => 'application/atom+xml;type=entry',
                    'Accept'       => 'application/atom+xml;type=entry'
                ])
                ->timeout(120)
                ->send('POST', $url, [
                    'body' => $xml
                ]);

            // ?? DEBUG OUTPUT
            dd($response->status(), $response->body());

        } catch (\Exception $e) {

            return back()->with('error', $e->getMessage());
        }
    }

i trying to connect laravel to sdata for invoice create but get error is <diagnosis xmlns="http://schemas.sage.com/sdata/2008/1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmln ?
  <sdata:severity>error</sdata:severity>
  <sdata:sdataCode>ApplicationDiagnosis</sdata:sdataCode>
  <sdata:applicationCode />
  <sdata:message>POST operation failed - Object reference not set to an instance of an object.

   at Sage.Integration.Accounts50.SDOAdapter.Feeds.salesInvoiceFeedEntry.Add(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.OnPostRequest(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.PostRequest(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.SdoequestManager.PostRequest(IRequest request) (-1)</sdata:message>
  <sdata:stackTrace />
  <sdata:payloadPath />
</diagnosis>

so how to do i
