### ISSUE TITLE
Updating Carrier Company

### ISSUE THREAD

**Issue by Superflyfox** [Sage/SData-2.0#94]
Is it possible to update the carrier company (which is the drop down courier field in Sage)? Can update carrierReference no problem, but have tried carrierCompany and carrierTradingAccount with no success. Is it possible

**Comment by darroncockram** [comment]
You don't say which product this is for but assuming it is Sage 50 Accounts then the carrier company is not exposed via the Sdata feeds I'm afraid.

**Comment by Superflyfox** [comment]
Thanks for the reply Darron.

Yes, you're right, using Sage Accounts Line 50 Pro. Is there a list of what fields which are updateable via SData for this version?  Would save a lot of head banging against the wall!

**Comment by darroncockram** [comment]
Unfortunately no list of updatable fields is maintained as the Sdata adapters are considered self-documenting through the $schema endpoints (http://sage.github.io/SData-2.0/pages/core/0207/).
