### ISSUE TITLE
SData Adapters

### ISSUE THREAD

**Issue by paulmumford** [Sage/SData-2.0#96]
Hi There,

Wonder if you could help with the following:

Is there any way to get the schema for an SData adapter which is not a “main” resource kind – i.e. tradingAccountCustomer or postalAddressCustRegistered as opposed to tradingAccount or postalAddress

OR, if the above is not possible,

Is it possible to programmatically know which “view” adapters relate to which main resources, i.e. tradingAccountCustomer is associated with tradingAccount, postalAddressCustRegistered is associated with postalAddress.  If we could at least do that, we could know that the schema for the view is the same as the main resource kind.

Hope that all makes sense!

Cheers,

Paul.

**Comment by jimothyj** [comment]
Hi Paul,

Not sure if this is of any use but I thought I'd drop it in, just in case.
https://github.com/Sage/SData-Contracts/blob/master/trunk/Tools/fullContract.html

Regards

**Comment by paulmumford** [comment]
Not what we were looking for I think but that’s a great resource we will add to our collection, thanks!

**Comment by darroncockram** [comment]
> Is there any way to get the schema for an SData adapter which is not a “main” resource kind – i.e. tradingAccountCustomer or postalAddressCustRegistered as opposed to tradingAccount or postalAddress

You can request the schema for any resource kind using a resource schema URL (http://sage.github.io/SData-2.0/pages/core/0207/). However having said that you should not work with anything that is not returned by the top level $schema response for the adapter as anything not included in this (such as tradingAccountCustomer and postalAddressCustRegistered) are inner workings of the adapter, not reusable across adaters and not really intended for eternal use in any event.

> Is it possible to programmatically know which “view” adapters relate to which main resources, i.e. tradingAccountCustomer is associated with tradingAccount, postalAddressCustRegistered is associated with postalAddress. If we could at least do that, we could know that the schema for the view is the same as the main resource kind.

No, but as noted above you should not need to work with the internal resource kinds. Everything supported by the adapter should be achievable using the types returned in the adapter $schema response.

Hope that helps.

**Comment by paulmumford** [comment]
Thanks for taking the time to respond darroncockram. It isn't the answer we were hoping for as it means changes in our software!

Does anyone else find it a bit odd that Sage themselves are incapable of answering this question? We are a developer partner and it does cost quite a bit and they just pointed us to this group. What is the deal with SData, is it actually a community product as opposed to a commercial one?

**Comment by darroncockram** [comment]
> Does anyone else find it a bit odd that Sage themselves are incapable of answering this question?

I work for Sage.

> We are a developer partner and it does cost quite a bit and they just pointed us to this group. What is the deal with SData, is it actually a community product as opposed to a commercial one?

You've hit the nail on the head there. Sdata is considered a community supported offering rather than being supported via the typical 3rd party developer channels.

**Comment by paulmumford** [comment]
Ok thanks darroncockram, we weren't sure where we stood on SData support, now we know where we stand we can work around our problems.
