### ISSUE TITLE
Few Questions and Problems - Date Functions, Member Filtering

### ISSUE THREAD

**Issue by jimothyj** [Sage/SData-2.0#97]
Hi Guys,

I've been struggling for days now and I'm getting increasingly frustrated, wondering if anyone can help:

Essentially what I'm trying to do is create some demand forecasting for my company for a few specific products. So I'm trying to a) check the usage via invoicing for the last 90 days and b) check the usage for the current month last year.

First problem, how am I supposed to filter by the member of a salesInvoiceLine? I've tried 

/sdata/accounts50/GCRM/-/salesInvoiceLines?where=commodity.reference eq '2312312'

Doesn't work.

/sdata/accounts50/GCRM/-/salesInvoiceLines?where=commodity.reference eq '2312312'&include=commodity

etc. and endless variations on the above.

Second problem, how are the date functions supposed to work? For example:

/sdata/accounts50/GCRM/-/salesOrders?where=date eq currentDate

This doesn't work, nor does

/sdata/accounts50/GCRM/-/salesOrderLines?where=date eq currentDate()

And again endless variations of trial and error getting me nowhere.

Can anyone please help? This is really starting to wear me down....

Thanks in advance.

**Comment by darroncockram** [comment]
The problem in both cases is that Accounts 50 adapter only provides the basic level of conformance for the Sdata query language. This means that the member operator and functions are not supported by it. Unfortunately you'd have no way of knowing that as the Sdata standard does not define a mechanism for discovering the level of query language conformance, something I have always felt is a bit of an oversight.

There's no good workaround for the first query you are trying to issue but the latter one has a simple workaround in that you can calculate the current date in your consuming application and pass it in as a constant date value when issuing the Sdata request.

**Comment by jimothyj** [comment]
Thanks for the quick response Darron!

That's an oversight alright...

Okay so, moving forwards, do you have any recommendations on how to achieve my end goal? (ie. How can I see usages for specific product codes). 

Many thanks

**Comment by darroncockram** [comment]
In some situations you can flip queries on their heads and query the lower level resource endpoint to achieve this kind of thing but unfortunately that would not help much in this case as you want to query on both a property of the commodity and of the salesOrderLine so regardless of which resource you start from you would have one or the other that you could not query on.

The only thing you could do is to query on one of the resource kinds with a filter on the property of that resource kind, include the related one and then further filter the results in your consuming code.  I would suggest querying on salesInvoiceLines as whilst there will be unwanted repetition repetition with the commodity being included multiple times in the response, the date filter on salesInvoiceLines would provide a better overall reduction in the initial data returned. Not ideal and not a greatly scale-able solution but it would be the closest you could get via Sdata.
