### ISSUE TITLE
ORDER BY in query with result not ordered

### ISSUE THREAD

**Issue by Myddleware** [Sage/SData-2.0#98]
Hi, 
I try to read data by ordering with the updated field. Here is my query : 
`select=firstName,familyName,phones,emails,website,id,updated,published&where=updated%20gt%20@2017-02-18T09:50:16+0100@&orderBy=updated%20desc`

I get this order : 
![order_desc](https://user-images.githubusercontent.com/11330301/31596434-8a0f9304-b210-11e7-92db-12c8708c9681.png)

Then I try the ASC order with this query : 
`select=firstName,familyName,phones,emails,website,id,updated,published&where=updated%20gt%20@2017-02-18T09:50:16+0100@&orderBy=updated%20asc`

And I get this order : 
![order_asc](https://user-images.githubusercontent.com/11330301/31596567-4ece9dde-b211-11e7-8d44-d69ab163fd24.png)

The order has changed but still not ordered. Could you  tell me what is wrong in my query ? Thanks for your help.

Have a nice day.

**Comment by darroncockram** [comment]
There is noting wrong with your query string. That is a known issue with the Sage 50 Accounts Sdata adapter where ordering is applied in group first and then by the fields int he orderBy parameter. This won't be readily apparent in your query as you are not including the type field which the Accounts adapter is grouping on the type field first and then applying ording.

**Comment by Myddleware** [comment]
Hi,
Thank you very much for you answer. Do you know when this bug will be fix ? 
Have a nice day.

**Comment by darroncockram** [comment]
There is no ETA for a fix at the moment I'm afraid.

**Comment by Myddleware** [comment]
OK no problem.
I need to read all data by package. So I will find a workaround by reading all data using the paging.
Have a nice day.
