### ISSUE TITLE
SData access to 50c data in Sage Drive?

### ISSUE THREAD

**Issue by Tedworthy** [Sage/SData-2.0#99]
We're in discussion with a potential client about a new website and they want this to integrate in with Sage, which seems perfectly possible using SData. They're currently using Sage 50 Accounts v23 but I believe just from 1 PC, storing data locally on that PC.

As I understand it, if they simply moved the storage of the accounts data to a server and accessed it over the network, they could then install the SData service on that server to expose it to us, so that the website could talk to Sage, assuming firewall rules were in place and ports were opened, etc.

However, they're currently looking at upgrading to Sage 50c, which seems to do something similar but syncs the accounts data to Sage Drive, in the cloud. With this option, is it possible for us to access the accounts data in Sage Drive directly using SData? Or do we still have to do this via the client PC, meaning it'd have to be permanently turned on to provide SData access?

I'm hoping that when you move to 50c and sync your data to Sage Drive, it then exposes it with the SData service running on the cloud servers Sage use for this task. I fear that this isn't the case, but I hope I'm wrong. Does anyone know if this is possible?

**Comment by darroncockram** [comment]
Sage Drive and Sdata are independent technologies. Having Sage Drive does not mean your data is automatically exposed via Sdata in the cloud. The Sdata service is installed with a full installation of Sage 50 Accounts, so data that you have synced locally via Sage Drive could be accessed via Sdata.

Hope that helps.

**Comment by Tedworthy** [comment]
Thanks Darron, that's what I assumed was the case. So in this scenario, even if the local PC with 50c Accounts was syncing with Sage Drive, that computer would need to be turned on for us to be able to access data from it using SData? I guess then in order for things to remain accessible over SData regardless of the state of the local PC, our client would need to set up a server on their network for the SData service to run on?

**Comment by darroncockram** [comment]
> So in this scenario, even if the local PC with 50c Accounts was syncing with Sage Drive, that computer would need to be turned on for us to be able to access data from it using SData?

Correct.

> I guess then in order for things to remain accessible over SData regardless of the state of the local PC, our client would need to set up a server on their network for the SData service to run on?

You'd need an active machine running the Sdata service somewhere. The data does not need to be local to that machine, although I would recommend it is for performance reasons.

**Comment by Tedworthy** [comment]
Thanks for the clarification Darron, much appreciated. All makes sense.
